### ISSUE TITLE
Consume core Penta updates: Clipboard copy

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10002]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6194

**Comment by thatblindgeye** [comment]
@andrew-ronaldson @lboehling doesn't look like React needs any updates, based on comparing the [React v6 staging](https://patternfly-react-v6.surge.sh/components/clipboard-copy) to [Core v6 staging](https://pf6.patternfly.org/components/clipboard-copy). React buttons may be slightly wider, but that may be due to the icons themselves.

One question: are the background colors correct in dark mode for the readonly and editable variants? I assume the colors are intended to match what light theme is doing, where the readonly variant has a darker background than the editable variant?

**Comment by srambach** [comment]
LGTM 📋

**Comment by andrew-ronaldson** [comment]
Good to go!
