### ISSUE TITLE
Expand all, not just section for Navigation - Expand all icon for the navigation for observability of items

### ISSUE THREAD

**Issue by kuklas** [patternfly/patternfly-react#10014]
This is an extension to existing [navigation component](https://www.patternfly.org/components/navigation)

In Red Hat Insights that lives on console.redhat.com we would like to provide an expand all button for the whole navigation. So pretty much the expected behaviour is to have a single click expand button in the navigation so all the items within the navigation expand.
The benefit of this is observability and quick findability of the desired page. Saves two or three clicks, based on how deep the navigation item is hidden. And for new customers they can get a quick peek into what is in the navigation itself.

I believe currently these is only expandable section, and no expand all for everything for navigation.

![image](https://github.com/patternfly/patternfly-react/assets/78739379/03b8ccd7-3c66-4e78-81f2-3a386359ee46)

**Comment by tlabaj** [comment]
cc @andrew-ronaldson for UX input.

**Comment by kuklas** [comment]
pinging this

**Comment by andrew-ronaldson** [comment]
We could do this but I’d want UX input. 
Couple thoughts/questions:

- Do we add another row with an expand/collapse all interaction. Switch or check maybe?
- Does it just expand the first layer of nav items. What happens if there is another layer like flyouts.
- A possible interaction (also not supported) would be a search in the nav that could highlight the nav item and expand only that section. Going from not enough visibility to everything can be overwhelming if the nav is large.

**Comment by kuklas** [comment]
The navigation in console.redhat.com Insights has multiple levels, like 2 or 3. The idea is to expand everything to see everything at glance.

- I dont know if we should utilize the space next to Red Hat Insights or add another row. I think that we would utilize the space we have not add more. But im open to suggestions
- I would expect to expand all items, even second third layers
- I understand that, but we have a search already

**Comment by kuklas** [comment]
Showed this on Patternfly design share, I will mockup a kebab with expand all, collapse all
- https://redhat-internal.slack.com/archives/C04FXDR3ZJ8/p1696341333048219 here is the conversation about expand all
