### ISSUE TITLE
Checkbox Component Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#1006]
1. What is the interaction difference between the Controlled and Uncontrolled Checkbox. I'm assuming that the Uncontrolled Checkbox would be like the Uncontrolled Switch, where the user cannot manipulate its state? Right now I can check it.
2. Custom Label Checkbox should be removed from the React example as there is no example in Core or in Wireframes. @mcarrano do we want to create an issue for this Custom label checkbox with the badge? 
3. When checkboxes exist in a group, a user can select as many checkboxes as they want. Can we add more checkboxes to the Controlled Checkbox example to demonstrate this functionality?

**Comment by mcarrano** [comment]
I do not forsee a use case for the Custom Label Checkbox. IMO it can be removed.

**Comment by rachael-phillips** [comment]
Will need to update per changes made in: https://github.com/patternfly/patternfly-next/issues/1209

**Comment by rebeccaalpert** [comment]
Hey @rachael-phillips - We're already not using aria-disabled for checkboxes.

I think the other change is talking about checkboxes specifically in the context of menu items. The basic PF4 Dropdown doesn't seem to support checkboxes well right now at all. (I added one in to an example and you can't click it. It's also not included in the dropdown's arrow key navigation.)

Are you looking for a Dropdown Multi-Select to be added? If so, is it okay if that's a separate issue?

**Comment by rebeccaalpert** [comment]
Spoke to @rachael-phillips about the changes outlined in https://github.com/patternfly/patternfly-next/issues/1209.

The second piece of feedback (copied below) is related to the upcoming Custom Select Component in https://github.com/patternfly/patternfly-react/issues/1206. I won't be able to address it here since the component is not yet available. It'll need to be addressed by whoever takes on https://github.com/patternfly/patternfly-react/issues/1217.

> Make the area that displays a background color clickable. In general, anywhere that hover styles display should also be clickable when possible. This can be done by changing div.pf-c-check pf-c-dropdown__menu-item to label.pf-c-check pf-c-dropdown__menu-item, and label.pf-c-check__label to span.pf-c-check__label. The same class structure can still be used, just swap out the elements.

I'll address the other comments in this PR though.
