### ISSUE TITLE
Gatsby not generating props for typescript

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1033]
Currently Gatsby is not generating props for typescript files.  'babel-plugin-react-docgen-typescript' is being used in gatsby-node.js, however we are not currently getting any props generated for tsx files in react-core such as Avatar.tsx

**Comment by dgutride** [comment]
The gatsby team appears to be working on a fix for this on their end - I opened an issue on their repo to try to figure out if there is a timeframe on a fix.  Moving to gatsby-transformer-react-docgen 3.0.5 does start to include some props in the response so that might be an option temporarily.
@jschuler @dlabaj 
https://github.com/gatsbyjs/gatsby/issues/11650
