### ISSUE TITLE
Bug - charts - prerelease causing build error in OCP 

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10402]
```
ERROR in public/components/graphs/tooltip.tsx:279:41
TS2349: This expression is not callable.
  Each member of the union type '{ <S extends string>(predicate: (value: string, index: number, array: string[]) => value is S, thisArg?: any): S[]; (predicate: (value: string, index: number, array: string[]) => unknown, thisArg?: any): string[]; } | { ...; }' has signatures, but none of those signatures are compatible with each other.
    277 |           ...legendTooltipProps,
    278 |           // For non-stack graphs, remove the text for "mainDataName"
  > 279 |           text: legendTooltipProps.text.filter(
        |                                         ^^^^^^
    280 |             (t, i) => legendTooltipProps.legendData[i].name !== mainDataName,
    281 |           ),
    282 |         };
```

The code is in [this file](https://github.com/openshift/console/blob/master/frontend/public/components/graphs/tooltip.tsx) in OCP.

**Comment by kmcfaul** [comment]
cc @nicolethoen 

After talking it through with Dan, this is something OCP will have to update on their side. The issue was caused because the return type of `legendTooltipProps.text` after they fetch it can be multiple types (including a function return), so they need to type check that it is an array first before calling `filter`. It was probably not marked as an error until our version of typescript was updated to something more strict. 

It's also worth mentioning that the helper function they are using (`getLegendTooltipVisibleText`) isn't one we expose officially and is marked as private.
