### ISSUE TITLE
Test error: Cannot find the Button's disabled attribute

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10927]
**Please describe the issue**

4 tests cannot find the Button's `disabled` attribute. This test worked with v5, but no longer works with v6.

**Are there visuals for this issue? Please provide screenshots**

Error 1
![Screenshot 2024-08-28 at 6 31 05 PM](https://github.com/user-attachments/assets/036a4bf5-ad61-44c1-a699-fba0a7a028b1)

Error 2
![Screenshot 2024-08-28 at 6 24 00 PM](https://github.com/user-attachments/assets/e03631d4-7e3c-4221-81f4-e74ff65d702b)

Error 3
<img width="866" alt="Screenshot 2024-08-28 at 6 29 49 PM" src="https://github.com/user-attachments/assets/5486ff40-681a-44c3-89a0-f55fa1f14e11">

Error 4
<img width="866" alt="Screenshot 2024-08-28 at 6 30 19 PM" src="https://github.com/user-attachments/assets/056ec6ca-b2f1-4068-8856-a3c6dfcccb7d">

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

Error 1
- Test https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModelsDetails/dialog.test.tsx#L81
- Button https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModelsDetails/utils/dialog.tsx#L24

Error 2
- Test https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.test.tsx#L275
- Button https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.tsx#L131

Error 3
- Test https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.test.tsx#L335
- Button https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.tsx#L131

Error 4
- Test https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.test.tsx#L355
- Button https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/settings/costModels/costModel/updateRateModel.tsx#L131

**Comment by wise-king-sullyman** [comment]
These failures are because we added a new wrapping div around the text inside of buttons in v6, and the RTL `byText` query is now returning that wrapper rather than the button element itself, which is where those attributes live.

I would suggest using `byRole` queries instead and passing a `name` option searching for the text value you're currently passing into the `byText` query, as it will return the top level button element. Also FWIW the RTL team does [suggest prioritizing the use of `byRole` queries over `byText` when possible](https://testing-library.com/docs/queries/about/#priority).

**Comment by dlabrecq** [comment]
Updated to use byRole
