### ISSUE TITLE
Component - Dropdown, Infotip & Kebab

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#11]
Implement one or more components that provide the following UI elements:

- ~~[PatternFly Dropdown](http://www.patternfly.org/pattern-library/widgets/#dropdowns)~~ *This has been contributed in #130*
- ~~[PatternFly Kebab](http://www.patternfly.org/pattern-library/widgets/#kebabs)~~ *This has been contributed*
- [PatternFly Infotip](http://www.patternfly.org/pattern-library/widgets/#info-tip)
- ~~Menu items~~ *This has been contributed*

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see links above)
- the component supports:
  - disabled menu items
  - drop the menu down or up
  - drop the menu left or right
  - conditional class to display component as a kebab instead of the button

**Comment by jtomasek** [comment]
I've been implementing this functionality in TripleO UI currently together with Toolbar components. We've made a decision to use react-bootstrap since it plays very well with PatternFly styling and we did not have to reimplement the components and can be sure that Dropdown etc. works properly.

I am happy to contribute those components if we agree on adding react-bootstrap as a dependency to patternfly-react

Here is a link to patch which adds these components to tripleo-ui: https://review.openstack.org/#/c/452175/

**Comment by jgiardino** [comment]
The work that remains for this component is to add the [Infotip variation](http://www.patternfly.org/pattern-library/widgets/#info-tip)

We might also want to consider grouping "Button" and "DropdownKebab" storybook sections into a single section labeled "Buttons and Dropdowns"?

**Comment by jeff-phillips-18** [comment]
Added #170 to complete the remainder of this issue.
