### ISSUE TITLE
Charts - update font-family

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#11116]
Just noticed that axis labels and tooltips look like they're not using the correct font-family. Specifically it looks like these places:
* I didn't dig into this one but I assume it's removing spaces from the var value? If so it's worth noting that we went from our font being defined as ["RedHatText" in v5](https://github.com/patternfly/patternfly/blob/7471dc83929f370cf177e5fcb41632b483950a20/src/patternfly/sass-utilities/scss-variables.scss#L200) to ["Red Hat Text" in v6](https://github.com/patternfly/patternfly/blob/b93029abee9117da890c05f219412e3c423d57b4/src/patternfly/base/tokens/tokens-default.scss#L65), so we'll just want to make sure those spaces are retained https://github.com/patternfly/patternfly-react/blob/a3ffb39a0cc2c9130f7db86ad3186787ba12648e/packages/react-charts/src/victory/components/ChartTheme/themes/base-theme.ts#L129
* This look like an example style, but it should probably be updated to be more accurate? https://github.com/patternfly/patternfly-react/blob/a3ffb39a0cc2c9130f7db86ad3186787ba12648e/packages/react-charts/src/victory/components/ChartBoxPlot/examples/ChartBoxPlot.md?plain=1#L227
* Samesies for this one https://github.com/patternfly/patternfly-react/blob/a3ffb39a0cc2c9130f7db86ad3186787ba12648e/packages/react-charts/src/victory/components/ChartTooltip/examples/ChartTooltip.md?plain=1#L306

cc @dlabrecq

**Comment by dlabrecq** [comment]
I don't believe Victory can handle white space in the theme. However, looking at the v6 area chart example via patternfly.org and it appears the axis labels, legend labels, etc. are using the correct font.

The browser inspector shows: 

`font-family: "RedHatText", "RedHatText", "NotoSansArabic", "NotoSansHebrew", "NotoSansJP", "NotoSansKR", "NotoSansMalayalam", "NotoSansSC", "NotoSansTC", "NotoSansThai", Helvetica, Arial, sans-serif;`

![Image](https://github.com/user-attachments/assets/cb15be4f-76e9-496a-af3a-6eb3b25b406e)

**Comment by mcoker** [comment]
As far as I can tell, all of the axis labels, legends, and tooltips that I see are using the wrong font ("RedHatText" instead of "Red Hat Text")

![Image](https://github.com/user-attachments/assets/f8af92ee-40ce-433c-b37c-0d27af275f48)

Here's an example of text that's using the correct font-family. And FWIW wherever the correct family is specified, it looks like the font famnily names are a fallback for the `var(--pf-v6-chart-global--FontFamily)` var, like:

> font-family: var(--pf-v6-chart-global--FontFamily, "Red Hat Text", "RedHatText", "Noto Sans Arabic", "Noto Sans Hebrew", "Noto Sans JP", "Noto Sans KR", "Noto Sans Malayalam", "Noto Sans SC", "Noto Sans TC", "Noto Sans Thai", Helvetica, Arial, sans-serif)

![Image](https://github.com/user-attachments/assets/626c30c5-ce78-45b8-94dd-e63074aa30f3)

**Comment by dlabrecq** [comment]
Thank you for clarifying

**Comment by dlabrecq** [comment]
Is there a particular reason why it's "Red Hat Text" instead of "RedHatText"?
I ask because we updated Victory to support "RedHatText" via this PR https://github.com/patternfly/patternfly-react/pull/5301
Even if we stop removing the whitespace, "Red Hat Text" will not work properly.
The character spacing will be off unless "RedHatText" is used

**Comment by dlabrecq** [comment]
@mcoker Why do we have both "Red Hat Text" and "RedHatText"?
I ask because we updated Victory to support "RedHatText" via this PR https://github.com/patternfly/patternfly-react/pull/5301
Victory is using "RedHatText"'s character spacing to to caclulate padding, etc. -- it doesn't know about "Red Hat Text"

**Comment by mcoker** [comment]
@dlabrecq gotcha! @lboehling do you remember anything around why we're using "Red Hat Text" vs "RedHatText" as the font family name on the page? Curious if we're aligning with any other groups at RH on that, and if we should consider declaring the font-family in PF as both "Red Hat Text" and "RedHatText" for anyone that may not be using our [font-family token](https://github.com/patternfly/patternfly/blob/42db5f3be828c93942814957b663671e8374fffd/src/patternfly/base/tokens/tokens-default.scss#L65) and might have specified "RedHatText" as their font family somewhere.

**Comment by dlabrecq** [comment]
Turns out that Victory implemented a reliable way to calculate character widths dynamically. The existing character map is now a backup (e.g., when there is no window object) -- likely for use with React native (i.e., iOS, Android, etc.).

The "Red Hat Text" (avg: 0.5413177633285524) character width is comparable to the previous font. Considering "RedHatText" (avg: 0.5341940789473685) is already supported, we don't need to update Victory upstream.

**Comment by tlabaj** [comment]
closed by #11122
