### ISSUE TITLE
PF4 Dropdown close broken

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#1113]
You cannot close the dropdown clicking on it anymore. As a workaround you can click somewhere on a page to close it.

**Comment by ibolton336** [comment]
The introduction of the focus-trap-react library has introduced this bug. @tlabaj When i remove the focus trap wrapper, this issue goes away. can you fill me in on what the accessibility requirements were around this so that I can take a look? https://github.com/patternfly/patternfly-react/issues/787 @jgiardino

**Comment by rhamilto** [comment]
Note Dropdown Panel is not affected.
