### ISSUE TITLE
Add coveralls reporting to pf4 packages

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#1175]
Need to evaluate the coverage reporting in coveralls and make sure the pf4 packages are being reported on as well.

**Comment by dtaylor113** [comment]
PF4 packages do appear to be included in Coveralls reporting:
![image](https://user-images.githubusercontent.com/12733153/51185686-d2fd5900-18a5-11e9-91ed-aaf6b81e6033.png)

**Comment by redallen** [comment]
Coveralls is really just a wrapper on `jest`'s coverage report which is enabled [here.](https://github.com/patternfly/patternfly-react/blob/master/package.json#L135) Coveralls seems to have had a lot of [issues](https://github.com/lemurheavy/coveralls-public/issues?utf8=%E2%9C%93&q=%22source+not+available%22) with getting source files to show since 2014, and on top of that it shows inconsistent results vs my manual inspection now, even on master. It may be time to investigate using [codecov](https://docs.codecov.io/docs), or [code climate](https://codeclimate.com/oss/).
