### ISSUE TITLE
PF4 Dropdown: Show onClick with examples

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1208]
The Dropdown examples show how to open the menu, but do not show which item was clicked -- that functionality is missing from the demo.

I figured out how to do this myself. However, it may be helpful to others if shown in the dropdown examples?

```
<DropdownItem
  key={option.value}
  onClick={event =>
    this.handleGroupByItemClick(event, option.value)
  }
>
  {t(`group_by.values.${option.label}`)}
</DropdownItem>
```

**Comment by priley86** [comment]
+1 

I was attempting to use `DropdownItem` with React Router configured in my application today. I noted that I would have to define the `onclick` behavior so that page refreshes did not occur and `history.push` could be used in rendering an anchor with an `href` instead of a `button`.  It might be nice to add a note about this in the docs for anyone using a single page app router (like React Router). 

```
          <DropdownItem key={option.label}
            isDisabled={isDisabled}
            onClick={e => {
              e.preventDefault();
              if(option.callback){
                option.callback();
              }
              if(option.href) {
                history.push(option.href);
              }
            }}
            href={option.href}
            component={option.href ? 'a' : 'button'}>
            {option.label}
          </DropdownItem>
```

**Comment by dlabrecq** [comment]
This would still be a good addition to the examples
