### ISSUE TITLE
PF4: Custom Select Component: Checkbox select (multiple items) variation

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1217]
This issue covers the Checkbox select (multiple items) variation of the Custom Select only:
(This issue is a child of issue #1206 )

On hold until the Single select variation is complete (issue #1214 )

Related issue in Core: patternfly/patternfly-next#651

Info provided on the component: https://docs.google.com/document/d/1rrCdARutABI-Vpa_mdMWGl2xJJTtt2dPQ2bjFx2zwCM/edit?usp=sharing

see: https://pf-next.com/components/Select/examples/

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @srambach (CSS) @mcarrano (interaction design) @christiemolloy (visual design)

**Comment by jgiardino** [comment]
There was some discussion in the a11y meeting today related to this component. Here's a recap of some things discussed:

- This variation of the Select component will use the behavior described in this issue: https://github.com/patternfly/patternfly-react/issues/839 (i.e. the panel behaves similar to a popover)
  - #839 is intended to allow consumers to use the Dropdown component and customize what displays in the panel that pops up. 
  - Having the panel behave like a popover allows us to manage the visibility relative to focus. The panel will trap focus, and isn't hidden until the user explicitly exits it. This will be the default behavior of the Dropdown Panel variation of the dropdown.
- Since for this case we know what the contents of the panel are, we can also include additional keyboard interaction behavior so that a sighted keyboard-only user will have similar experiences for components that look the same (i.e. toggle that displays something with a menu). We might not be able to have complete parity, but maybe at a minimum can:
  - enable the arrow keys to shift focus between menu items
  - have Tab on the last menu item exit the menu
- It might make sense to start off with basic functionality first (e.g. basic popover functionality) and do a round of testing, and incrementally add the arrow key and tab key functionality then test again, in case these updates cause the component to not work at all in one of the screen readers.

**Comment by kmcfaul** [comment]
@jgiardino For clarification, should Checkbox Select behave differently than Dropdown for keyboard input? The custom dropdown, Dropdown Panel, currently matches our Dropdown's behavior: it does not use a focus trap, arrow keys are used to navigate items, and tab closes the menu regardless of position. 

The other issue I've run into is that you cannot natively pass focus to a label, so I've added a tabIndex to the labels for the moment to allow focusing. I'm not sure if there's a better way to handle that.

**Comment by jgiardino** [comment]
My expectation is that this panel would be implemented using the behavior described for #839, primarily because these menu items include checkboxes. It might make sense to consider implementing the keyboard interaction to be similar to other menu items, but that seems like something we can add later as an enhancement if we realize that the default keyboard interaction you get with checkboxes doesn't behave as users expect.

For setting focus, have you tried setting focus on the `<input type="checkbox">` element instead of the `<label>` element? I would think selecting the checkbox would only work if the checkbox has focus, so that's probably the better element to add focus to.

If that isn't possible, then I think exploring whether focus can be set on a wrapper for the panel might be a decent alternative.

**Comment by kmcfaul** [comment]
@jgiardino It's more that the way I have Select implemented, I can easily reuse the keyboard interaction to match the Single Select (and Dropdown) interactions. 

I've tried setting focus on the input itself but it only focuses the checkbox itself rather than the whole label, making it hard to see. Wrapping the whole label would probably also work but I would still have to add a tabIndex because divs are also not natively focusable. I'll play around with it more.

**Comment by jgiardino** [comment]
My main concern with using the same keyboard interaction as it is for the Single Select example is that the Tab key no longer behaves as expected with the type of element being presented (i.e. a checkbox).

I'm not opposed to enabling the arrow keys, as long as they don't interfere with the standard keyboard behavior that's expected with the roles associated with this. But I think we should at least implement the behavior that's expected of the roles being used in this component. I would say that the roles used in this component consist of a button that displays a modal with a form (or something like a form) of checkboxes. Buttons and forms are keyboard accessible by default. And the modal requires some handling, but hopefully that's a pattern that's easily reusable here.

> I've tried setting focus on the input itself but it only focuses the checkbox itself rather than the whole label, making it hard to see.

Setting focus on the input itself is the behavior I would expect. As a future enhancement, we might be able to update core to provide better focus indication, but the focus provided should be coming from the browser, which many people argue is better than providing custom focus indicators, since that's what users are used to.

**Comment by dgutride** [comment]
Closing - PR merged:  https://github.com/patternfly/patternfly-react/pull/1487
