### ISSUE TITLE
Update background image component.

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-react#1240]
Background image component
https://pf-next.com/components/BackgroundImage/examples/
Core PR
https://github.com/patternfly/patternfly-next/pull/1285

We now include the svg inline to fix a bug with safari.

**Comment by priley86** [comment]
An additional request here from the Open Shift side would be to conditionally load the background images per the current breakpoint. Today, the `BackgroundImg` loads all images. This is not ideal and we should only load the single image needed for current screen size.

**Comment by priley86** [comment]
Actually, this may have been recently resolved... i'm not seeing this while loading the page here anymore.
http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-default-nav

![screen shot 2019-02-18 at 4 20 25 pm](https://user-images.githubusercontent.com/4237045/52976859-25480300-3399-11e9-8498-8e1cdb657b25.png)

**Comment by rachael-phillips** [comment]
@priley86 just following up. Has this been resolved?

**Comment by priley86** [comment]
@rhamilto ^^ any thoughts? I think last we spoke we wanted to look into the default background size. Would appreciate any further feedback when you get a chance (and let me know if you need anything at all).

**Comment by rhamilto** [comment]
Looks fine.  But note the reason we are not using this component in OpenShift console is because **multiple, resolution dependent, very large** background images were being **bundled** with the console.  And of those large background images, **only a small sliver of each image was ever visible** in the console.  So rather than bundling several megs of images (most of which was never visible in the console), we're opting to only serve **one relevant image** that meets the specific needs of the OpenShift console.  For comparison, [pfbg_1200.jpg](https://github.com/patternfly/patternfly-next/blob/master/static/assets/images/pfbg_1200.jpg) clocks in at 271 KB.  [Our override](https://github.com/openshift/console/blob/master/frontend/public/imgs/pfbg_2000.jpg) is 24.9 KB.  So our override is getting us the same visual effect but with **only 24.9 KB regardless of viewport size**.   The [smallest image from this component](https://github.com/patternfly/patternfly-next/blob/master/static/assets/images/pfbg_576.jpg) still clocks in at 65.9 KB (that's 41 KB more than the image we're using for **all** viewport sizes).

**Comment by rhamilto** [comment]
It may be worth noting the about modal has this same issue (multiple, resolution dependent, very large background images are being used, but only a small portion of each image is ever visible) and we've also implemented an override in OpenShift.

**Comment by rhamilto** [comment]
> multiple, resolution dependent, very large background images are being used, but only a small portion of each image is ever visible

Er, that should be a single, very large background image.

**Comment by priley86** [comment]
so @rhamilto - in summary, it seems this is no longer a CSS/JS loading issue, but just an issue w/ the default assets used? I am under the assumption we could use the `BackgroundImage` component as-is and override the default assets in the future (with the background filter applied). Is this fair? Happy to create a branch of this for you to experiment with again if needed...

**Comment by rhamilto** [comment]
> in summary, it seems this is no longer a CSS/JS loading issue, but just an issue w/ the default assets used? 

Personally, I think the component is overkill since:

1.  the vast majority of the pixels in the images served are never seen.
2.  the background image is just providing visual decoration; it seems to me there is no need for such high resolution images for what amounts to decoration.

>  I am under the assumption we could use the BackgroundImage component as-is and override the default assets in the future (with the background filter applied).

We could, but I'm not sure how much benefit there would be to doing so.  Adding the component to then override it seems overly complicated when a straight CSS addition in the console code base achieves the desired result.

**Comment by priley86** [comment]
ok, thanks for clarifying it much further here! I certainly understand your reasoning much better now. In this case (and dependent on designs), it may make sense to keep as-is and close this issue. Your current use case is certainly supported by the framework, but I don't always know the design intent best. 

@rachael-phillips @janwright73 @kybaker @matthewcarleton  - please feel free to follow up w/ @rhamilto on this. I don't know that there is much more from a PF perspective on this...

**Comment by mcoker** [comment]
For what it's worth, with the new brand guideline updates that we're implementing now, we're pulling the background from the page component entirely, and will be using a solid background color in the masthead. As for the background image on the about modal, wizard, and login pages, we're replacing the existing background image with an SVG that is significantly smaller. Hopefully that will resolve all of these issues.

**Comment by LHinson** [comment]
@mcoker that's really helpful. Does that mean this can be closed since we are taking a different approach entirely? CC @jessiehuff

**Comment by mcoker** [comment]
This issue still applies for the time being, since the [login component](https://pf4.patternfly.org/components/Login/examples-full/?component=Login%20Simple) currently uses the background image with the filter. The background image in the login component will be updated at some point though.
