### ISSUE TITLE
Add split-button dropdown

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1287]
https://github.com/patternfly/patternfly-next/pull/1263/

This is a new variation of a dropdown. The current dropdown toggle element changed from a `button` to a `div`, and you can now put interactive elements in the toggle `div` and those control the menu. Our current example shows a `button.pf-c-dropdown__toggle-button` and `label.pf-c-dropdown__toggle-check` (with an `<input type="checkbox">` in it) in the toggle area, but that could be 3 buttons, 2 buttons and a check, etc. We may add more things like the `pf-c-dropdown__toggle-button/check` later. The aria properties will move from the current `button.pf-c-dropdown__toggle` to the element(s) that control the menu - in this example, that's `.button.pf-c-dropdown__toggle-button`.

**Comment by mturley** [comment]
I'm debating between two implementations here and could use some guidance on which to choose:

1. Make a new `DropdownSplitButton` component that the consumer can pass to the `toggle` prop of `Dropdown`, which renders the `<div class="pf-c-dropdown__toggle pf-m-split-button">` and whose children will include whatever interactive elements the user wants, including a `DropdownToggle` which is mostly left alone (but needs some prop to tell it to use the class `pf-c-dropdown__toggle-button`). This is the most flexible (the user could in theory put some other elements after the DropdownToggle) but requires some redundancy (when it's disabled, the `DropdownSplitButton` and `DropdownToggleCheckbox` and `DropdownToggle` all need to render differently, so do you have to pass `disabled` to each of them? do they all need to consume some context for that?)

    ```js
    <Dropdown
        onSelect={this.onSelect}
        toggle={(
          <DropdownSplitButton>
            <DropdownToggleCheckbox id="example-checkbox-1" />
            <DropdownToggle isButton onToggle={this.onToggle} />
          </DropdownSplitButton>
        )}
        isOpen={isOpen}
        dropdownItems={dropdownItems}
      />
    ```

2. Add a prop like `splitButtonItems` to `DropdownToggle` which will cause it to wrap its `<button>` in the `<div class="pf-c-dropdown__toggle pf-m-split-button">` internally, and then render any items passed to the prop as children of this div placed before the `<button>`. This is cleaner and requires less redundancy (a disabled prop passed to DropdownToggle could render the right classes on the div and the splitButtonItems), but makes it so that the last child of the `.pf-m-split-button` must always be that `<button>` originally rendered by `DropdownToggle`.

    ```js
    <Dropdown
        onSelect={this.onSelect}
        toggle={(
          <DropdownToggle
            splitButtonItems={[
              <DropdownToggleCheckbox id="example-checkbox-1" />
            ]}
            onToggle={this.onToggle}
          />
        )}
        isOpen={isOpen}
        dropdownItems={dropdownItems}
      />
    ```

Either way I'll need to also add `DropdownToggleCheckbox` or something like it.

@mcoker, @jgiardino, @dgutride or anyone else, what do you guys think? I'm leaning towards option 2 and I've started towards building it that way.

**Comment by redallen** [comment]
Option 2 is more idiomatic as well. I like it!

**Comment by tlabaj** [comment]
I also like option 2.
