### ISSUE TITLE
Add Context Selector component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1293]
New component - https://pf4.patternfly.org/components/ContextSelector/examples/

https://github.com/patternfly/patternfly-next/pull/1288

**Comment by jgiardino** [comment]
There was some discussion in the a11y meeting today related to this component. Here's a recap of some things discussed:

- This component will use the behavior described in this issue: https://github.com/patternfly/patternfly-react/issues/839 (i.e. the panel behaves similar to a popover)
  - #839 is intended to allow consumers to use the Dropdown component and customize what displays in the panel that pops up, when they need something more than just a basic menu. 
  - Having the panel behave like a popover allows us to manage the visibility relative to focus. The panel will trap focus, and isn't hidden until the user explicitly exits it. This will be the default behavior of the Dropdown Panel variation of the dropdown.
- Since for this case we know what the contents of the panel are, we can also include additional keyboard interaction behavior so that a sighted keyboard-only user will have similar experiences for components that look the same (i.e. toggle that displays something with a menu). We might not be able to have complete parity, but maybe at a minimum can:
  - enable the arrow keys to shift focus between menu items
  - have Tab on the last menu item exit the menu
- It might make sense to start off with basic functionality first (e.g. basic popover functionality) and do a round of testing, and incrementally add the arrow key and tab key functionality then test again, in case these updates cause the component to not work at all in one of the screen readers.

**Comment by dlabaj** [comment]
#1526 Fixes this issue.
