### ISSUE TITLE
Nav component prop type declaration file correct?

### ISSUE THREAD

**Issue by eriknelson** [patternfly/patternfly-react#1391]
I'm currently exploring using the patternfly 4 components in a new TypeScript project and came across what seems like an inconsistency in the Nav type declaration (I'm also relatively new to typescript, please forgive me if I'm missing something here).

Looking at the props in the declaration file, the Nav `onSelect` property optionally takes a function with 3 positional parameters: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts#L7

However, the Nav component actually passes an object with the various fields on it to the handler, as seen in the [example](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js#L9).

Is this a case where the type declaration file just needs to be updated, and in general, are these files up to date?

**Comment by rachael-phillips** [comment]
@jschuler do you mind taking a quick look at this one?

**Comment by jschuler** [comment]
Hi @eriknelson thanks for submitting this issue. You are correct, the handler passes back an object with fields. The Nav.d.ts file needs to be updated to reflect that. 
We are also currently in the process or converting existing components over to Typescript fully, so that we don't have to manually maintain those *d.ts files anymore. 
Either way, this needs to be fixed. Thanks!
