### ISSUE TITLE
ListView.InfoItems are not aligned with each other

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly-react#1393]
It would be really nice if the `InfoItem`s would behave more like table columns where they would always be aligned properly. This can already be seen in the official [storybook](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Item%20Count%3A=75&knob-Items%20End=15&knob-Page=1&knob-Page%20Size%20Drop%20Up=true&knob-firstPage=First%20Page&knob-Total%20items=75&knob-of=of&knob-Items%20Start%3A=1&knob-currentPage=Current%20Page&knob-perPage=per%20page&knob-nextPage=Next%20Page&knob-Style=default&knob-Number%20of%20Pages=5&knob-View%20Type%3A=list&knob-lastPage=Last%20Page&knob-previousPage=Previous%20Page&selectedKind=patternfly-react%2FContent%20Views%2FList%20View&selectedStory=List%20of%20expandable%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel):

![storybook](https://user-images.githubusercontent.com/200109/52852929-43540000-311a-11e9-83cf-405b3228edeb.png)

You see how the "8 images" is misaligned in the third column as "11" is wider than "7" or "9".

@tlabaj for PR review

**Comment by martinpitt** [comment]
*bump*

**Comment by kmcfaul** [comment]
@mcoker Is there something in css we could add for padding for this case?

**Comment by mcoker** [comment]
Hmm... the datalist can handle a "grid" type layout to a certain extent, but this is a case where it will be hard to align a group of items in one row with a group in another row. One thing you could do in this case is apply the following, so that the items grow to fill their parent (will change the spacing), but they're all based off of the same `flex-basis` so they will be equal widths (each item is 25%). So as long as you have the same number of items in each of those groups, they should align with one another on different rows.

```
.list-view-pf-additional-info-item {
  flex: 1 1 0;
}
```

Will that work for you?

**Comment by kmcfaul** [comment]
Adding the flex property to that class will space them out evenly, opposed to the more left aligned items.

![Screen Shot 2019-07-26 at 10 19 54 AM](https://user-images.githubusercontent.com/45077788/61958321-17715c00-af8f-11e9-8707-b5017a5584f6.png)

Should this be changed in core or should a separate class be added in core and applied to the items via a flag parameter? @kybaker @mcoker

**Comment by mcoker** [comment]
@kmcfaul since this is pf3, we only want to introduce changes for high priority blocking changes (features, bugs, etc).

@martinpitt would the option above help in your case, or can I help you re-work it so that it does? Or could you potentially consider a table for a layout where columns will align with one another in all rows?

**Comment by kmcfaul** [comment]
@mcoker @kybaker Of the three ListView issues then (#1392, #1393, #1394), are either of the other two besides #1392 slated to change? #1394 I haven't pinged on because it should be able to be done only on the react side, with letting a user has in a null/empty `actions` parameter to keep the spacing div (just without children).

**Comment by rachael-phillips** [comment]
Hi @mcoker and @kybaker I'm following up here. What should @kmcfaul 's next steps be here?

**Comment by kmcfaul** [comment]
Hi @martinpitt. We are not taking on these couple PF3 ListView issues at this time, please refer to the workaround using `flex` for this spacing issue, and contact @mcoker if you have further questions.
