### ISSUE TITLE
PF 4 Table updates even if arrived data haven't changed values

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1399]
In our application, data are periodically reloaded from backend and then re-displayed. But often the data values remains the same.

The content of `tbody` element in DOM is always updated even if data in attribute `rows` stay the same
when I use the Table component.

Let's say we have the following code:
```javascript
import React from "react";
import { Table, TableHeader, TableBody } from "@patternfly/react-table";

const Nodes = ({ nodeList }) => {
  console.log(nodeList);
  return (
    <Table
      aria-label="Cluster nodes" 
      rows={nodeList.map(node => [node.name, node.status])}
      cells={["Name", "Status"]}
    >
      <TableHeader />
      <TableBody />
    </Table>
  );
};

export default Nodes;
```

The console shows that we get the same data:
```
(3) [{…}, {…}, {…}]
0: {name: "node-1", status: "online"}
1: {name: "node-2", status: "online"}
2: {name: "node-3", status: "offline"}
length: 3
__proto__: Array(0)

(3) [{…}, {…}, {…}]
0: {name: "node-1", status: "online"}
1: {name: "node-2", status: "online"}
2: {name: "node-3", status: "offline"}
length: 3
__proto__: Array(0)
```
But the DOM elements inspector indicates that content of tag `tbody` element is updated:
Before data arrives
![dom_inspector_before](https://user-images.githubusercontent.com/16188254/52949239-06874380-337c-11e9-8d85-1a3e856409d0.png)

After data arrives
![dom_inspector_after](https://user-images.githubusercontent.com/16188254/52949286-261e6c00-337c-11e9-938a-c75b53830498.png)

Version of @patternfly/react-table is 1.0.7

**Comment by rachael-phillips** [comment]
This issue will require more investigation from the PF4 team. @karelhala do you happen to know anything about this issue from your work?

**Comment by karelhala** [comment]
This was one of my concerns when I voted not to use `react-tabular` as dependency. The table is not connected directly to redux so it is refreshed everytime data are passed to this component (that is how react works).

We have two otions here:
1) keep as is and force consumers to code components that does not trigger re-renders if data remains the same. There are multiple approaches that can help programmers to identify if data were changed or not.

2) write function that will compare old rows with new ones and do not trigger a re-render. This can be really CPU consuming if programmers pass really complex data or a lot of rows. I would propose not to include this function by default, but rather opt in.

In my opinion first way is cleaner and slightly better because we do not have to use CPU consuming function just to check if any data were changed. But we can be nice to consumers of this package and write such function. Programmers can then import it to render lifecycle on their own.

**Comment by idevat** [comment]
@karelhala I don't understand what you meant by this:

> The table is not connected directly to redux so it is refreshed everytime data are passed to this component (that is how react works).

When I create similar table component (`AnotherTable`), the update does not occur for this component whilst for `Table` it occurs.
```javascript
import React from "react";
import { Table, TableHeader, TableBody } from "@patternfly/react-table";

const AnotherTable = ({ rows }) => (                                            
  <table>                                                                       
    <tbody>                                                                     
      {rows.map((r, i) => (                                                     
        <tr key={i}>                                                            
          {r.map((c, j) => (                                                    
            <td key={j}>{c}</td>                                                
          ))}                                                                   
        </tr>                                                                   
      ))}                                                                       
    </tbody>                                                                    
  </table>                                                                      
);

const Nodes = ({ nodeList }) => {
  console.log(nodeList);
  const rows = nodeList.map(node => [node.name, node.status]);
  return (
    <React.Fragment>
      <AnotherTable rows={rows} />
      <Table
        aria-label="Cluster nodes" 
        rows={rows}
        cells={["Name", "Status"]}
      >
        <TableHeader />
        <TableBody />
      </Table>
    <React.Fragment>
  );
};

export default Nodes;
```
So I guess something special inside `Table` enforces update. React generally doesn't update DOM when render result is the same as previous (i.e. when rows stays the same).

**Comment by karelhala** [comment]
Actually both components re-render, but in the first one you are using static keys and react uses them to understand if such component (row and cell) should or shouldn't be updated [1]. With the second (using PF4 Table) you are creating new array everytime you get `nodeList` from server (notice the `map` function)
```JS
const testArray = ['one'];
testArray === testArray // true
testArray.map(item => item) === testArray // false
```

That being said you can implement [react-component#shouldcomponentupdate](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) and check if `nodeList` changed or not. In the meantime we can change `BodyWrapper` to be actual component and use React's native checker to improve this even further (we are already using keys so that will prevent some re-renders as well) and in future to allow passing custom `shouldcomponentupdate` for row, body and cell - https://github.com/patternfly/patternfly-react/issues/1310.

[1] https://reactjs.org/docs/lists-and-keys.html

**Comment by idevat** [comment]
Ah, I see the point now.

I guess the problem is in a fact that `Table` component accepts rows instead of letting the content render explicitly by a client. Just create stylled wrappers around `tr`, `td` - similar to `DataList`. It would also allow to avoid row objects:

```javascript
{
  title: <div>one - 2</div>,
  props: { title: 'hover title', colSpan: 3 }
},
```
I don't like the workaround with shouldcomponentupdate. I think it is better to use own `table` with appropriate style, in such case.

**Comment by karelhala** [comment]
I agree with you, custom styled elements for table would be better, we had a discussion about this couple months ago https://github.com/patternfly/patternfly-react/issues/402 but reactabular was chosen to be used. It has some features that are really good, like chaining enhancers together without actually add your code to this repository. But as you described because the data are not directly connected to redux the render method is complicated and it can cause re-renders.

**Comment by idevat** [comment]
@karelhala thank you for the explanation and link. Personaly, I agree with your opinion that no such heavyweight component for a table is needed. Especially at the cost of losing control on the client side.

It would be nice if patternfly-react also added the lightweight styled components (wrappers around `table`, `tr`,...) besides current `Table`.
