### ISSUE TITLE
PF4 Empty State Icon: Allow size to be set

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1434]
The Cost Management UI needs to provide an empty state in a table, per Kyle's high fidelity mock below. However, it appears that the empty state icon component does not allow me to set the size?

Also, the empty state icon component is undocumented in the PF4 examples.

This icon appears to be too large and does not match the size shown in Kyle's high fidelity mock.

<img width="646" alt="screen shot 2019-02-22 at 4 27 49 pm" src="https://user-images.githubusercontent.com/17481322/53272576-aec04380-36bf-11e9-8d06-e75c64a19bef.png">

Kyle's Mock:
<img width="1501" alt="screen shot 2019-02-22 at 2 58 34 pm" src="https://user-images.githubusercontent.com/17481322/53267880-867e1800-36b2-11e9-9ede-49b254a61358.png">

**Comment by boaz0** [comment]
@dlabrecq you can pass `size` to `EmptyStateIcon` to change the icon size.
Size can be one of the following: `sm`, `md`, `lg` and `xl`.

**Comment by tlabaj** [comment]
@dlabrecq The Icon size for Empty state is always supposed to be 54px.  That is what it is set to in the core styles.  Can you verify the size of the icon in your workspace?

**Comment by rachael-phillips** [comment]
@dlabrecq thoughts here? :)

**Comment by dlabrecq** [comment]
It is 54px in my workspace, but that still appears much larger than Kyle's mocks.

**Comment by dlabrecq** [comment]
It is 54px in my workspace, but that still appears much larger than Kyle's mocks.

**Comment by rachael-phillips** [comment]
Thanks @dlabrecq ! @tlabaj @mcoker is this an issue we will need to solve for in Core?

**Comment by mcoker** [comment]
@kybaker @mceledonia what do you think here? The icon size is 54px currently. Should the design above be adjusted to use the [existing empty state icon size](https://pf4.patternfly.org/components/EmptyState/examples/), or should we add a modifier to the empty state icon so folks can adjust the size as they see fit?

**Comment by mceledonia** [comment]
Let's stick with our single default size (54px) for now, and also introduce a small size for smaller card layouts? The small size would be 32px. I don't want to introduce too many sizing options here yet because we are planning on offering variations of this layout for success states, etc.. which will have different (larger) icon sizes, so it probably would be best to keep things simple until we see how that pans out.

**Comment by dlabrecq** [comment]
This is still an issue for Cost Management. That is, I was never able to match the icon size shown in Kyle's high fidelity mock.

**Comment by tlabaj** [comment]
@mceledonia has the small size icon been introduced in core?

**Comment by mceledonia** [comment]
@kybaker What size is the icon in your mockup? I am thinking we just keep them all at 54, though we did have that even larger size for the "success" version of the empty state. @dlabrecq I wouldn't worry too much about matching it to Kyle's mocks unless he's got a reason for the change.

**Comment by rachael-phillips** [comment]
@kybaker @mceledonia any update you can provide us here? :)

**Comment by kybaker** [comment]
@dlabrecq @rachael-phillips @mceledonia I created this mockup before the empty state pattern existed in its currect form. It would be best if this icon was consistent with the rest of the empty state patterns. Since this was filed in February we have evolved the empty state to accommodate this layout. I think this issue should be closed.
