### ISSUE TITLE
PF4 Pagination per page menu sticks open

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1562]
The menu used to set the number of items per page does not close properly. The menu opens and closes when using the button. However, when clicking elsewhere in the page, the menu remains open unexpectedly. Users can only close the menu by clicking the button, again.

![chrome-capture (1)](https://user-images.githubusercontent.com/17481322/54235595-f03a5680-44e7-11e9-91df-1b0505924817.gif)

**Comment by rachael-phillips** [comment]
Hi @dlabrecq thanks for posting this! We will take this into the current milestone if we have time.

**Comment by jgiardino** [comment]
Capturing some notes from a slack discussion here about updates needed to address this:

- OptionsMenu is updated so that menu panel is closed when clicking outside the menu
- OptionsMenu is updated to include a prop so that the consumer can decide if it stays open or closes when selecting an option. 
  - The prop should default to close the menu when an option is selected. 
  - All examples can use the default except the example labeled **Options menu - multiple options**. For this example, we should set the prop to keep the menu open when selecting an option.
- Pagination component should not need updates, but please check that it works as expected after updating the OptionsMenu. 

Also, here are some comments from @mcarrano on the use case for when a consumer might want the menu to stay open:

> Yes, it was coded this way to all for selecting multiple options without needing to reopen the menu each time. Sort is a good example where I might want to say sort by Name and sort in descending order. For single option selection, there is probably no need to keep the menu open. That would solve the issue raised with the Items per page selection. I also agree that clicking outside of the menu should close it.
