### ISSUE TITLE
Introduce Victory Charting Brush and Zoom 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#1715]
There is a need for users to be able to zoom in on line charts. I imagine we will leverage Victory charting again for this.... https://formidable.com/open-source/victory/guides/brush-and-zoom/

**Comment by LHinson** [comment]
@rachael-phillips tagging you in order to follow up with team and determine assignee. I'm also curious about any estimates regarding how long this might take and/or any other complexities.

**Comment by rachael-phillips** [comment]
Yes, and that was @jcaianirh 's response, as well. I believe he will still be working on this when he returns from pto.

**Comment by dlabrecq** [comment]
My thought about zoom is that we could add Victory's `allowZoom` prop to our Chart and ChartGroup components, and add `VictoryZoomContainer` for the user. It's possible we can also do something like that for brush (i.e., add the `allowDrag` prop). If the user needs something more advanced, they can still override the `containerComponent` property.

I don't know if the user will need to combine container functionality (i.e., show brush and zoom at the same time), but we could potentially use Victory's `combineContainer()` function to add that for the user as well. Perhaps brush and zoom are mutually exclusive, but other combinations may be valid?

**Comment by jcaianirh** [comment]
@dlabrecq I like that idea. Do we still want to provide the examples in my PR so that we can show how to manually add the zoom component? I actually think we can use createContainer for all of this work and just pass the features selected by the user...I know its documented to be used to combine with multiple features, but it seems to work fine even with a single feature.

**Comment by dlabrecq** [comment]
What I had in mind for the Chart and ChartGroup components, would look more like this:

![Screen Shot 2019-05-30 at 2 21 33 PM](https://user-images.githubusercontent.com/17481322/58654634-5ca64400-82e6-11e9-8d64-39199ee7f50a.png)

We use VictoryZoomContainer as is. And only add it as a default if `allowZoom=true`. (This would allow users to still override containerComponent if necessary.) We would do something similar for Brush. 

I would only consider using `createContainer` if we were combining containers.

**Comment by jcaianirh** [comment]
@dlabrecq Yeah I get what you meant. I think its a good idea. I wonder if we should add this to it:
`const Chart = ({
allowZoom=false, 
zoomProps, 
etc, 
containerComponent=allowZoom ? <VictoryZoomContainer {...zoomProps}/> : undefined
...
`

**Comment by dlabrecq** [comment]
I'm leery of adding more props because it feels cleaner to use containerComponent. I'm also thinking that we will need to document all 10 zoom and 13 brush props.

I'm not opposed to adding allowZoom to provide default functionality. However, I feel that containerComponent should be used for advanced features. That's a more typical Victory use case.
