### ISSUE TITLE
Component : Time Picker 

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#180]
Provide implementation for the [PatternFly Time Picker](http://www.patternfly.org/pattern-library/widgets/#timepicker)

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/time-picker.html

Include story examples demonstrating this features in a mock application scenario

**Comment by mturley** [comment]
This was mentioned today on slack as a need. Not sure what our process is for prioritizing stuff based on community input.

**Comment by dabeng** [comment]
@serenamarie125 @priley86 I managed to make a **[demo](https://rawgit.com/dabeng/patternfly-react/t-p-dist/.out/index.html?selectedKind=Timepicker&selectedStory=Timepicker&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)** for component timepicker. Please review and if it makes sense, I'm glad to commit the according PR :blush:

**Comment by serenamarie125** [comment]
@jgiardino @maryclarke from a design perspective, there are differences as well
1 - AM/PM button versus arrows
2 - if the user edits in the text field, should the drop panel automatically close?  Because right now in both examples, the drop panel remains displayed ... 
3 - should the AM/PM be optional?  Often 24 hour time is displayed

@Rohoover from a visual perspective, there are a bunch of differences:
<img width="474" alt="screen shot 2018-02-14 at 8 52 13 am" src="https://user-images.githubusercontent.com/12504403/36207580-686365ec-1164-11e8-9fb0-268bd3634eaf.png">
<img width="372" alt="screen shot 2018-02-14 at 8 52 08 am" src="https://user-images.githubusercontent.com/12504403/36207581-68764ab8-1164-11e8-9e6c-e476ebd8c3e6.png">

font, caret

IMO, I think we need to determine what the design should be and then get both implementations to reflect them :)

**Comment by Rohoover** [comment]
@serenamarie125 @maryclarke @jgiardino 

So I checked out the [pf documentation](http://www.patternfly.org/pattern-library/widgets/#timepicker) as well as what is available on the [rawgit site](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/time-picker.html) the top example in Serena's post seems to be the correct design as it's reflected in both areas.

As a personal note I prefer the carrot approach to changing PM/AM but that's obviously a separate issue.

Sorry for the delayed response, I didn't have the correct notifications turned on for PF.

**Comment by maryclarke** [comment]
I personally like the AM/PM with carrots as well rather than a toggle button.  I do believe that the AM/PM should be optional so that if for localization the time picker needs to reflect 24 hour time, there is no confusion.

For your second point @serenamarie125, I think that at the very least, if the dropdown stays open, it should reflect the time that the user is typing, but I am ok if it does stay open.

**Comment by jgiardino** [comment]
@Rohoover I think the pf documentation and rawgit site are pulling the same example, which is why they match.

Regarding visual styling, I wanted to point out that this component is based on a third-party component. In general when we are implementing the JS version of a PF component based on a third-party component, I think we should question whether the visual styling shown in the core patternfly example is really the example we want to follow since it's heavily based on the third-party component. For example, those carets aren't the patternfly carets, and I'm sure the fonts would be slightly different too if we implemented this ourselves. 

Without having an actual PF mockup, it's hard for me to say what's right and what's wrong. 

@dabeng Is your demo based on another third-party component, or did you implement this completely in pf-react? I'm curious how much control you have over the elements that display in the dropdown menu.

I'm open to ideas on this one, but this is what I would suggest the next steps to be if they're easy to do:

-  make the updates that @Rohoover and @maryclarke suggest, but use `fa-angle-down` and `fa-angle-up` for the carets
- remove any css we don't need (specifically styles that affect text styling), and see what happens when we rely more on PF styles that already exist

Then I think we should review again and see how it compares to similar components like the Dropdown Button. 

@serenamarie125 regarding this:
> 2 - if the user edits in the text field, should the drop panel automatically close? Because right now in both examples, the drop panel remains displayed ...

I think that depends on whether we want to make the menu keyboard accessible, which it isn't currently. If I'm a keyboard only user, and I place focus on the field, if the dropdown displays, I would expect to be able to shift focus to the dropdown. If we don't want to spend the resources to make the dropdown keyboard accessible, then I would suggest we keep it hidden. I think this would be fine, assuming that a keyboard user would probably just type in the time rather than use the dropdown anyway. I'm totally open to other thoughts on this.

**Comment by Rohoover** [comment]
@jgiardino 

Ah ok. I didn't realize that what was being used wasn't from PF in terms of iconography etc. I assumed since it was in the documentation that it had previously been vetted.

YES - lets use those PF icons.

To elaborate on my preference of a caret for AM/PM. Currently we're using a button that is toggling am/pm. That seems like a misappropriation of a button. Just my $0.02.

**Comment by dabeng** [comment]
Hi @Rohoover @serenamarie125 , could you send a link to show the correct design ?

**Comment by dabeng** [comment]
@jgiardino I developed this react version of datetimepicker based on https://github.com/YouCanBookMe/react-datetime

**Comment by dabeng** [comment]
@jgiardino currently, react-datetime doesn't provide API to customize the layout of time, so if we want to get the same style of drop panel we need to send PR to upstream repo.
