### ISSUE TITLE
Add option to use <a> element on tabs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1805]
https://github.com/patternfly/patternfly-next/pull/1722/files

> Note: `<a>` should be used when there is a URL associated with the tab, and should only be used when `.pf-c-tabs` is used with `<nav>`.

**Comment by mturley** [comment]
@mcoker @dgutride @dlabaj do you guys think it would be more appropriate here to:
1. add a `component` prop to `Tab` which defaults to `button` and can be set to `a` explicitly, but we leave it up to the user to know that they should use this when they want to use `href` and use it in a `nav`
2. add an `href` prop to `Tab` which, when included, causes it to render an `<a>` instead of a `<button>`, but we leave it up to the user to use `href` in their tabs when using them in a `nav`
3. pass props down from `TabsWithNav` into the `Tab` itself to make it aware that it is a child of a `<nav>` and render an `<a>` automatically in this case.

I like #3 the best personally, since it doesn't require the user to remember anything and means tabs will strictly always be `<a>` when they are inside a `<nav>`. But it's less flexible; do we care about making it possible for a user to use `<button>` inside `<nav>` and override this rule?

**Comment by mcoker** [comment]
@jgiardino what do you think about @mturley's question?

**Comment by jgiardino** [comment]
I like option # 2 of all of them.

I don't think we should be too strict on the `<nav>`>`<a>` relationship. I'd prefer to leave that up to the consumer.

But it does make sense that if the user is defining an `href` that it would/should always be an `<a>`.

**Comment by mturley** [comment]
@jgiardino what if instead we did option # 3 with the ability for the user to specify an alternate `component` prop to the `Tab` component? That's what I started building and I like it. By default tabs descended from `<nav>` will be an `<a>` with or without an `href`, but they can pass `<Tab component="button`>` to override it.`

I have a PR ready for that if you want to see it. If you think it should be strictly driven by `href` i'm fine with that too.

**Comment by jgiardino** [comment]
My concern with that method is that it will lead to cases where `<a>` elements are being used when they shouldn't be. I also have an uneasy feeling about a child element type being changed depending on a prop value on the parent component.

**Comment by mturley** [comment]
Fair point. Ok! thanks @jgiardino

**Comment by mturley** [comment]
https://github.com/patternfly/patternfly-react/pull/1828
