### ISSUE TITLE
Broken chart examples

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1887]
I recently discovered that the React examples have been deleted, replaced with an .md file via https://github.com/patternfly/patternfly-react/pull/1656. :(

Unfortunately, the CSS that was written for the chart examples has been lost. The chart examples look horrible now.

It's difficult not being able to write React based examples using React. However, can we please have a way to include CSS with the examples?

**Comment by dlabrecq** [comment]
Tooltips don't overflow:
![Screen Shot 2019-04-29 at 5 41 20 PM](https://user-images.githubusercontent.com/17481322/56928839-086d3180-6aa6-11e9-878c-cc50121d7a21.png)

Stack Chart bars are off:
![Screen Shot 2019-04-29 at 5 39 14 PM](https://user-images.githubusercontent.com/17481322/56928720-bb895b00-6aa5-11e9-8f6f-380f303b955f.png)

Pie chart legend should appear on the right:
![Screen Shot 2019-04-29 at 5 39 36 PM](https://user-images.githubusercontent.com/17481322/56928762-d22fb200-6aa5-11e9-9ec5-60f5ae3f6209.png)

Donut chart is huge:
![Screen Shot 2019-04-29 at 5 40 22 PM](https://user-images.githubusercontent.com/17481322/56928785-e4a9eb80-6aa5-11e9-8288-a5b3f43f1141.png)

Bar chart is ridiculously enormous:
![Screen Shot 2019-04-29 at 5 40 43 PM](https://user-images.githubusercontent.com/17481322/56928808-f1c6da80-6aa5-11e9-9144-16bbb32ca73d.png)

**Comment by redallen** [comment]
A few notes on this...
1. You are still writing React-based examples using React. These markdown files actually give you more flexibility. Now since the docs use [MDX](https://mdxjs.com/) instead of MD, your file gets converted to a React component and you can do everything you could do in a React component in your MDX.
1. Many parts of chart examples had problems because of hardcoded widths/heights for the react-live container which changed size when I converted them to MD. I did my best to convert them, but if I recall correctly I had to add lots of `style={{}}` tags, since at first the MD couldn't have styles included. I documented the axes problem in #1673 .
1. [This PR](https://github.com/patternfly/patternfly-react/pull/1889) adds the old CSS to the chart pages, but those old `style={{}}` tags still need to be cleaned up and classNames potentially changed. This is in my backlog, but you are probably the person that best understand the Victory styles that need to be applied to which `<div>` containers. It would be awesome if you could also document it in the MDX so consumers can copy/paste the styles and have nice looking charts!

**Comment by dlabrecq** [comment]
This has been fixed with my lastest PR.

https://github.com/patternfly/patternfly-react/pull/1964
