### ISSUE TITLE
TitleSize: Type not available

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1892]
The TitleSize does not make '2xl' available. I'd like to use the following with Title component:

`<Title size={TitleSize.2xl}>`

Although, I can do this:

`<Title size={TitleSize['2xl']}>`

**Comment by rachael-phillips** [comment]
Hi Dan, thanks for filing this! Is this blocking implementation? Also what priority is this issue to you?

**Comment by dlabrecq** [comment]
Not blocking me. I'm using the workaround described above, but prefer not to do that.

**Comment by jenny-s51** [comment]
@dlabrecq Titani mentioned that there is some discussion about what the best name for the vars would be.

Here are some of the suggestions she listed:

1. Size[‘2xl’] (what we already have)
2. Size.xl2
3. Size.xxl (and also xxxl, xxxxl ?)
4. Size._2xl (folks do not like this due to common use of_ for private variables)
5. Size.$2xl
6. Size.TwoXl

@dlabrecq Please comment here what you think would be most appropriate.

Thank you!

**Comment by dlabrecq** [comment]
I'm just looking to add TitleSize.2xl, not asking to rename all the sizes. 

I don't know why we have TitleSize['2xl'] as a string, but probably not the best choice. That is,  considering we already support TitleSize.sm, TitleSize.xl, etc.

Why don't folks like Size.2xl -- exactly how does that interfere with private vars? I'd rather add TitleSize.2xl than rename all the sizes and introduce a breaking change.

**Comment by jenny-s51** [comment]
@dlabrecq Sorry for not clarifying -- JavaScript prohibits variable names from starting with numbers, which is why 2xl must be accessed as a string: TitleSize['2xl']. 

@tlabaj marked this as a breaking change issue because there isn't a quick fix that would allow for TitleSize.2xl without renaming the sizes.

**Comment by dlabrecq** [comment]
Makes sense now. Thanks for clarifying

**Comment by jenny-s51** [comment]
closed via #2129
