### ISSUE TITLE
Donut chart problems

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#1925]
Currently, the donut chart does not meet the PF design criteria. There are a few issues that need to be addressed:

1. The 'donut hole' (innerRadius) is a static value which will cause issues if users pass in width/height values to the ChartDonut component. Need to figure out the best way to calculate this value so that setting width and height don't break the chart. See this example of a donut chart implementation: https://medium.com/@sschannak/creating-a-progress-chart-with-victorypie-in-react-20514c92775

2. Setting width or height on the DonutChart can cause some really strange behavior. For example, setting it to a small value like`10` can cause it to scale up to a huge size within the parent. This might just be an issue with Victory and svg scaling, but I feel like setting a width or height shouldn't cause strange, unwanted behavior. The above implementation with the width and height props abstracted might help with this.

3. Tooltips are not PF design

4. There should be a prop to easily set the label shown in the middle of the donut. As it is now, user has to create their own svg and position the text themselves. This makes the component difficult to use as the design intends.

**Comment by dgutride** [comment]
@dlabrecq  - please take a look at this and let me know the level of effort

**Comment by janwright73** [comment]
@dlabrecq - any chance you can jump on this and help Jon get these issues resolved?

**Comment by dlabrecq** [comment]
Regarding #4, creating a generic label is difficult for the donut chart to do. Victory doesn't have its donut chart, which is why the label is created via compilation. 

Note that this was a first pass at a donut chart. (We haven't made any changes since November and still don't have any pf-core variables for the theme.) There are known issues trying to use the Victory pie chart in this way and don't have a good answer for this.

Regarding #3 et al, there is still some basic architecture that should be addressed first, IMO. For example, theme properties, color variables, etc. That would address tooltips for all charts, for example.

FYI, Cost management overrode the styles for tooltips to show the PF4 white text on black background -- not difficult.

**Comment by TheRealJon** [comment]
@dlabrecq

> Regarding #4, creating a generic label is difficult for the donut chart to do. Victory doesn't have its own donut chart, which is why the label is created via compilation as shown in the example above.

Could we do something like what we are doing in the example, just wrap it into the component? The label is part of the design, so I think we probably need to provide a simple API for it.

> Regarding #3 et al, there is still some basic architecture that should be addressed first, IMO. For example, theme properties, color variables, etc. That would address tooltips for all charts, for example.

I agree, but those basic architecture changes will take time. Meanwhile, the donut chart doesn't meet the design specs. I think it would be worth fixing what we have and iterating on it to fix the underlying architecture. Also, agree that it's easy to override the tooltip styling, but just wanted to make sure the issue was documented.

> Regarding #2, our examples set height and width on a div container only. Not sure when a 10 pixel chart would be used; however, users are free to add height and width to the underlying pie chart. We're simply passing through properties to the Victory pie chart, similar to the example above.

So we set the size of the chart by setting the size of the wrapper, right? Can't we just make that a part of our API instead of leaving it up to the user to wrap the chart in a div? Changing the size of the VictoryPie chart itself effects the inner to outer radius ratio, which means that the 'thickness' of the donut will change. We would need to account for this by calculating an innerRadius value based on the provided width/height props. Instead, if we allow the user to provide a `size` prop which is applied to a wrapper div, the svg should just scale with the wrapper. Something like this:

```jsx
const ChartDonut = ({
  size,
  innerRadius = DEFAULT_INNER_RADIUS,
  labelComponent = <ChartTooltip/>,
  padAngle = DEFAULT_PAD_ANGLE,
  ...rest
}) => {
  return <div style={{width: `${size}px`, height: `${size}px`}}>
    <VictoryPie
      innerRadius={DEFAULT_INNER_RADIUS} 
      labelComponent={labelComponent} 
      padAngle={DEFAULT_PAD_ANGLE} 
      theme={ChartTheme.default} 
      {...rest}
    />
  </div>
};
```

> Not sure when a 10 pixel chart would be used;

My point is not that a 10px chart should be a huge concern, but that setting the height and width directly on the ChartDonut component can result in strange behavior. I think the main problem here is that we are using a static value of 88 for the innerRadius, which means that the diameter of the center cutout is 176. If you set the height/width to any value less than that, it will cause unexpected behavior. If we want to use a static inner radius, we will need to use a static width and height on the VictoryPie as well. Then we can use the wrapper to resize the chart, as above.

> That said, there are limitations using a Victory pie chart in this way and don't have a better answer for this. The latest designs now include thresholds, which introduces other challenges.

I think that where we find limitations to Victory, we will need to fill in the gaps. Otherwise, react-charts will be very cumbersome to use.

> Note that this version was a first pass at a donut chart. We haven't made any further changes since the initial charts we created back in November and still don't have any chart variables in pf-core for the theme.

Understood. Take all of this with a grain of salt. I know that this isn't a final release or anything, just making suggestions for our next iteration.

**Comment by dlabrecq** [comment]
I agree that the innerRadius should be some percentage of its container. However, it's not clear if wrapping Victory pie is the best way to solve it. Perhaps providing a donut component isn't the way to go here, but an example? Will investigate.

In the mean time, you should be able to add you're own label per the example above, while we try other solutions?

If you also want to apply tooltip styles, try these variables from @patternfly/react-tokens:

```
  <ChartTooltip
    flyoutStyle={{
      fill: c_background_image_BackgroundColor.value,
      strokeWidth: 0,
    }}
    pointerWidth={20}
    style={{
      fill: global_Color_light_200.value,
      padding: 18,
    }}
  />
```

Don't really want to hard code those particular values in our theme, but will try to do something. Ideally, Patternfly core would create some chart variables.

**Comment by dlabrecq** [comment]
After some investigation, issue #1 & #2 turned out to be a misunderstanding of how the SVG viewport works.

"Because Victory renders responsive containers, the width and height props do not determine the width and height of the chart in number of pixels, but instead define an aspect ratio for the chart. The exact number of pixels will depend on the size of the container the chart is rendered into." -- Victory

Users can set height and width of a chart, but it's typically done using a container. If users want to use height and width in a more traditional way, responsive containers can be disabled.

Per my discussion with @TheRealJon, we don't want to wrap/hide that functionality with a div because users expect an SVG to be output.

That said, I'll plan to add this documentation to the height and width properties. Although, Gatsby still needs some work to display them properly.

**Comment by dlabrecq** [comment]
See https://github.com/patternfly/patternfly-react/pull/1964
