### ISSUE TITLE
PF4: Investigate how to handle props dynamic tags in TypeScript

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2006]
Currently we are casting the tags to "any" as a work around.
In the code below we cast the dynamic tag to any ` const Component: any = component;`
From initial investigation it seems that the issue because we extend HTMLElement. 

`export enum TextVariants {
  h1 = 'h1',
  h2 = 'h2',
  h3 = 'h3',
  h4 = 'h4',
  h5 = 'h5',
  h6 = 'h6',
  p = 'p',
  a = 'a',
  small = 'small',
  blockquote ='blockquote',
  pre ='pre'
}

export interface TextProps extends React.HTMLProps<HTMLElement> {
  /** The text component */
  component?: TextVariants;
  /** Content rendered within the Text */
  children?: React.ReactNode;
  /** Additional classes added to the Text */
  className?: string;
}

export const Text: React.FunctionComponent<TextProps> = ({
  children = null,
  className = '',
  component = TextVariants.p,
  ...props
}) => {
  const Component: any = component;

  return (
    <Component {...props} data-pf-content className={css(className)}>
      {children}
    </Component>
  );`

**Comment by redallen** [comment]
We have to cast this because in the JSX we are returning `<Component>`, which is actually a call to `React.CreateElement(Component, ...)`, so we need to satisfy the types for that. However, this isn't the reason the tags are rendering funny in the jest tests. TS Components that don't even use this pattern still get rendered as `<Component>` whereas if they're JS it's `<AlertActionLink>` or whatever.

**Comment by redallen** [comment]
I investigated a little further, and it's more complicated than just the types for `React.CreateElement`. I think we have to declare a namespace for our custom elements. See the Typescript JSX docs: https://www.typescriptlang.org/docs/handbook/jsx.html
