### ISSUE TITLE
Alert has improper defaults

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-react#2030]
As a developer, I should be able to just say:
```javascript
<Alert>My message to the user.</Alert>
```
Everything should have a reasonable default and I should get what I expect, which is an info message with the text I passed in.  But this code won't even transpile in TypeScript because I didn't specify variant and title.  I would expect variant to default to "info" and I didn't want a title in the first place.  But I soldier on and do this:
```javascript
<Alert
   title=''
   variant='info'
>
   My message to the user.
</Alert>
```
Now I can at least transpile my code, but it displays something I didn't want.  It displays a hard-coded, unlocalized string for the title.  The title says, "Info alert:".  I finally figure out that there is this thing called a "variantLabel".  I don't see why anyone would want that, but ok.  I notice that there is a similar hard-coded, unlocalized default for "aria-label".   So now to get the simple message to my user I have to do this:
```javascript
<Alert
   title=''
   variant='info'
   variantLabel=''
   aria-label=''
>
My message to the user.
</Alert>
```

I propose, the following changes:
**title** should not be required
**variant** should default to 'info'
If we really need **variantLabel** and **aria-label**, they should default to empty string.  

But really, if I wanted a variantLabel, I would just add it to the title myself.

**Comment by tlabaj** [comment]
@jgiardino Thoughts on this one.

**Comment by jgiardino** [comment]
For some of our components to meet WCAG 2.1 AA compliance, we need additional text strings defined, either as `aria-label` or screen-reader-only text. Instead of making these props required, we have opted to provide default non-localized values for these props. Our thinking behind this approach is that these strings are a fallback for consumers who might not be aware of accessibility, and for consumers who are aware, they can provide localized strings. And the default string would serve as a recommendation. 

My recommendation would be to either leave the non-localized strings, or provide localized strings for the props `aria-label` and `variantLabel`. But in the example you share, where they are set to empty strings, these components would not be accessible to screen reader users. 

The other react devs should weigh in on your other suggestions, since I don't have strong opinions on those, but here are my comments/questions anyway... 😉 

It sounds reasonable to have a default variant. If so, we would probably want to do this for all components, like Button? Some of these might require arbitrary decisions on what the most likely variant should be.

Since the minimal display of an alert is with just the title (like the example below), if `title` is not defined, then is your expectation that there would be some underlying logic to take the contents of `<Alert>` and display them as the title if the `title` prop is not defined?

![image](https://user-images.githubusercontent.com/21063328/58025350-3e6c6700-7ae2-11e9-93ec-94ef1a85c1d5.png)

**Comment by ssilvert** [comment]
I'm not well versed in accessibility compliance, but it seems to me that something that just says, "Info alert" is not very helpful to anyone.

You could make the logic for aria-label be that if unspecified, it defaults to the title.  If there is no title then try to use the body text.  It would be an error if you provided no title and no body.

variantLabel doesn't seem to serve any real purpose at all.  Again, if I wanted something prefixed to my title, I would just add it myself.

Non-localized text should never be displayed to the user unless his translation is unavailable.  I suggest that if you are going to have text defaults anywhere, then you should make them localizable and provide the ability to use translation bundles.

**Comment by jgiardino** [comment]
> I'm not well versed in accessibility compliance, but it seems to me that something that just says, "Info alert" is not very helpful to anyone.

> variantLabel doesn't seem to serve any real purpose at all. Again, if I wanted something prefixed to my title, I would just add it myself.

These are text strings that are not visible on the screen but are available to assistive technologies like screen readers. In most cases, strings like these are used as alternates for icons where the icons are meaningful and not decorative. In this case, the icons communicate the type of alert. And therefore, without these text strings, these Alerts would not have an equivalent experience for screen reader users.  

> Non-localized text should never be displayed to the user unless his translation is unavailable. I suggest that if you are going to have text defaults anywhere, then you should make them localizable and provide the ability to use translation bundles.

My expectation was that consumers would be able to provide localized values for these props. But maybe there's a better way of handling this? or at least a better way of communicating this to consumers? Any insights on this are appreciated 😄

When you were looking for information about the Alert component, were you looking at 
https://patternfly-react.surge.sh/patternfly-4/components/alert/
or
https://www.patternfly.org/v4/documentation/react/components/alert/
?

**Comment by ssilvert** [comment]
That makes sense for **aria-label** if it represents the icon.  I still should be localizable though.
**variantLabel** does show on the screen.  It's just a prefix for the title.  IMO, variantLabel should be removed from the component.

Right now, consumers are unable to localize this text.  It is hard-coded with no way to replace it.  Right now for me to localize your React components I would have to go through every component I use and replace the defaults like I show like I show above.  But I'm not sure that is doable for all components.

There are some i18n/l10n packages that take care of some of the infrastructure for you.  It's worth looking into.

**Comment by ssilvert** [comment]
> 
> It sounds reasonable to have a default variant. If so, we would probably want to do this for all components, like Button? Some of these might require arbitrary decisions on what the most likely variant should be.
> 
> Since the minimal display of an alert is with just the title (like the example below), if `title` is not defined, then is your expectation that there would be some underlying logic to take the contents of `<Alert>` and display them as the title if the `title` prop is not defined?
> 
> ![image](https://user-images.githubusercontent.com/21063328/58025350-3e6c6700-7ae2-11e9-93ec-94ef1a85c1d5.png)
The minimal display of an alert should be the message content with no title at all.   Title should be optional and should be empty by default.  Often times, we just want to display a message to the user and there is no need to dress it up with a title.  Plus the title takes up screen real estate.

variantLabel serves no purpose at all.  It should be removed.

And back to my original point, everything should have reasonable defaults so that the simple case just works without having to figure out all the parameters that I need to set to empty string.  Please look at my first post.

Also, please reopen this as #2093 does not address the problems with the Alert component itself.

**Comment by jgiardino** [comment]
There are several issues raised in this issue. I’m attempting to recap them below, but please let me know if I missed something:

1. **minimal display** - This suggestion would require a change to both our design pattern and also to core. An issue would first need to be raised in the patternfly-next repo before we could proceed with it here. You could also reach out to the designers on slack to ask if this design was already considered or not before you open an issue in patternfly-next. You might have a use case that they did not consider, or they might have reasons why they decided against that approach, so a discussion there might be helpful.
2. **variantLabel** - This prop allows you to define the text string alternative for the icon that indicates type of alert. This is required for screen reader accessibility, which is one of our initiatives with PF4. You are not required to specify a value for this, but we do provide a default string in English. This prop is for consumers who are providing localized text strings. Hopefully, the concerns you have with this will be resolved with #2093.
3. **Everything should have a reasonable default** - Yes, this should be addressed. I created #2154 to capture that update.

**Comment by ssilvert** [comment]
Hi @jgiardino,

1. **minimal display** - I don't see where this is actually defined by patternfly-next.  The example does put "Info alert:" as part of the screen reader definition and it also uses it as part of the title.  But that does not mean this is a standard.  It's just an example.

It looks like what is needed is to separate the screen reader part from the title text displayed on the screen.  But that would be logic in patternfly-react and not necessarily part of patternfly-next, right?

2. **variantLabel** does not just define the text string alternative for the icon.  It defines a prefix for the title.  So by default, your title will say something like, "Info alert:".  This is obviously wrong.  If I wanted some text in my title as a prefix I would supply it myself.   

If I were just using patternfly-next by itself, I would be free to code the HTML any way I want.  But with patternfly-react, it is automatically adding incorrect HTML that I can't get rid of without specifying an empty **variantLabel**.  The solution is to get rid of **variantLabel** altogether, or at least stop displaying it as a prefix to the title.

3.  #2154 only addresses the **variant** property.   Everything should have a reasonable default.

As a developer, I should be able to just say:
```javascript
<Alert>My message to the user.</Alert>
```
Then it should just display my message to the user with no title and a default variant of 'info'.

**Comment by jgiardino** [comment]
I'm sorry for the confusion. Issue # 1 in my previous comment was in response to this:

> The minimal display of an alert should be the message content with no title at all. Title should be optional and should be empty by default. Often times, we just want to display a message to the user and there is no need to dress it up with a title. Plus the title takes up screen real estate.

My comment on this issue is that the implementation in core does not support an Alert where a title is not displayed. If a title is not provided, the alert is rendered with a blank space as shown below. Since react only implements what's provided by core, then you would need to open this issue in the patternfly-next repo and work with the designers on your use case.

![image](https://user-images.githubusercontent.com/21063328/58915182-7254a880-86ee-11e9-92f2-297ae5fbbb70.png)

> If I were just using patternfly-next by itself, I would be free to code the HTML any way I want. But with patternfly-react, it is automatically adding incorrect HTML that I can't get rid of without specifying an empty variantLabel. The solution is to get rid of variantLabel altogether, or at least stop displaying it as a prefix to the title.

I'm not sure what you're referring to as "incorrect html" in the example below. 

`<h4 class="pf-c-alert__title"><span class="pf-u-screen-reader">Info alert:</span>Info alert title</h4>`

The text inside the span tag is providing a text alternative for the icon. This text is not visible on the screen, but announced as part of the alert title by screen readers. Without this text, screen reader users do not have the same information that we provide to sighted users, which is why it is included. I'm not sure how we could implement your suggestion for this in a way that aligns with our goal to provide components that are accessible (speaking generally here, since this isn't the only case were we provide default text strings to support screen reader accessibility). If we don't provide default strings and we don't make these props required, then I would expect screen reader accessibility of applications using PF4 to suffer, and I am not in favor of making changes that will result in PF4 components being less accessible.

**Comment by ssilvert** [comment]
> This text is not visible on the screen, but announced as part of the alert title by screen readers.

Now I see where we have our wires crossed.  In 3.16.10, the text was indeed visible on the screen.

```html
<h4 class="pf-c-alert__title"><span class="pf-u-screen-reader">Success alert:</span></h4>
```
![Alert](https://user-images.githubusercontent.com/507202/58918384-11ca6900-86f8-11e9-82a7-49ed869dc5c0.png)

Now it is "fixed", except that it shows a blank line for the title, which is obviously wrong. 

I don't see where in core it says that a title is required.  Is that really part of the specification?

**Comment by jgiardino** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/626dd453-b50e-4ee9-9dce-86d306043c85-fe7ba5ad-9c01-4dac-b094-998c3f204a3b-v1.png?transparent=1&palette=1&width=123)

I was not aware of that bug. 

> I don't see where in core it says that a title is required. Is that really part of the specification?

The design documentation is available here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications
It doesn't explicity state title as required, but it does mark which items are optional.

As I mentioned above, we can't update react without updating core to address the issue you mention (i.e. it shows a blank line).  I honestly am not sure if core would get updated to support a design or use case that doesn't align with the design documentation. It's a valid question to raise, but that needs to be raised with the designers and core developers. So either an issue in patternfly-next or a chat on Slack is where I suggest bringing this up.

**Comment by ssilvert** [comment]
So a close look at the documentation suggests that core expects most messages to be "title only".  I can live with that.

So then the simple case becomes:
```html
<Alert title="my message to user"/>
```

As long as that use case is supported I think it's fine.
