### ISSUE TITLE
ClipboardCopy - display inline

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2044]
Currently, the ClipboardCopy react component container is `display: block`. It would be nice to be able to drive this via javascript. Could we add it as a feature so users can specify to display it as inline-block? This would be helpful for times where we don't want the component to expand the full width of its container.

**Comment by mcoker** [comment]
cc @mcarrano wdyt? Offering an inline variation that looks something like this

<img width="1021" alt="Screen Shot 2019-05-20 at 2 40 34 PM" src="https://user-images.githubusercontent.com/35148959/58047229-4392db80-7b0d-11e9-8af2-05433eedcb58.png">

**Comment by mcarrano** [comment]
Seems useful. Would this also require a new variant on the Core side @mcoker ?

**Comment by mcoker** [comment]
@mcarrano I'm not sure. With our current implementation, I don't think it's as simple as defining an inline variation, since the text in the copy field is the `value` attr of a `input[type="text"]`, and the width of the text input will not match amount of text in the `value` attr.

Seems like if we want to keep the current way this component is marked up, we could:

* offer different sized widths like `pf-m-[sm,md,lg,xl]` that a user can use to define the width of the component. 
* have javascript determine the number of characters in the value attribute and update the `width` or `size` of the text input.
* refactor the component to use a `<span contenteditable>` instead of `input` (similar to how we use `contenteditable` on the `.pf-c-clipboard-copy__expandable-content` element).

What do you think @seanforyou23? How did you end up making this work in syndesis?

**Comment by seanforyou23** [comment]
In Syndesis I used a media query to set the display property at given breakpoint. It works ok but is out of line with how we recommend users customize styling in other components (via js props or css variables).

Using JS to detect number of characters isn't great because the quality of the solution can be influence by other styling properties line font-family, letter-spacing, etc.

Seems like the first option could be the easiest, but the last option of using a span with contenteditable could allow for the control to expand as much as necessary to fit the content? This would really be useful.

Now that I look further, I don't think the `maxWidth` property is having any effect on how the component renders anyway. Is this a bug? Maybe this makes a nice case for making one of the above suggestions.

**Comment by mcarrano** [comment]
@seanforyou23 @mcoker So sounds like we should open a core issue for this to address first?

**Comment by mcoker** [comment]
@mcarrano https://github.com/patternfly/patternfly-next/issues/1845

@seanforyou23 do you know if we could change the input in this component to a span without introducing a breaking change in the react component? I think we can do it in core since the input has no specific styling in this component. We can simply introduce a new element for the span and the input should still work fine. I would want to build it first to make sure though.

**Comment by seanforyou23** [comment]
@mcoker I don't see why this would be a breaking change. If users can still type into the "input" then `text-input-${id}` as an id format still makes sense. The usage of TextInput isn't configurable so I think it would be a transparent change for users, except for the slim case where users have further styled the component using descendent selectors and keying off of the input element itself - not from a JS perspective though. Needs the styling changes in place to happen of course, but yea seems possible to introduce this without breaking backward compatibility.

**Comment by mcarrano** [comment]
Is this something we still intend to do? If so, we should get it on the roadmap. I don't believe there are any design dependencies. @LHinson @rachael-phillips FYI

**Comment by tlabaj** [comment]
on hold. waiting for core implementation

**Comment by ssbarnea** [comment]
I think we should reopen this and find a way to decouple the cliboardcopy from the heavy input UI. The https://github.com/patternfly/patternfly-design/issues/956 ticket explains why the current implementation is limiting the usability of this feature, especially in places where the space is tight and where you do not need or want to display the text that will be copied to the clipboard.
