### ISSUE TITLE
Inconsistent chart legends

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#2183]
@dlabrecq @mcarrano @rachael-phillips @jgiardino 

After charts were released, I realized that donut utilization with thresholds is the only legend with text including "[variable name] - [data value]" (i.e. storage capacity - 25%). I believe we had to add the data value in order for this chart to be accessible. Wondering if we can add that text to all legends so they are consistent, before our next release? Also if we can change the "-" to a ":". So "Storage capacity: 25%" or "Dogs: 5" etc.

**Comment by dlabrecq** [comment]
In order for the charts to be accessible, we need to add a title and description to the chart. Changing the legend text doesn't make it accessible because it's all an SVG.

IMO, this could just be added to the chart updates described here.
https://github.com/patternfly/patternfly-react/issues/1692

**Comment by mcarrano** [comment]
I'm fine to see these issues combined. @rachael-phillips is this work anywhere on our roadmap?

**Comment by dlabrecq** [comment]
FYI, This is the a11y issue to add title and description.
https://github.com/patternfly/patternfly-react/issues/1498

**Comment by jgiardino** [comment]
Thanks for catching this, @gdoyle1! From a design perspective, I think it's a great idea to include numeric values in the legend. If we do decide to recommend this from a design perspective, I'm not sure how much would be built in to the chart components vs just represented as best practice in our examples.

Re: @dlabrecq's point, I had created https://github.com/patternfly/patternfly-react/issues/1498 to make updates to our chart examples so that they are screen reader accessible. But I see this update as more of a benefit for these users:
- low vision users that might not be using a screen reader - they might have difficulty associating colors in the legend with colors in the chart. The argument could be made that they can get this info on hover, but they might also be keyboard-only users...
- keyboard-only sighted users - the numeric values are available on hover, but not on focus. I think this was one of the main reasons we had decided to add the numbers to the chart legend for donut utilization with thresholds.

**Comment by rachael-phillips** [comment]
These changes still need to be slated on the roadmap. @gdoyle1 @mcarrano do you mind telling me a bit more about what impact you think this is for charting? Also, is this something that needs to be fixed in Core or React?

**Comment by mcarrano** [comment]
I don't believe there is any Core impact here, but @dlabrecq tell me if I'm wrong. User impact concerns only accessibility as @jgiardino has outlined above. I guess there is also now a consistency issue as donut charts have implemented this and other charts have not.

**Comment by dlabrecq** [comment]
There is no core impact, they're just examples. Although, I agree they should represent the design as best practice.

**Comment by gdoyle1** [comment]
I updated the design examples with this only for charts that have mutually exclusive variables i.e. donut charts and pie charts. @mcarrano @dlabrecq Should we just get this added to pies and donuts in the react examples? Format would be "Storage capacity: 25%" or "Dogs: 5" etc.

**Comment by dlabrecq** [comment]
I believe the react repos are currently locked down for testing. Unless this is a critical change, we should wait to update the examples after the Albatross release.

**Comment by dlabrecq** [comment]
Updated the donut and pie legends as part of PR https://github.com/patternfly/patternfly-react/pull/2271
