### ISSUE TITLE
Alert component shouldn't wrap children into a paragraph tag

### ISSUE THREAD

**Issue by jhadvig** [patternfly/patternfly-react#2283]
When Alert component children contain any tag used for it's formatting  (eg. `ul`, `div`, ...) a warning in the browser console will be shown:

<img width="788" alt="Screen Shot 2019-06-17 at 11 40 09" src="https://user-images.githubusercontent.com/1668218/59616620-17c33f80-9125-11e9-9abc-3be1f228ddb4.png">
<img width="789" alt="Screen Shot 2019-06-17 at 11 40 20" src="https://user-images.githubusercontent.com/1668218/59616621-17c33f80-9125-11e9-88c5-ff7e28678de9.png">

This is due to the fact that the children are [wrapped into a paragraph tag](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Alert/Alert.tsx#L62). Alert component should not be restricted to just have string children, but instead have a capability to format the children.

cc'ing @rhamilto

**Comment by rachael-phillips** [comment]
@jhadvig is this a PF3 issue or a PF4 issue? Also, is this blocking you in any way? Thanks!

**Comment by spadgett** [comment]
PF4. It blocks https://github.com/openshift/console/pull/1699#issuecomment-502635936

**Comment by rachael-phillips** [comment]
@mcoker Titani wanted me to make you aware of this. If we update this as requested it will no longer match core. It also may change the intended design if changed. What would you recommend as next steps on this bug knowing this?

**Comment by mcoker** [comment]
I agree, the `<p>` shouldn't wrap the alert description. This looks like an oversight when we reviewed the alert component in React. The `<p>` in the core example isn't a required part of the component, and is just used as an example. Typically if an element is required for the component, we will add it to the usage documentation for that component. A user should be able to put whatever they want in the alert description.

FWIW, another example is how we wrap the main section content in the [wizard component in core](https://pf4.patternfly.org/components/Wizard/examples-full/?component=Wizard) in a `<p>` in the example, but that isn't included by default in the [wizard component in pf-react](https://patternfly-react.surge.sh/patternfly-4/components/wizard/), since you should be able to put whatever you want in the main section.

Would it help if we removed the `<p>` in the core example?

**Comment by jhadvig** [comment]
@mcoker not really sure removing the `<p>` from the example would be of any help, but we need to remove it from the component source -> https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Alert/Alert.tsx#L62

**Comment by tlabaj** [comment]
@mcoker I think the example in core is ok as is.    @jhadvig  PR #2293 has been pushed to resolve this isssue.

**Comment by tlabaj** [comment]
Closed by #2293
