### ISSUE TITLE
Make charts traversable

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#2506]
relates to #1498 

Possible approaches:
- assign `role="group"` to chart, and `role="presentation"` to elements as described here: https://css-tricks.com/accessible-svgs/#article-header-id-16
- create a hidden table with chart data for SRs 

@jgiardino what do you think?

**Comment by dlabrecq** [comment]
I don't believe we have the ability to add our own `role` attributes to the SVG tags output by Victory. However, it appears that aira roles may already be in place:

FormidableLabs/victory-chart#233

**Comment by dlabrecq** [comment]
Some examples of `role="presentation"`

<img width="887" alt="Screen Shot 2019-07-12 at 12 42 13 PM" src="https://user-images.githubusercontent.com/17481322/61144287-7e2c4b00-a4a2-11e9-829b-1f8eca9e250e.png">

**Comment by dlabrecq** [comment]
Regarding a hidden table, I have some thoughts about Victory's architecture. 

First, consider how each dataset (i.e., the data points for each line, bar, etc.) in a chart is represented by individual components in the bar chart below.

<img width="493" alt="Screen Shot 2019-08-25 at 11 48 02 AM" src="https://user-images.githubusercontent.com/17481322/63652458-60533680-c72e-11e9-8a75-f6a070594063.png">

This particular chart is composed like so:

```
<VictoryChart>
  <VictoryBar data={[{ name: 'Cats', x: '2015', y: 1 }, { name: 'Cats', x: '2016', y: 2 }, { name: 'Cats', x: '2017', y: 5 }, { name: 'Cats', x: '2018', y: 3 }]} />
  <VictoryBar data={[{ name: 'Dogs', x: '2015', y: 2 }, { name: 'Dogs', x: '2016', y: 1 }, { name: 'Dogs', x: '2017', y: 7 }, { name: 'Dogs', x: '2018', y: 4 }]} />
  ...
</VictoryChart>
```

However, not all charts show an x and y axis, so this is also valid as well.

  ```
  <VictoryBar data={[{ name: 'Cats', x: '2015', y: 1 }, { name: 'Cats', x: '2016', y: 2 }, { name: 'Cats', x: '2017', y: 5 }, { name: 'Cats', x: '2018', y: 3 }]} />
  <VictoryBar data={[{ name: 'Dogs', x: '2015', y: 2 }, { name: 'Dogs', x: '2016', y: 1 }, { name: 'Dogs', x: '2017', y: 7 }, { name: 'Dogs', x: '2018', y: 4 }]} />
```

Since data points are provided separately, each component may be able to output its own data in the SVG as a `foreignObject`; however, a couple questions here. 

1. It's unclear if a `foreignObject` would be understood by a screen reader? 
2. Given the current architecture, would each component output its own table?

For example:

```
<?xml version="1.0" standalone="yes"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <foreignObject x="10" y="10" width="100" height="150">
    <body xmlns="http://www.w3.org/1999/xhtml">
      <table><!-- ...  --></table>
    </body>
  </foreignObject>
  <!-- ... -->
</svg>
```

Now consider how the data is provided without units. In order for the table to make sense, a couple more questions to address.

1. How do we combine datasets provided to individual components?
2. Do we need another dataset to include `%` units in the table cells?
3. Axis labels (e.g., percentage, years, etc.) would be lost, unless we can include nested headers?

For example:

<img width="612" alt="Screen Shot 2019-08-25 at 12 16 52 PM" src="https://user-images.githubusercontent.com/17481322/63652787-3ef44980-c732-11e9-8423-5293852dc865.png">
