### ISSUE TITLE
Donut Chart - Handle datasets with 0 values

### ISSUE THREAD

**Issue by kialam** [patternfly/patternfly-react#2542]
If passing in a sample dataset that contains 0 values, I would expect the donut chart to render and the tooltips to reflect the correct values relative to their slices. 

Sample dataset:
```javascript
[{ "x": "Organization 5", "y": 74, "percent": 26 },
{ "x": "Organization 1", "y": 70, "percent": 25 }, 
{ "x": "Organization 4", "y": 55, "percent": 19 }, 
{ "x": "Organization 8", "y": 0, "percent": 0 }, 
{ "x": "Organization 3", "y": 32, "percent": 11 }, 
{ "x": "Organization 9", "y": 16, "percent": 6 }, 
{ "x": "Organization 2", "y": 14, "percent": 5 }, 
{ "x": "Organization 7", "y": 14, "percent": 5 }, 
{ "x": "Organization 6", "y": 5, "percent": 2 }]
```

Observed behavior:
![pf-donut-handle-zeros](https://user-images.githubusercontent.com/2293210/61475490-e83c6880-a958-11e9-987e-3372308ef662.gif)

edit: update percentage values for clarity.

**Comment by dlabrecq** [comment]
Victory is not expected to render a data point with a zero value.

Obviously, the orange data point (above) is not zero. However, you're not seeing that particular tooltip because the container isn't large enough to accommodate tooltips.

You either need to make the SVG larger or use overflow to see all tooltips.

**Comment by dlabrecq** [comment]
This is a dup of https://github.com/patternfly/patternfly-react/issues/2541

**Comment by rachael-phillips** [comment]
Closing as this is a duplica
