### ISSUE TITLE
Dropdown: The first item in the dropdown is always selected

### ISSUE THREAD

**Issue by yuwang-RH** [patternfly/patternfly-react#2569]
The first item in the Dropdown is always selected even when users move on the other item in the dropdown menu. 
It looks strange that there are two item selected when the user try to choose the other item rather than the first one.

**Comment by rachael-phillips** [comment]
@yuwang-RH is this referring to the PatternFly 4 dropdown?
@mcarrano do you know if this is he expected interaction?

**Comment by mcarrano** [comment]
I believe this is because the first item automatically receives focus to support keyboard navigation. @tlabaj @jgiardino can you confirm that this is why the dropdown is coded this way?

**Comment by jgiardino** [comment]
I would have to go back to earlier PR's to dig up specific discussions on this, and am going only on memory here... I'm fairly certain that when @kmcfaul originally implemented the dropdown component, that she was differentiating between mouse click and Enter events, so that if the user is using a mouse, the focus doesn't shift, but when using Enter key (i.e. keyboard only navigation), the focus will shift to the menu.

Testing now, I do see that this behavior isn't there anymore. I'll look for specific comments that detailed this behavior and add those to this issue.

BTW, the selected state that is mentioned in the original description is the focus state. Different browsers have different ways of handling focus (e.g. some browsers don't show it on mouse click, but some do, and browsers can vary on the visual styling used to show focus).

**Comment by jgiardino** [comment]
The second half of the following comment documents the original behavior that was implemented for the dropdown with regard to mouse and keyboard interaction:
https://github.com/patternfly/patternfly-react/issues/1002#issuecomment-452763351

And this behavior was implemented in https://github.com/patternfly/patternfly-react/pull/1075

**Comment by kmcfaul** [comment]
When using keyboard navigation, hitting enter on a dropdown should open the menu and move focus to the first element. After which the arrow keys will move the focus up and down. When using the mouse, the first element will not be focused, but hovering the mouse over an element will show the same grey highlighting. 
Is this double selection using both types of input or just one or the other?
