### ISSUE TITLE
Mssing default props

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2772]
It looks like when a lot fo components were transformed to TS a lot of them started to use default parameters instead of defaultProps.

This causes several problems
* snapshots changed when consumers used `mount` - a lot of unnecessary snapshot changes needs to be applied
* React extension is not usable for lot of components - if component does not set `defaultProps` it will not display them in React extension. This might seem as a minor issue, but that is actually really usefull when you are using these components as you can change props on the fly. 
**Before**
![Screenshot from 2019-08-26 11-13-49](https://user-images.githubusercontent.com/3439771/63679853-9ce86600-c7f2-11e9-9757-fe212afee18c.png)
**After**
![Screenshot from 2019-08-26 11-05-43](https://user-images.githubusercontent.com/3439771/63679403-85f54400-c7f1-11e9-93ee-86abe43a5435.png)

Even though it is correct to use default parameters instead of default props, for better code style and consistency it's better to use default props. And of course the great benefit of helping developers to use PF4 components.

**Comment by karelhala** [comment]
@rachael-phillips even though this can seem like a minor problem it should actually be taken care of sooner rather than later. Plus this change is really low hanging fruit so if you want some devs to start codig and understand how React works, it's best issue.

**Comment by karelhala** [comment]
@dlabaj I am not that big of a fan of adding babel plugin to change code and pass these things around. However given that react wants to deprecate defaultProps on functional components https://github.com/reactjs/rfcs/pull/107 (learned that just now) I think that babel plugin might be better because we'd have to rewrite this to defaultProps and once react deprecates them back to default params.

**Comment by dlabaj** [comment]
@karelhala Sounds good.  Thanks for the link to the issue above.  We'll go down babel plugin route given the information you found.

**Comment by redallen** [comment]
@karelhala I'm thinking that this can be a part of our greater move to using `tsc` instead of `babel` and that we could write it as a [TypeScript transform plugin](https://dev.doctorevidence.com/how-to-write-a-typescript-transform-plugin-fc5308fdd943). Let me explain.

Currently, to generate `propTypes`, we use [babel-plugin-typescript-to-proptypes](https://www.npmjs.com/package/babel-plugin-typescript-to-proptypes) which I find less than ideal. @TheRealJon and I have found numerous errors and inconsistencies in its behaviour. Our own extension can add whatever we want to the JS (`propTypes`, `defaultProps`, etc.) and we can enforce proper behaviour and handle function components however we want.
