### ISSUE TITLE
PageSidebar opens and closes if it is closed and we're resizing from md to sm

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2868]
When resizing a Page with PageSidebar from md to sm size that has a closed sidebar, it will open and close the sidebar instantly when switching between md and sm. This can be seen on both the demo from PatternFly website and from surge:

* https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutsimplenav/
* https://patternfly-react-seed.surge.sh/

## Reproducible steps
1. Open one of the demos
1. Have a window size larger than md
1. Close sidebar
1. Resize window to sm or smaller
1. See sidebar pop into existence and close itself

**Comment by rebeccaalpert** [comment]
I opened an issue for this at patternfly-next (https://github.com/patternfly/patternfly-next/issues/2252) since it seems like a CSS issue (props and modifiers look OK). It doesn't look like there's any .pf-m-collapsed-related styles for the smaller breakpoints, so I'm wondering if that's all we need. I got it to go away locally by adding this:
```
.pf-m-collapsed.myClassNameHere {
  min-width: 0;
  overflow: hidden;
  transform: none;
}
```

**Comment by rachael-phillips** [comment]
@rebeccaalpert are we ready to close this issue?
