### ISSUE TITLE
Button shows error in console on reload

### ISSUE THREAD

**Issue by AlexSCorey** [patternfly/patternfly-react#2980]
When I go to a page that has a button the page loads fine without any error in the console.  However, when I refresh the page I get a console error. `Warning: Failed prop type: Invalid prop component supplied to `Button`, expected a ReactNode.`

![Button Bug](https://user-images.githubusercontent.com/39280967/65341306-0ebb9180-db9e-11e9-9b63-59f2e1441087.gif)

**Comment by boaz0** [comment]
Hi @AlexSCorey 

Can you show the code of that page? It's hard to tell what causes this error but my guess (which is not good) is it's related to the breadcrumb.

Thanks.

**Comment by boaz0** [comment]
@AlexSCorey :wave: 

OK, the problem is what I thought: the type of [the `component` prop](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Button/Button.tsx#L28) doesn't cover all the cases.

`ReactNode` is good for HTML elements (`'a'`, `'button'`) or a react component that is passed after rendering (`<Link to="/my_switch" />`). However, in this case the `Link` component itself is passed and thus the error message. To fix it we need to update the type.

@rachael-phillips @tlabaj can you assign me to this?
Thanks.
