### ISSUE TITLE
Select dropdown is not fully visible inside Page Component 

### ISSUE THREAD

**Issue by akshygupt** [patternfly/patternfly-react#3000]
System Details:
Operating System: Fedora 29
Chrome 77

"@patternfly/patternfly": "^2.33.3",
 "@patternfly/react-core": "^3.104.0",
 "@patternfly/react-styles": "^3.5.22",

I used the Page layout and tried to put in a Select Dropdown but when i expanded it, it wasn't fully visible. [Code Sandbox Code](https://codesandbox.io/s/interesting-jones-xrcys) [Code Sandbox Example](https://xrcys.csb.app/)

It seems the overflow: hidden property is hiding the dropdown.

.pf-c-page__main{
...
overflow-x: hidden;
...
}

I have a small form with a bunch of Dropdowns at the top of my page and i have to overwrite this property to show the complete dropdown.

**Comment by redallen** [comment]
Hey @akshygupt , it looks like your Select isn't visible because the page is not tall enough to accommodate it. You can set `height: 100vh;` on the `<Page>` component to fix this, which is the pattern we often use in our examples. I've fixed your example by using a `style` tag: https://codesandbox.io/s/confident-noyce-wcrty
```jsx
        <Page
          header={Header}
          sidebar={Sidebar}
          isManagedSidebar
          skipToContent={PageSkipToContent}
          mainContainerId={pageId}
          style={{ height: "100vh" }}
        >
```
Your fix of overriding the `overflow-x: hidden;` property is also valid. If you would like this property to be changed in the default `@patternfly/patternfly` CSS, please open an issue at https://github.com/patternfly/patternfly-next, we can't change it here in React!

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
@akshygupt in PatternFly, we apply `height: 100%;` to `<html>`, `<body>`, and `<div class="pf-c-page">`. In order for the `<Page>` component to be full height, if you have any additional elements in your application that exist between `<body>` and `<div class="pf-c-page">`, you will need to add `height: 100%;` to them in your application's CSS. This is mentioned here in the page layout demo documentation:

https://www.patternfly.org/v4/documentation/react/demos/pagelayout/

> To make the page take up the full height, it is recommended to set the height of all ancestor elements up to the page component to 100%

I've updated your codesandbox here - https://codesandbox.io/s/floral-dew-qmkpo

**Comment by akshygupt** [comment]
@mcoker  thanks for the info.
