### ISSUE TITLE
Charts: interactive legend

### ISSUE THREAD

**Issue by jotak** [patternfly/patternfly-react#3073]
Is there any plan to have a built-in interactive legend as there was in pf3 / c3 charts ?
Previously, clicking on legend icons would show/hide the related series in charts.

With victory chart I believe there's no such mechanism built-in, but we can implement it through events. I'm doing something like that in Kiali: https://github.com/kiali/kiali-ui/pull/1457/commits/63d400d58c2fdcbbb4a77c087c2b76511be6801e#diff-82e26dca83e13db6b8969687fd9268cbR71-R156 . Maybe that can be part of the patternfly value-added & standard look n feel?

Also note that, currently I cannot do it using the `ChartLegend` component from PF4, as it seems events are not fired when targeting the legend (I believe it's due to the wrapping component) so I need to use `VictoryLegend` directly instead of `ChartLegend`.

**Comment by jotak** [comment]
PS: this is something I can contribute for, if it gets some chance to be accepted

**Comment by dlabrecq** [comment]
I have implemented this in Cost Management using the ChartLegend. This implementation allows the user to click on either the legend symbol or label.

This is the custom Legend component with event handlers for onClick:
 
<img width="644" alt="Screen Shot 2019-10-04 at 9 36 38 AM" src="https://user-images.githubusercontent.com/17481322/66211797-b9e24580-e68a-11e9-8663-78596b5614fc.png">

And this is how the custom Legend component is added to the chart:

<img width="659" alt="Screen Shot 2019-10-04 at 9 38 07 AM" src="https://user-images.githubusercontent.com/17481322/66211810-bea6f980-e68a-11e9-9bc9-59ec46557361.png">

The chart is composed of multiple components, but the legend doesn't know anything about the charts data. That's what we're wiring up above.

We can certainly add an example of this -- this was on my next to do. However, it may be possible for the `Chart` component to wire this up, if you also allow the chart to create the legend. It would also need to be implemented in other components that don't use `Chart`.

**Comment by jotak** [comment]
I see, it's another approach of dealing with events, it's interesting.

> A chart is composed of multiple components, so the legend doesn't really know anything about the chart's data. That is, unless it's assumed you're providing the same data object? That's what we're wiring up above.

Yes, same as you, I ended up correlating chart data and legend data, enforcing a 1-to-1 relation between a timeseries and a legend item (here's how: https://github.com/kiali/kiali-ui/pull/1457/commits/63d400d58c2fdcbbb4a77c087c2b76511be6801e#diff-7bf01c70aab3be56bf4a4e8e7ffce668R3-R20 in `VCLines` objects). I understand that victory doesn't do that because they provide kind of "low level" components, but at patternfly's level I think it totally makes sense to have something more integrated. IMO it would make the component easier to use and to reason about.

As for the events, I understand that having "internal" event creates a risk to interfere with user events, but as long as the legend is something created internally in patternfly, not in user code, I guess it makes you legit to have events on it.

**Comment by dlabrecq** [comment]
I'm going to try kicking of a design discussion about what we want to implement. That is, should we strive to implement the C3 features in PF3 or something completely different, like what Analytics has implemented with their legend toggle button?

**Comment by jotak** [comment]
I haven't seen toggle buttons in action but I'm confident that you'll get good design feedback :)

**Comment by dlabrecq** [comment]
This is from Analytics -- think it's called the ISV monitor UI

<img width="252" alt="Screen Shot 2019-10-04 at 12 10 01 PM" src="https://user-images.githubusercontent.com/17481322/66222796-f53b3f00-e69f-11e9-817b-68b92f10de8c.png">

**Comment by dlabrecq** [comment]
FYI @jotak, I created a POC with you're implementation. The POC relies on the theme to coordinate colors between ChartArea, ChartScatter, and the custom ChartLegend -- not necessary to use custom colors.

I also fixed ChartLegend so that you won't need to rely on VictoryLegend. That change will be added via https://github.com/patternfly/patternfly-react/pull/3067

I like your use of the `onMouseOver` and `onMouseOut` events. While the user hovers over a legend label, the line representing the data series is highlighted by making it 2x wider. Although, that is the opposite behavior I see with PF3.

In PF3, the opacity is lowered for all other data while hovering over a legend label. That is, we blur everything, but the data series the user is currently viewing.

Considering the Cost Management UI may have up to 8 lines of historical data, we also need a way to hide / show each data series individually. PF3 never implemented that type of behavior.

That said, I took the implementation a little further and was able to duplicate the PF3 behavior below.

PF3 blur functionality:
![chrome-capture](https://user-images.githubusercontent.com/17481322/66280589-70aa1580-e885-11e9-988c-3491fa0d5e31.gif)

I was also able to use `onClick` events to hide / show each data series individually. Although, I wasn't able to use events to demo both features at the same time -- difficult to ensure events don't reset the styles of each other.

Hide / Show functionality:
![chrome-capture (1)](https://user-images.githubusercontent.com/17481322/66280625-933c2e80-e885-11e9-8d87-b0faf245c0da.gif)

Unfortunately, maintaining state via events doesn't work very well. When the cursor moves outside the SVG or a tooltip is shown, the hidden data series is redrawn.

This leads me to believe that the hide / show state must be maintained outside the events, similar to my Cost Management example. Charts are stateless and use composition, so I'm not certain we could built that feature internally?

That said, I've put out the request to our design team to get this prioritized. I'm hoping to use all this as a POC to show what features may be possible.

**Comment by jotak** [comment]
Awesome! :)
About my previous example, yes it was an exact copy of pf3 behaviours but I wanted to check what could be done with events. I'm not sure if people will prefer hiding/showing versus highlighting.

I'm fine with just an example if you think events won't be stable and robust enough for that.

**Comment by dlabrecq** [comment]
Good point. I believe we want to omit the data being hidden, Vs just applying styles, so that the chart can adjust its domain appropriately. I'll update my hide / show POC to do that and share.

**Comment by jotak** [comment]
Hi @dlabrecq ,
If you want to take a look (might give some ideas for an example), I've implemented a solution with a mixture of events (for hovering) and react state (for clicks show/hide) which refreshes the domains as wanted. This is in file "SparklineChart.tsx" here: https://github.com/kiali/kiali-ui/pull/1457/files#diff-f91e53dbcd8ec7fb34893a2d850e6c6e

It's also using an aggregated model for series and legend items as we discussed before.

**Comment by dlabrecq** [comment]
Thanks, I'll check it out. I'll also share the example I'm working on; although, this has not been approved by our design team. 

https://github.com/dlabrecq/patternfly-react/blob/interactive-legend/packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md

The `onClick` events work to hide / show each data series individually, while the `onMouseOver` / `onMouseOut` events blur data similar to the PF3 area chart. I would like to apply some styling to the legend items when data is hidden -- that may be a change to ChartLegend.

Not that I'm basing this on the ChartLegend fixes which have not been merged, yet.

**Comment by dlabrecq** [comment]
Thanks, I'll check it out. I'll also share the example I'm working on; although, this has not been reviewed by our design team -- just a POC regarding what is possible. Note that this is based on the ChartLegend fixes which have not been merged, yet.

https://github.com/dlabrecq/patternfly-react/blob/interactive-legend/packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md

The `onClick` events work to hide / show each data series individually, while the `onMouseOver` / `onMouseOut` events blur data similar to the PF3 area chart. 

Update: added legend item styling when data is hidden. Also disabled the `onMouseOver` event while data is hidden for a given legend item.
