### ISSUE TITLE
PF4 Tooltip: add support for right-aligned content

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#3089]
This is a follow-up to #3013. 
--
Why only support a left aligned option? What if designers want to support right-aligned content, next?

Even if we don't support right-aligned content for now, something more like this would scale better in the future.

```
contentPosition?: 'bottom' | 'center' | 'right';
```

Then we could create an enum

```
export enum TooltipContentPosition {
  bottom = 'bottom',
  center = 'center',
  right = 'right'
}
```

Looks like we already take this approach for the `position` property.

_Originally posted by @dlabrecq in https://github.com/patternfly/patternfly-react/pull/3053_

**Comment by mcarrano** [comment]
@jenny-s51 Can you give me an example of where you would want right-aligned content in a tooltip?

**Comment by dlabrecq** [comment]
@mcarrano This issue was created in regard to my review comments in https://github.com/patternfly/patternfly-react/pull/3053, where we added a new `isContentLeftAligned` property.

For the React modal component, we have both `isSmall` and `isLarge` properties. This looks very odd in my code because the modal cannot be both, obviously. 

![Screen Shot 2019-10-08 at 2 09 47 PM](https://user-images.githubusercontent.com/17481322/66421137-50896c00-e9d5-11e9-9917-a4bef3e17145.png)

My comments were intended to avoid the scenario where the tooltip ends up with both `isContentLeftAligned` and `isContentRightAligned` properties. My suggestion was to follow the existing `position` prop, which is more scalable, and add something more like `contentPosition?: 'bottom' | 'center' | 'right';`

That said, the ask for In Cost management is that multi-line chart tooltips not be centered. We're going to make them left-aligned, but the content could just as easily be right-aligned.

**Comment by mcarrano** [comment]
Yes, one could right-align the tooltip text, but it does not seem like a good solution from a readability standpoint IMO.

**Comment by dlabrecq** [comment]
We can probably close the issue
