### ISSUE TITLE
Allow to trigger Popover on mouseenter

### ISSUE THREAD

**Issue by jotak** [patternfly/patternfly-react#3116]
Hi,

In Kiali we have a regression with PF4, as it seems popovers can't be triggered on mouse-enter anymore (or I didn't find how).
Is it done on purpose? It would be nice to get it back.

Before you ask, I've also considered using `Tooltip` instead of `Popover` but it doesn't really look well because it's not short content (as supposed to be in tooltips) and also tooltip text is centered which is not what I want.

Related PR in Kiali: https://github.com/kiali/kiali-ui/pull/1475

**Comment by jgiardino** [comment]
In response to @mcarrano's [comment on the PR](https://github.com/patternfly/patternfly-react/pull/3185#pullrequestreview-312684384) that was opened related to this, I wanted to see what the Tooltip component currently supports. 

In the example below, I modified the react of our first [tooltip](https://www.patternfly.org/v4/documentation/react/components/tooltip) example to include the class `pf-u-text-align-left`. This does change the alignment of the contents of the tooltip. 

I also tried adding a Title component to add a heading, and since the default styles for the Title is intended for a light background, this text is not visible.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/21063328/68335113-dddde000-00a9-11ea-82f4-64bcdbff9dde.png">

**Comment by jotak** [comment]
Hi @jgiardino
As commented in the PR, we adopted a similar solution as what you suggest anyway, using Tooltip : https://github.com/kiali/kiali-ui/pull/1521/files (although it's because of another issue with Popover)
We're using `TextVariants.h2` to show a title, and some custom css.
I'm also seeing that Tooltip now has a props `isContentLeftAligned` which, I guess, set the `pf-u-text-align-left` class as you suggest? If so we will probably use that later but for now we're some versions behind that.
cc @aljesusg

**Comment by tlabaj** [comment]
Closing this issue based on the discussion above.
