### ISSUE TITLE
PF4 testability for integration UI tests

### ISSUE THREAD

**Issue by vmuzikar** [patternfly/patternfly-react#3152]
Hi,
we're facing some issues with writing integration UI tests (tests that use real browsers) for our PF4/React based application. The problem is in the selectors. We currently need to strongly rely on CSS classes and element sequence so most of our selectors now look like this:
```
*[@id='main_react_container']//header/div[@class='pf-l-toolbar__item pf-m-mobile']/div[contains(@class, 'pf-c-dropdown')]/ul/nav/ul/li
```
This is quite unusable for us in long term. All it takes to break a test will be just minor change to the UI, like adding a button or a class name change with a PF4 update. Also writing the selectors this way is *very* time consuming as it requires deep DOM investigation.

We'd like to use the ID attributes to select elements as the most robust way. However, the issue with this is that even though IDs are present on most of the elements, they're generated and therefore dynamic.

This issue doesn't seem to affect only a specific component but rather petternfly-react in general.

Are we missing something? Can we somehow force the components to use static IDs?

We're using Selenium Webdriver and the testsuite is Java.

**Comment by dgutride** [comment]
Hi @vmuzikar  - we directly support using OUIA tags with our components to support automated test suites.  You can read more about those in this issue on the forum:  https://forum.patternfly.org/t/open-web-ui-design-specification-for-enabling-automation-ouia/154

and this closed issue that resulted in a way to turn OUIA tags on for discoverability when running automated tests - https://github.com/patternfly/patternfly-react/issues/2303.  We chose not to include them by default with the components in order not to add bloat to the DOM when reusing components.

Defining selectors the way you have them is problematic since structure can change periodically and using classes instead of definitive id's is not great (as you mentioned).  @quarckster has done quite a bit of the work contributing to these components as well.

All that being said - we also do support using id's on the components.  I'd recommend enabling OUIA and using those attributes to select after you get to a parent component with an id.

**Comment by quarckster** [comment]
@vmuzikar we discuss using OUIA offline

**Comment by vmuzikar** [comment]
@dgutride @quarckster Thank you!
I'm closing this ticket (for now). We'll open a follow up ticket if needed.

**Comment by vmuzikar** [comment]
I know this issue was closed but I'd like to ask a follow-up (and maybe a bit silly :)) question regarding this.

I've noticed that we can set a custom ID attribute to pretty much every component, even to those that generate their own IDs.  This way it's possible to sort of "override" the ID and it's then used the same way as it were generated (e.g. used in any related elements and such). E.g. the `DropDown` component:
```typescript
<Dropdown
    isPlain
    position="right"
    toggle={<KebabToggle onToggle={this.onKebabDropdownToggle} id="my-custom-kebab-id" />}
    isOpen={this.state.isKebabDropdownOpen}
    dropdownItems={kebabDropdownItems}
/>
```
Notice the ID set on `KebabToggle` component. This ID will be then present on the actual HTML button element and it will be also used by the actual dropdown menu in `aria-labelledby` attribute – just like the ID were generated and not "hardcoded". And it seems to work like that with other components that generates IDs as well.

Is this expected behaviour (that you can "override" generated ID and force components to use custom ID)? Can we rely on this (e.g. that it won't be removed in some future patternfly-react version)? This way we wouldn't need to adopt and use OUIA which turned out to be a bit problematic.

**Comment by rachael-phillips** [comment]
@

**Comment by rachael-phillips** [comment]
Hi @vmuzikar our team has seen this issue, and I can get back to you next week once we have a chance to look deeper at this.

**Comment by tlabaj** [comment]
The components that have the generated ID that can can be overridden is intentional and will remain that way.

**Comment by vmuzikar** [comment]
@tlabaj Thanks for the confirmation!
