### ISSUE TITLE
"Call retries were exceeded" build failure in CI

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3266]
I've noticed that some times after posting a PR, the CI build pipeline fails on the `build:docs` target. Running it locally builds fine, and you can get it to work by re-running that step in the workflow, but it's disruptive and adds to the overall time it takes for developers to submit PR's and make them ready for review.

Here's a couple of examples

https://circleci.com/gh/patternfly/patternfly-react/18329
https://circleci.com/gh/patternfly/patternfly-react/17953

Is there something we can do to ensure this step doesn't fail randomly? @redallen might have some insight here?

<img width="864" alt="Screen Shot 2019-11-05 at 9 53 35 AM" src="https://user-images.githubusercontent.com/5942899/68218347-2a45f480-ffb2-11e9-968e-9545a6df1f33.png">

https://gist.github.com/seanforyou23/c8251f178a81ba22cba65eb98d6e5ef5

**Comment by redallen** [comment]
This is because Gatsby uses more than the 2GB of RAM CircleCI gives us with its docker container.

Our choices are to find a way to make Gatsby use less RAM, upgrade CircleCI (and get some other benefits like more executors for our 5 projects), or use a [different executor type](https://circleci.com/docs/2.0/executor-types/) than Docker that has more RAM.

**Comment by seanforyou23** [comment]
Thx for the additional info @redallen! I have less opinion on which specific strategy we go with, just that the CI builds are stable for a team our size.
