### ISSUE TITLE
Alignment issue with last child on simple table in small resolutions

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-react#3301]
We ran into this in Cockpit, and I think it's an issue in Patternfly in general.
Looking at the [example page](https://www.patternfly.org/v4/documentation/react/components/table/basic), if you resize the viewport to 768px, the items `five` and `five-two` doesn't line up, but fly out to the right.

![image](https://user-images.githubusercontent.com/209895/68768228-69172280-0622-11ea-85d4-930d0581f7d0.png)

**Comment by rachael-phillips** [comment]
Hi @andreasn thanks for bringing this to our awareness. We've seen this and will be looking into this next week.

**Comment by seanforyou23** [comment]
Hi @andreasn, I think this is actually due to how the example is set up. The "Last commit" column applies a `textCenter` transform like this

```js
        {
          title: 'Last Commit',
          transforms: [textCenter],
          cellTransforms: [textCenter]
        }
```

I think what you're seeing is that the other columns are left aligned by default and the last commit cell data is centered within that space, of course except for the last one "five - 3 (not centered)". This one is left aligned like the rest because we "unset" this transform like so:

`props: { textCenter: false }`

Does it make sense? Let me know if this helps or if you see any other issues. Thanks!

**Comment by rachael-phillips** [comment]
@andreasn and @seanforyou23 can I move forward with closing this issue?
