### ISSUE TITLE
DateTimePicker: misplaced calendar popup

### ISSUE THREAD

**Issue by mzazrivec** [patternfly/patternfly-react#3306]
I wanted to use `DateTimePicker` component in ManageIQ but for some reason the calendar popup gets misplaced (along the x-axis, it seems):

![datetimepicker](https://user-images.githubusercontent.com/6648365/68942817-c5587e80-07a9-11ea-9f6c-9593a4bdae10.png)

I'm not sure how much it matters here, but the datetimepicker is part of a modal with rougly the following structure:
```
<Modal>
  <Modal.Header ... />
  <Modal.Body>
    <div>
      // all the radio inputs land here
    </div>
    <div className="row">
      <div className="col-xs-2">
        <DateTimePicker placement="bottom"/>
      </div>
    </div>
  </Modal.Body>
  <Modal.Footer .../>
</Modal>
```

Upon close inspection, the `<div id="datetime-picker-popover"...>` (the div containing the whole actual popup) uses `bootstrap-datetimepicker-widget.dropdown-menu` classes, which contain the following line:
```
.bootstrap-datetimepicker-widget.dropdown-menu {
  left: 0 !important;
...
``` 

![datetimepicker-explore01](https://user-images.githubusercontent.com/6648365/68943408-6c89e580-07ab-11ea-884e-8bbbe57be6fc.png)
![datetimepicker-explore02](https://user-images.githubusercontent.com/6648365/68943412-6eec3f80-07ab-11ea-89fc-ccca2d43c653.png)

**Comment by rachael-phillips** [comment]
HI @mzazrivec our team has seen this issue, and we can will get back to you early next.

**Comment by rachael-phillips** [comment]
@mcoker I spoke with @mturley, and he mentioned to me we should look into the CSS. Do you think this could be an issue with the CSS?

**Comment by mturley** [comment]
It's definitely an issue with CSS, the question is whether it's patternfly CSS or product CSS :)

**Comment by mcoker** [comment]
Hey @mzazrivec if you look at our core example of that widget on https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/date-and-time.html, it looks like that `absolute` positioning is dependent upon `position: relative;` on the parent `.input-group` that holds the text input and button that triggers the menu. 

From looking at the code in your dev tools, it looks like this widget is being appended to the `<body>`. Is it possible to instead append it to the `.input-group` element that wraps the text input and button that trigger the menu?

**Comment by mzazrivec** [comment]
@mcoker The example you are linking above is pure patternfly, i.e. markup + javascript initialization. That is in fact what we're currently using in ManageIQ and it seems to be working fine.

What I wanted to use (and what this issue is about) was a patternfly-react `DateTimePicker` component, i.e. instead of
```html
<div className="form-group">
  <div id="dateTimePicker" className="input-group date-time-picker-pf">
    <input id="dateTimeInput" type="text" className="form-control" />
    <span className="input-group-addon">
      <Icon type="fa" name="calendar" />
    </span>
  </div>
</div>
```
You should be able to just use
```
<DateTimePicker />
```
That component renders the input field with calendar icon and that component also appends the element containing the whole calendar popup to the body element (via portal, I assume). I don't really append anything anywhere.

**Comment by mturley** [comment]
@mcoker it sounds like that might be the change we need to make to the React component to fix this.

**Comment by mcoker** [comment]
@mzazrivec Ah thanks, found the react component. @mturley can we add `!important` to the inline `left` CSS property that is added via react to position the widget? That will position the widget relative to the button that clicked it, rather than the `.input-group`, which is how the individual date and time picker widgets are displayed.

**Comment by mturley** [comment]
I can take a look soon, but it might need to be next week. Is `!important` really the best way to fix it? I thought that was an antipattern (I guess it must exist for a reason, though).

**Comment by mcoker** [comment]
> Is `!important` really the best way to fix it? I thought that was an antipattern (I guess it must exist for a reason, though).

Yep, the existing `!important` in the PF3 CSS is the issue - ideally we would remove that so that it doesn't have to be used again to overwrite the existing `left` value, but I'm hesitant to do that as it could be a breaking change for users depending on how they're using the widget currently.

Another way to fix it could be to add a unique class to the widget when it's triggered in react that we can use to exclude the existing `left: 0 !important;` declaration in the PF3 CSS, allowing the `left` value that the react component applies to overwrite the existing declaration without `!important`.

In this case, I think it's fine to use `!important` since we want the react positioning to overwrite any existing `left` declaration. That said, I wonder if updating this would also introduce a breaking change to users currently using the widget that may be reliant upon the `left` declaration that comes from the PF3 CSS? Would it be better to introduce a prop that adds `!important` to the `left` position value (or adds a class that allows us to exclude the PF3 CSS's use of `!important`)?

**Comment by mturley** [comment]
Bumping stalebot, this should still be fixed eventually.
