### ISSUE TITLE
Charts: Update interpolation examples to use monotoneX

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-react#3329]
On area and line charts, the way curves are drawn creates misleading visualization. 

In the chart below, the data goes from 0 on one day to 156 the next then remains at 156. Where the line goes up to 156, a bump appears which is misleading. The curve should never go beyond the indicated value. 

![image](https://user-images.githubusercontent.com/2206023/69272017-e81cd580-0ba3-11ea-994d-ce2d2d9a7202.png)

The issue is also exists at the bottom of the chart, where you can see the line dips below the x axis. 

![image](https://user-images.githubusercontent.com/2206023/69272505-b6f0d500-0ba4-11ea-9dc4-2e32d61b854f.png)

This can be seen in cloud.redhat.com at 
https://cloud.redhat.com/beta/subscriptions/rhel-sw/all

**Comment by jeperry** [comment]
FYI @dlabrecq @cdcabrera

**Comment by dlabrecq** [comment]
I suspect this particular chart is using Victory's optional interpolation. PatternFly charts do not set `interpolation` by default; otherwise, it would show linear lines. 

I have not seen our chart examples render like this with interpolation="basis", but curious to know what they're using -- my guess is "cardinal"? There are several options shown below.

"Cartesian area charts may use the following interpolation options: "basis", "cardinal", "catmullRom", "linear", "monotoneX", "monotoneY", "natural", "step", "stepAfter", "stepBefore"

See docs https://formidable.com/open-source/victory/docs/victory-area#interpolation
Live demo of all interpolation options: https://formidable.com/open-source/victory/gallery/interpolation/

**Comment by jeperry** [comment]
According to @cdcabrera he is using "catmullRom." It is interesting to me that in the docs there does not seem to be any run-over (bump).

**Comment by jeperry** [comment]
Given the above I think we can close this issue but I wonder if want to provide any guidance in PF about this (ok if not). David can make this change in his app.

**Comment by dlabrecq** [comment]
Our React examples show `interpolation="basis"`, but we could change that to use "monotoneX".

**Comment by jeperry** [comment]
yeah, I'd recommend that switch to "monotoneX" since "basis" seems to not necessarily hit the data points accd to their demo.
