### ISSUE TITLE
Example usage of table inline editing

### ISSUE THREAD

**Issue by dalaicam** [patternfly/patternfly-react#3357]
Cheers,

Was trying to integrate the table inline editing in the project I'm currently in, but having a bit of difficulty to understand how to actually include and use it properly.
The project is being developed using Typescript and React.

Was following the examples as base to have the component integrated, though can't advance much since getting the error:
'EditableTableBody' only refers to a type, but is being used as a value here.ts(2693)

eg.
```
import React from 'react'
import { Table, TableHeader} from '@patternfly/react-table';
import {
  EditableTableBody
} from '@patternfly/react-inline-edit-extension';

export default class InlineEditTableTest extends React.Component {

  render() {
    const editConfig = {
    };

    return (<Table
        aria-label="Editable Table"
        cells={[]}
        rows={[]}
      >
        <TableHeader />
       <EditableTableBody editConfig={editConfig} />
      </Table>
    )
  }
}
```

This error happen to all other components related with the table inline editing.

Not sure if the way we are using is not the correct or if an issue in the configuration.
If not issue, would it be possible to provide a small example of how it is expected to be used with Typescript?

Thanks for the help

**Comment by rachael-phillips** [comment]
Hi @dalaicam  our team has seen this, and we will be taking a look at it this week.

**Comment by dalaicam** [comment]
Were you able to check the situation?

Thanks for the help

**Comment by rachael-phillips** [comment]
@dalaicam thank you for following up! Is this currently blocking you? We are going to be introducing an inline edit feature, and that could be worth waiting on since we aren't offering support for the extension at this time.

**Comment by dalaicam** [comment]
@rachael-phillips thank you for the quick response.
Currently this feature is not blocking the development, but the sooner we have it implemented/available the better as we will be able to test and validate if it's necessary to make adjustments to the application (user feedback, etc...).

When are you predicting to have this feature included and available (at least as experimental) in the API?

Once again, thank you for the help and attention

**Comment by seanforyou23** [comment]
Hi @dalaicam - it has taken a while but we just merged the new inline edit feature. It's supported in core and react, and now supersedes the previous inline-edit-extension. Since it's a critical new feature, we've marked it as `beta`, and for a while, we'll probably leave the inline edit extension around in case people are still using it and want to test out the new version before migrating. I'd love any feedback you may have, feel free to give it a try when you have time.

The last thing to mention is that since we've just merged this, it's not on the public-facing documentation site just yet, it should show up next time we update it - not sure exactly when this will happen but I'd expect within the next few business days. In the meantime, you can access the example through the [PR preview URL](https://patternfly-react-pr-3581.surge.sh/documentation/react/components/table#editable-rows). I'll close this issue for now, feel free to reopen if I've missed anything. Thanks for raising this issue and being patient for the solution, good luck!
