### ISSUE TITLE
Feature Request: Investigate adding async support for components

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#3406]
Many applications are using a form of async communication (promises, observables, etc.) to load components.  It would nice to have an optional feature that would provide this support for some of our components (e.g. A function that sets a state to loading, call an async function, and then load the component according to the developers needs) to do this in a standardize way.

Here is an example on how it's done with react-select:

https://react-select.com/async

If we can find a way to do this across components using the same API, and same code that would be the ideal solution.

This would be in addition to the demo request in #3405

**Comment by seanforyou23** [comment]
In case it is helpful, we have a [simple solution](https://github.com/patternfly/patternfly-react-seed/blob/master/src/app/DynamicImport.tsx) I cobbled together for the seed project to facilitate this. It does the job technically but has [some issues](https://github.com/patternfly/patternfly-react-seed/issues/65). Here's how you [define a component](https://github.com/patternfly/patternfly-react-seed/blob/master/src/app/routes.tsx#L13-L38) using it. Probably better ways of accomplishing this, just wanted to +1 the idea and show what we have. I would love to use something PF supported instead, and happy to help test/review the solution when it's ready.

**Comment by mturley** [comment]
Note for posterity: The solution @seanforyou23 is referring to above was removed from the patternfly-react-seed repo in https://github.com/patternfly/patternfly-react-seed/pull/103. Here's a [permalink to the DynamicImport.tsx file](https://github.com/patternfly/patternfly-react-seed/blob/015ddf4d65356d8f6d89f20b9d372c1afac022f8/src/app/DynamicImport.tsx) before it was deleted, and a [permalink to the usage](https://github.com/patternfly/patternfly-react-seed/blob/015ddf4d65356d8f6d89f20b9d372c1afac022f8/src/app/routes.tsx#L13-L38) referenced above.

It seems that solution was causing issues during a dependency upgrade and was removed since it was just a stub. If this is ever revisited, restoring that may be a good starting point.

The rabbit hole that got me here is described in this comment: https://github.com/patternfly/patternfly-react-seed/pull/103#issuecomment-1221031317
