### ISSUE TITLE
Select multiple option typeahead - un-expand options when return hit

### ISSUE THREAD

**Issue by xeviknal** [patternfly/patternfly-react#3488]
Hey there,

In kiali we are thinking of introducing the selector with the `typeaheadmulti` variant. We were thinking if there could be the possibility to shrink the options everytime user hit the return key to select an option. And if the user type another option, the option should appear again.

The current behavior we have is:

![Screen recording (20)](https://user-images.githubusercontent.com/613814/72154339-abee4000-33b0-11ea-9c50-5758c8346b5d.gif)

We'd like to have all the options listed right after the first user's keystroke.
I'd been looking through all the components property and I don't see one that could help in that way. I also thought that a callback property being called after each stroke it would be useful. There I could manage to toggle the `isExpanded` property.

**Comment by rachael-phillips** [comment]
HI @xeviknal can you clarify what requests you have here for this interaction? We are trying to get a greater understanding of how the ui should behave. 

What are you asking for when it comes to the user's keystroke? Thank you for the explanation!

**Comment by xeviknal** [comment]
Yes, sure. And sorry for my fuzzy description above.

If you see the gif in the description, when I first type an option, the component properly show the filtered options. When I am typing the second option, the list of options doesn't appear (note that I did hit the 'enter' key to select the option, instead of a click).
So what it could be useful for us is to have the ability to show the filtered option's list for the second word the user types.

So, what we would need is a way to capture the user's keystroke to manage the `isExpanded` property. After the first user's keystroke in the second word, I would need to change the `isExpaned` property to `true` in order to show the filtered list of options.

I am thinking of a callback called at every keystroke or when user have the first keystroke.

Does this make sense? Happy to re-explain myself. or even join you guys in a chat, if needed.

**Comment by kmcfaul** [comment]
Hi @xeviknal,

I tried out modifying one of our examples to use a multiple typeahead select variant. Does the "Location" filter in this codesandbox example sort of match the behavior you are wanting for the input? I removed the callback that toggles the filter's dropdown when something is selected, so the menu stays open until it is clicked out of or `escape` is pressed.

https://codesandbox.io/s/filterable-tablemulti-select-utpnn

We do need to introduce a flag to hide the display of selected options in the input of the menu for this use case, since here it is handled by the `DataToolbarFilter` instead. Passing in an empty `selections` array to the `Select` would hide the chips from view (in multiple typeahead, while in single typeahead it would keep the input empty), but this would also hide the check marks that appear in the list alongside the selected options.
