### ISSUE TITLE
Selectable Table with Empty State issues

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3649]
**Describe the issue. What is the expected and unexpected behavior?**
Given that we have a selectable table with actions, it is not possible to display an empty state cell without something changing.

If we just provide `actions` and `onSelect` as normal, this is what we'd get.
![image](https://user-images.githubusercontent.com/6598829/73736695-86e7b580-4741-11ea-8770-75da4922ad85.png)

If we change `actions` and `onSelect` to `undefined`: 
* `onSelect` made `canSelectAll` to not be applied and thus the header changed.
* `actions` made us loose the last column and thus moved the headers to the right
![image](https://user-images.githubusercontent.com/6598829/73736932-f2318780-4741-11ea-877e-29984b4f3657.png)

Could we make it possible to provide Table with a prop to tell it that there's no data?

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**

**Comment by SpyTec** [comment]
Still an issue

**Comment by kmcfaul** [comment]
We have updated our Table demo with Empty State in the v4 merge that will resolve the checkbox/kebab showing up in the row (it moves the EmptyState component out of the cells, and visually looks the same). However, the actions column will still change widths because the header cell does not have any padding on its own, it is determined by the child cells' kebab menus. 

@mcoker Is it possible for a class to add the correct padding as to not change widths when data is added?

**Comment by kmcfaul** [comment]
@SpyTec I've talked with @mcoker about possible solutions for spacing of this column and it's not very clear cut because the actions cells may not be static. Additionally, the table will resize to fit the content so the header row is going to shift around already when data is first loaded in (accounting for long strings, etc). Can this issue be closed with the example update or is the shifting header row a blocker?

**Comment by SpyTec** [comment]
@kmcfaul I think this would be acceptable. Should I ever have any problems with the shifting header I'm sure it can be fixed in some other way.
