### ISSUE TITLE
Table: better handle white-space

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3670]
This is a placeholder for the work in https://github.com/patternfly/patternfly-next/issues/2205 and https://github.com/patternfly/patternfly-next/issues/2325 which may result in changes to the props we use to manipulate white space, word wrapping, etc.

**Comment by mcoker** [comment]
The core work for this is complete - https://github.com/patternfly/patternfly/pull/2965

cc @mattnolting

**Comment by nicolethoen** [comment]
@TheRealJon @seanforyou23 @redallen @tlabaj 

This issue adds 5 new modifiers (`.pf-m-truncate`, `.pf-m-wrap`, `.pf-m-no-wrap`, `.pf-m-break-word` and `.pf-m-fit-content`) which can be applied to `thead`, `tbody`, `tr`, `th`, `td` or `.pf-c-table__text`. 

I've added to `Table/utils/decorators/wrappable.ts` four new decorators (nowrap, truncate, breakWord, and fitContent). This allows me to add the 5 new modifiers to `td` or `th` elements via
 cellTransforms and transforms.

I'm wondering, when it comes to `thead` and `tbody` elements, if it'd be kosher to ask the user to provide the modifiers in the `className` prop for `TableHeader` and `TableBody`? I've tried adding a new prop to the `TableHeaderProps` and the `TableBodyProps` but I've totally gotten lost in the weeds of all the createElement calls so that I'm not sure I can expect the new props to propagate down correctly to the eventually rendered `thead` and `tbody` elements any other way. 

If using the actually pf modifiers in `className` is not an option, does anyone have any thoughts about applying modifiers to the `thead` and `tbody` elements?

**Comment by nicolethoen** [comment]
I don't think there is any other way to apply the modifiers to the `tr` elements - I am looking at the `Custom row wrapper` example and believe the consumer will need to manually apply the appropriate modifiers to the desired rows in their own `rowMapper`

**Comment by redallen** [comment]
I don't think it's kosher to ask for `className` on `TableHeader`. The currently supported way is to modify desired rows using a transformer. We could implement something like `className` for all rows which adds a transformer that gets merged in somewhere, but I think that's a complication we want to avoid.

**Comment by nicolethoen** [comment]
Yeah, I've got it working with transformers and cellTransformers which I think will serve most consumer needs. I just know the css was designed so that the new modifiers could also be applied to other table related elements like `thead` and `tbody` but the transformers don't modify those elements. So in a special case where the consumer actually does want the modifiers in those places, the only way I know how to do it now is by passing the modifiers to the `TableHeader` or `TableBody` components using `className`. To do it another way will involve jerry-rigging something for this rare case.
