### ISSUE TITLE
Divider: Update components that have their own divider to use the divider component instead

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3679]
We'll remove the component-specific dividers and update the examples to use the divider component

https://github.com/patternfly/patternfly-next/issues/2621

**Comment by mcoker** [comment]
The core work is complete - https://github.com/patternfly/patternfly/pull/2944

**Comment by evwilkin** [comment]
May be partially addressed in #4116

**Comment by nicolethoen** [comment]
@tlabaj 
I imagine we would want to introduce as few breaking changes as possible? And just change the definitions of DropdownSeparator and other components with their own separators so they render a Divider. Rather than removing the whole DropdownSeparator component and requiring consumers to replace all instances with a Divider component.

**Comment by nicolethoen** [comment]
@mcoker @tlabaj @mattnolting 

There is no implementation of a vertical divider variant. I don't need to make one in order to make the vertical dividers in the DataToolbar work, since the vertical separator is a variant of a DataToolbarItem. But I figure if people see them in the DataToolbar, they may want the variant to be accessible to them? 

I understand that the vertical Divider variant would always need to be placed in a Flex layout in order to work. That'd have to be documented in the example if implemented as part of addressing this issue. Unless there is still more work to be done or decisions to be made surrounding this on the core side?

**Comment by mcoker** [comment]
Hey @nicolethoen there is an issue to add support for the vertical variant here that hasn't been completed - https://github.com/patternfly/patternfly-react/issues/3736

> I understand that the vertical Divider variant would always need to be placed in a Flex layout in order to work.

That's one way. The divider either needs to have some sort of height established, or be the child of an element with a height. Here are a couple of examples - https://codepen.io/mcoker/pen/wvKqpzy 

 A flex layout assigns an intrinsic height by default so being the child of a flex layout works.
