### ISSUE TITLE
EmptyStateIcon should provide options to pick the right icon

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#3810]
The EmptyStateIcon icon prop accepts a string, but that doesn't really do anything `icon?: string | React.FunctionComponent<IconProps>`.

Looking at the design guidelines, we encourage a specific set of icons to be used https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/empty-state
We should provide an enum/a list of string literals to make it easy to pick one of these.

So perhaps instead of `string` it should accept an enum of supported react-icons, like `SearchIcon`

**Comment by nicolethoen** [comment]
@jschuler @redallen is there a way to limit which Icon components can be passed to the icon prop using typescript? I feel like the only way to do this is to update the documentation/comments. But I could be forgetting something obvious.

**Comment by redallen** [comment]
We could limit them to icons from `@patternfly/react-icons` by using the type:
```ts
import { SVGIconProps } from '@patternfly/react-icons';

icon?: React.ComponentClass<SVGIconProps>;
```

If we want to restrict consumers to specific icons that's not currently possible since we don't export named types for each icon. We could if we _really_ wanted to, though...

My preference is to be flexible with types, and specific with documentation:
```ts
/** Usually a TimesIcon or PlusIcon */
icon?: React.ComponentClass<any>;
```

**Comment by nicolethoen** [comment]
That's exactly what I was thinking.
