### ISSUE TITLE
Create dashboard to track issues, people, and PRs

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#3814]
cc: @dgutride @evwilkin

**Comment by dgutride** [comment]
(possibly move to rh-uxd org for tracking)

Need the following:
Summary of issues by team (team, count, average/max time to resolution, datepicker for filtering)
Count of issues by the team that opened them (will need to map github user -> team)
Number of days open
Number of days since last activity?

**Comment by redallen** [comment]
Creating a dashboard would require a serious time investment (1 week for a prototype?) and choosing a TSDB like Graphite. It could be used to explore many metrics over time.

I've gathered metrics grouped by team for open PRs on this doc per @dgutride 's suggestion: https://docs.google.com/spreadsheets/d/1pAm8Ibx9Jb0cuzNWgaUq6AP9pqx9ZR_AUaPtfb8zgmM/edit?usp=sharing

Closing for now. A new issue can be opened if we want to invest more into Github metrics.

cc: @janwright73
