### ISSUE TITLE
Rethink documentation for consuming PF4 react components with scss

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3815]
The [Patternfly documentation](https://www.patternfly.org/v4/get-started/developers#install) has some pointers regarding how an project can consume patternfly.
In [cockpit](https://github.com/cockpit-project/cockpit) we have decided to use Patternfly with scss (we need to make changes in pf-global-* vars and it's possible only through scss). However when importing a React component from react-core automatically the css files from react styles are included and not the scss.
There is clear documentation on how to disable default style injection and start comsuming scss files [here](https://github.com/patternfly/patternfly-react/wiki/Disabling-Style-Injection-with-Webpack).

Is there any better solution to this problem so that we can avoid having to maintain a list of components that we are using their stylesheets? 

A proper way to disable style injection would fix for us also https://github.com/patternfly/patternfly-react/issues/2919, which right now is a major issue for us.
Note: passing react-styles/css to null-loader as the link above suggests won't prevent emotion usage, which results in the inline style CDP issue.

**Comment by redallen** [comment]
Ah, you're in a tough spot @KKoukiou .

As for wanting to load SCSS instead of CSS, it's possible to alias `@patternfly/react-styles/css/**/*.css` imports to `@patternfly/patternfly/src/**/*.scss` with some clever webpack config. If you link me to your webpack config and provide steps to run a dev server I'd be happy to take a stab at getting that setup so you don't have to include ALL components like our base `patternfly.css` or `patternfly.scss` does.

You're still going to run into #2919 though since all our components `import { css } from '@patternfly/react-styles';` (where `css` is basically just a glorified `classnames`). React-styles requires emotion.js, which as a side-effect injects a single `<style>` tag into the `<head>` and causes [the CSP: style-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src) policy to be violated. In our next breaking change release we will remove emotion.

**Comment by redallen** [comment]
Hey @KKoukiou , we've removed emotion in our `prerelease-v4` branch, so that fix will land in master in about 3 weeks with our breaking change release.

How are you importing component SCSS in cockpit now, and what type of webpack config are you using? It may still be possible to alias `@patternfly/react-styles/css/**/*.css` imports to `@patternfly/patternfly/dist/**/*.scss` which would "avoid having to maintain a list of components that we are using their stylesheets."

**Comment by KKoukiou** [comment]
Hi @redallen, sorry for the delayed response.
Currently we allow React import the CSS files apart from some problematic ones - where we need to overwrite global variables.
For these we use null loader, and import them manually.

Here is the alias section in webpack config, if you have it easy I would love a suggestion on how to create the aliased css -> scss.
https://github.com/cockpit-project/cockpit/blob/master/webpack.config.js#L356

**Comment by redallen** [comment]
No problem @KKoukiou ! I'll take a look after our breaking change release is over.
