### ISSUE TITLE
Labels should be group-able like chip groups and link-able

### ISSUE THREAD

**Issue by AlexSCorey** [patternfly/patternfly-react#3829]
Chip Groups allow for grouping of chips.  I'd like the same features for labels, that allow group of labels, that also serve as links. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
Ansible Tower

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by marshmalien** [comment]
cc @trahman73

**Comment by jlmitch5** [comment]
After talking with the team, I think this might be a lot easier if we just add the ability for a Chip to be able to be wrapped in Link (or have the component prop), and then allowing a "primary" variant that styles the chip as a label.

It seems like the way the label component is described on the docs "Use a label when you want to highlight an element on a page to draw attention to it or make it more searchable." basically equates to "Emphasized Chip".  It's much easier in implementation for us to be able to use the same component, rather than have to have logic that conditionally handles usage of these two different types of components, depending on if the chip links or not.

**Comment by mcarrano** [comment]
We do have an open design issue here to look at the overall approach to chips, labels, and badges: https://github.com/patternfly/patternfly-design/issues/751 We will take this into consideration. @maryshak1996 FYI.

**Comment by mcarrano** [comment]
Note that the new Label component that is being introduced in our breaking change release will have linkable labels. As for Label Groups, I've opened a design issue here to add those to the library in a coming release: https://github.com/patternfly/patternfly-design/issues/845

**Comment by mcarrano** [comment]
Design work for this issue is currently in progress and it is on our roadmap, currently for the 2020.12 milestone. Related issue: https://github.com/patternfly/patternfly-design/issues/845
