### ISSUE TITLE
Wizard closes on "Enter" key press

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-react#3833]
**Describe the issue. What is the expected and unexpected behavior?**
We had a bug report that when a user was on the multi-step wizard, that the "enter" keypress would send them to the next step in the wizard. How it is now, if the user hits enter, the wizard closes.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. go to https://www.patternfly.org/v4/documentation/react/components/wizard/basic
2. click "show wizard"
3. hit enter on the keyboard

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

We're not going to worry about hacking it in all the wizard places

**What is your product and what release version are you targeting?**
Cloud Services

**Comment by boaz0** [comment]
It seems like when the wizard/modal is displayed the active element is the close button which explains the behavior you're describing here.

I guess we can add a prop to focus on a specific element. Does that sound good?

**Comment by seanforyou23** [comment]
I don't think this is a bug, pressing enter only closes the wizard because of the initially focused item being the close button as @boaz0 described (which so far has been intentional). If focus is not on the close button, pressing enter does not close the wizard.

Trying to think how to keep from overcomplicating this.. maybe we could consider simply focusing the entire wizard container by default instead of any button within? This way launching a wiz and immediately pressing enter will not dismiss, and users can still easily focus other wizard elements by simply tabbing further.

Thoughts?

**Comment by boaz0** [comment]
@seanforyou23 I see that `Modal` has a prop option to hide the close button and I think that's the easiest way to workaround this. However, I am not sure it's OK with the core team.

**Comment by ryelo** [comment]
I don't think we want to hide the close button, but I think our QE teams expected the initially focused item to be the "next" button.

**Comment by boaz0** [comment]
But what if next is disabled?

**Comment by seanforyou23** [comment]
Yea that's a good point and a common case, too. I was hoping there would be an `onOpen` props like there is `onClose`, this way users could explicitly control what receives focus on open beyond the default. Thoughts on this as a solution?
