### ISSUE TITLE
Tooltip doesn't show on disabled items

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3842]
**Describe the issue. What is the expected and unexpected behavior?**
When disabling a button, the tooltip will no longer show. This makes it difficult to describe what an icon will do or why the icon is disabled.

Lets say I have a Duplicate icon-button, but if there is nothing selected it will be disabled. Best way to tell the user why it's disabled is through a tooltip, alas it gets disabled

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/ecstatic-wave-wmvyn?fontsize=14&hidenavigation=1&theme=dark - CSS seems broken, though you can still see a tooltip popup

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
Telltale, RH internal

**Comment by michpetrov** [comment]
This is intentional, at least as far as HTML is concerned - a disabled element doesn't fire events. The tooltip triggers on `mouseover` and so it can't do anything with a disabled button.

I would assume there is a possible workaround by wrapping the button in something but from briefly testing this it breaks the appearance of the tooltip.

**Comment by SpyTec** [comment]
I see, makes sense. If there isn't a recommended way already I'll investigate trying to wrap the button in some manner
