### ISSUE TITLE
PageHeader doesn't render <Brand /> image

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#3853]
Hello I am trying to copy-paste code:
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-integration/demo-app-ts/src/components/AppHeader/AppHeader.tsx#L11

My code is:

`
      <PageHeader
            logo={<Brand src={ciBoardLogo} alt="CI Board"/>}
            logoComponent={Link}
            logoProps={logoProps}
            topNav={PageNav}
        />
`

But, the area is empty.

Only when I heavily reduce browser window in size it renders image in new line.

If I type `logo='some text'` browser shows text.

        "@patternfly/react-core": "^3.140.11",

**Comment by Andrei-Stepanov** [comment]
![bug](https://user-images.githubusercontent.com/12443962/75693317-0fa53300-5ca7-11ea-950c-73a42f40f07a.jpg)

**Comment by jschuler** [comment]
We have some page layout examples that use the Brand component for the icon. Perhaps this can help: https://patternfly-react.surge.sh/documentation/react/demos/pagelayout
Under the example is also a codesandbox link if you want to play with the example. (due to a bug, may have to reload the browser window within codesandbox to see the background image)

**Comment by jschuler** [comment]
If you have a reproducible example that demonstrates this issue on codesandbox for example, that would be helpful as well to see what the issue is!
