### ISSUE TITLE
Update alerts documentation to remove non-dismissable variations

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-react#3999]
https://www.patternfly.org/v4/documentation/react/components/alert

Toasts are always dismissable so we should not show variations without the close button.

**Comment by tlabaj** [comment]
cc @mcarrano @mcoker thoughts on this one.

**Comment by mcarrano** [comment]
@ajacobs21e @tlabaj IMO I would not remove these component variants. While the design guidelines state that toast alerts should always be dismissable, to me it does not hurt to have this flexibility. What do you think @mcoker ?

**Comment by mcoker** [comment]
Since the examples show the component capabilities, in general I think it's helpful to show examples of the variations the component supports. So unless the toast alert's close button is a required part of the component, I think having an example without it is helpful.

Currently only the title is required, so we show the most basic up to more complex examples of the alert usage. We do the same in the [core alert docs](https://www.patternfly.org/v4/documentation/core/components/alert).
