### ISSUE TITLE
Data table library for PF4 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#402]
This issue to work with @mcarrano about the direction for PF4 data table view and the required features and functionality. Design work is currently being tracked here: https://github.com/patternfly/patternfly-next/issues/199

Questions to answer: 
- Will we continue to use what seen in PF React today? If not, what are alternatives?
- Is there any customization required to achieve desired features and functionality?

**Comment by karelhala** [comment]
I love the new design of tables! It looks really interesting and easy to use.

As of the implementation I don't really like the idea of relying on other packages let alone on reactabular, it's fairly old and given the design it would be really hard to use and work with it.

For simple tables there is often used package called [react-table](https://github.com/react-tools/react-table), I would recommend it to be used for simple tables, header with sort and static pagination. However I don't think there is any package complex enough to cover our needs for custom rows which could be draggable, editable, sortable and collapsible. So I suggest writing our own implemtnation, I know that it might sound scary, but sorting, pagination and filter is rather easy because of ES6 functions. Drag and drop can be achieved with [react-dnd](https://react-dnd.github.io/react-dnd/), rendering custom rows/cells (including collapsible elements) is easy thanks to react (just pass HTML elements into body of PF table), inline edit can be achieved easy enough with react as well.

**Comment by priley86** [comment]
@karelhala thanks for the feedback...having worked on this a bit in the past, here is my thoughts...

I think we are essentially comparing two very similar APIs for building tables w/ React. I find the [reactabular](https://reactabular.js.org/#/) implementation quite simple to modify and fully featured. I do tend to agree that more HOCs could be provided to make the reactabular API easier on the consumer (still a TODO item), but it is quite flexible and can handle almost all use cases when packages are combined (and it is completely extendable). 

With react-table, you are getting a lot of additional things out of the box I feel (vs independently loading table features w/ separate packages/modules). While its API may seem easier to consume, for PF concerns, I think you will end up overriding virtually everything. The HTML markup it renders in all of the examples is not semantic (`div` vs `table`.. missing `aria` attributes, etc), custom css, etc. so in the end, I think you'll just end up completely customizing and reimplementing on top of that to meet PF guidelines...

For that reason, I still believe reactabular is a better choice for PF (you'll write smaller extensions on top of smaller independent packages). You mention wanting to write a lot of custom features, well reactabular is just a modular guide to doing that...I would almost be more inclined to just write a completely custom implementation then.

I'm definitely curious what other community members think, but that is my $.02 on this one. I am happy to help write more HOCs if it makes table consumption easier...

**Comment by LHinson** [comment]
Just wanted to give you the heads up of continued conversation over in the core repo - https://github.com/patternfly/patternfly-next/issues/199

**Comment by LHinson** [comment]
@karelhala does this address your concerns? As FYI, @mnolting is going to start on basic table styling over in core. https://github.com/patternfly/patternfly-next/issues/513

We've had success with reactabular with PF3, therefore would like to move forward with this solution for PF4 as well however, wanted to loop back around with you as well given you initial concern.

**Comment by martinpovolny** [comment]
@LHinson : I am pasting the questions from our email conversation that remained unanswered as you suggested.  Thx!

Do you (PF4) plan to use Rectabular for anything that is table-like?

Was there some test project/study on using Rectabular for something like what Karel Hala did? 

Is there some technical discussion on that that you had and I can read?

Are all PF4 contributors expected to use Rectabular for any tabular data?
