### ISSUE TITLE
Calendar icon should be FAR not FAS

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#4023]
**Describe the issue. What is the expected and unexpected behavior?**
Right now we offer a fa-calendar-alt icon in React that from FontAwesome but is using the solid style rather than regular. In the design kit and based on the PF icon recommendation updates that Brian has been working on (this issue: https://github.com/patternfly/patternfly-org/issues/1687), we have determined we want to use the far style. Would like to replace this with the regular style version!

See line 16 in ["Icon table - website format" tab here](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing) for the icon details

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement to the icon

**What is your product and what release version are you targeting?**
This will be relevant for all users:
1. Designers using the Sketch design kit (ensuring what they are using is consistent with what is in the code)
2. Developers building the icon font and consuming the icon font are using the recommended icon
3. Anyone looking at the PF website redesigned icon page will be told to use the far fa-calendar-alt so this will need to be provided correctly in our font.

@redallen is aware of the icon effort going on here!

**Comment by redallen** [comment]
I'll see if I can get this into `v4`.

**Comment by redallen** [comment]
After authoring #4073 I have some info on why FAR is not the default.

All reexported FAR icons are prefixed with `Outlined` in React, so the FAR Calendar icon is actually `OutlinedCalendarIcon`. We could make `CalendarIcon`=`OutlinedCalendarIcon`, but then what about the old FAB `CalendarIcon`?

Should the other FAR icons (from "Address book" -> "Window restore") be made default as well (and then maybe the old FABs prefixed with "Bold"? If so that's a fairly easy breaking change to make. Or do you just want the documentation to change to not include the FAB "Calendar" icon and instead only the FAR "Outlined calendar" icon?

**Comment by gdoyle1** [comment]
@redallen Ah thank you for pointing out the FAR icon! You don't need to make any changes - we can update the icon table to use "OutlinedCalendarAltIcon" as the React reference. Sorry about that
