### ISSUE TITLE
Charts: Upgrade react-charts to include performance pr from victory

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4119]
**Describe the issue. What is the expected and unexpected behavior?**
Request to upgrade victory charts to include: https://github.com/FormidableLabs/victory/pull/1494 into pf/react-charts. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by dlabrecq** [comment]
We have updated to victory@34.3.1 in our breaking change release (PatternFly v4). We cannot backport this to v3 because there are type changes in this major release.

See https://github.com/FormidableLabs/victory/pull/1481 & https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42436. 

Note that you can use the react-charts v4 pre-release, but there may be extra package dependencies installed.

"@patternfly/patternfly": "4.8.6",
"@patternfly/react-styles": "^4.2.0",
"@patternfly/react-tokens": "^4.3.0",

**Comment by jcaianirh** [comment]
@dlabrecq it looks like using the v4 pre release isn't only an extra package issue, but also victory type errors that are currently blocking this path. The only way around would be skiplibcheck workaround that is not desirable.

**Comment by dlabrecq** [comment]
The charts have been updated to use the types introduced by Victory. The package is available in PatternFly v4
