### ISSUE TITLE
Dropdown tooltip doesn't work when isDisabled

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#4124]
**Describe the issue. What is the expected and unexpected behavior?**

`tooltip` prop doesn't work on disabled dropdown item

![Peek 2020-04-24 11-50](https://user-images.githubusercontent.com/32869456/80199618-d55e6f00-8621-11ea-848a-44ec00e4642e.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

```jsx
import React from 'react';
import {
  Dropdown,
  DropdownToggle,
  DropdownItem,
  DropdownSeparator,
  DropdownPosition,
  DropdownDirection,
  KebabToggle
} from '@patternfly/react-core';
import { ThIcon, CaretDownIcon } from '@patternfly/react-icons';

class SimpleDropdown extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isOpen: false
    };
    this.onToggle = isOpen => {
      this.setState({
        isOpen
      });
    };
    this.onSelect = event => {
      this.setState({
        isOpen: !this.state.isOpen
      });
      this.onFocus();
    };
    this.onFocus = () => {
      const element = document.getElementById('toggle-id');
      element.focus();
    };
  }

  render() {
    const { isOpen } = this.state;
    const dropdownItems = [
      <DropdownItem key="link" tooltip="ahoj">normal</DropdownItem>,
      <DropdownItem key="link" isDisabled tooltip="ahoj">disabled</DropdownItem>,
    ];
    return (
      <Dropdown
        onSelect={this.onSelect}
        toggle={
          <DropdownToggle id="toggle-id" onToggle={this.onToggle} iconComponent={CaretDownIcon}>
            Dropdown
          </DropdownToggle>
        }
        isOpen={isOpen}
        dropdownItems={dropdownItems}
      />
    );
  }
}

```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

BUG.

**What is your product and what release version are you targeting?**
Sources. GA. ASAP.

**Comment by redallen** [comment]
## Solution
Hey @rvsia , this behavior is due to `isDisabled` adding the `pf-m-disabled` class which sets `pointer-events: none` on the `<a tabindex="-1" class="pf-c-dropdown__menu-item pf-m-disabled">disabled</a>`. If you override this with some CSS on your end to `pointer-events: auto; cursor: default;` it will show the tooltip like you desire. [Here's a working example.](https://codesandbox.io/s/affectionate-jones-7sjro)

## Why
Our `pf-m-disabled` class mimics what would happen if you set the `disabled` attribute on a button. As you can tell from [this codesandbox](https://codesandbox.io/s/nervous-rhodes-g9pmi), setting that attribute on a button disabled ALL pointer events, which includes the `onMouseOver` event that we use for adding tooltips with JS. The proper solution is to not rely on pointer events to show the tooltip by [using pure CSS](https://www.florin-pop.com/blog/2019/05/pure-css-tooltip/) (which PatternFly does not support), or to [wrap the disabled element in a div](https://stackoverflow.com/questions/18113937/fire-onmouseover-event-when-element-is-disabled) and apply the tooltip to the div instead.
