### ISSUE TITLE
Select without children is crashing

### ISSUE THREAD

**Issue by glekner** [patternfly/patternfly-react#4131]
**Describe the issue. What is the expected and unexpected behavior?**
Select of type `SelectVariant.typeaheadMulti` in the new version from 5 days ago is crashing without children even though the documentation says `children` is not a required prop.
We want to create an initial empty Select so the user can add multiple new values.

<img width="1009" alt="Screen Shot 2020-04-26 at 17 01 04" src="https://user-images.githubusercontent.com/24938324/80309800-ddfca400-87df-11ea-9c49-cbb162f7e7f3.png">
<img width="522" alt="Screen Shot 2020-04-26 at 17 02 54" src="https://user-images.githubusercontent.com/24938324/80309806-dfc66780-87df-11ea-8237-fc816e301ea8.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Create a `SelectVariant.typeaheadMulti` without `children`
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
2.71.5

**Comment by glekner** [comment]
<img width="909" alt="Screen Shot 2020-04-26 at 17 09 24" src="https://user-images.githubusercontent.com/24938324/80309937-b4904800-87e0-11ea-9b0c-cb5cab2079ed.png">

**Comment by redallen** [comment]
I'm unable to reproduce this by removing the children from any of our examples, but I think it might be because you're still passing an array of `selections`.  Can you fork this [codesandbox](https://codesandbox.io/s/7tejp) and reproduce your issue (note: the select's dropdown in the codesandbox didn't work for me in FF, but did in Chrome)? Then we can help debug further!
