### ISSUE TITLE
v4 Table expansion toggle no longer functions

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4168]
Table expansion toggle no longer functions with the latest v4 packages. It also defaults to the open position.

![chrome-capture (1)](https://user-images.githubusercontent.com/17481322/80821859-8d05fa80-8ba7-11ea-9069-f3b63009d51a.gif)

PatternFly v4 packages RC1:
<img width="409" alt="Screen Shot 2020-05-19 at 10 46 09 AM" src="https://user-images.githubusercontent.com/17481322/82342232-60334f00-99bf-11ea-9040-c0c48b46f9ac.png">

**Comment by mcoker** [comment]
The parent element for the icon with class `.pf-c-table__toggle-icon` needs to be a `div` instead of a `span`. I think this is what needs to change https://github.com/patternfly/patternfly-react/blob/688a4959f1f0e0b9735f646534fa8de75791e5a8/packages/react-table/src/components/Table/CollapseColumn.tsx#L32
