### ISSUE TITLE
avoid using cloneElement or improve documentation and types

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#4203]
**Describe the issue. What is the expected and unexpected behavior?**

This is a general issue across patternfly react but recently encountered an issue specifically with the use of `NavItem`.

The problem is that patternfly react uses `cloneElement` to inject props into children unknowing what kind of child that element may be. I can accept this if the typescript types were precisely typed to only accept children of certain types however in the case of `NavItem` it is `children?: React.ReactNode`.

If patternfly chooses to use this pattern, then the component API should be explicit of such.
Otherwise patternfly could move to more flexible pattern of using render props and give control back to the client to assign the given props correctly to the child components.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
OpenShift Console

**Comment by redallen** [comment]
We have 31 instances of `React.cloneElement` across 11 components and **all** but 1 are necessary to add classNames, ids, refs, or other attributes required to style and make child components function properly inside their parents.

I'd argue that `children?: React.ReactNode` is the correct type for most of these since most of the time the consumer _can_ pass any element they want. In the case of `NavItem`, yes, we really support passing [any React.ReactNode.](https://codesandbox.io/s/jovial-haze-o5ceg)

I think we need to take API design on a case-by-case basis. `BackgroundImage`'s `React.cloneElement(filter, { id: filterId })` probably isn't going to upset anyone, but `NavItem`'s:
```jsx
React.cloneElement(child, {
  onClick: (e: MouseEvent) => context.onSelect(e, groupId, itemId, to, preventDefault, onClick),
  className: css(styles.navLink, isActive && styles.modifiers.current, child.props && child.props.className),
  'aria-current': isActive ? 'page' : null
})
```
upsets people who want full control over the `className` passed to their child. Thankfully, there's only 2 cases where we override `className`: `InternalDropdownItem` and `NavItem`. `InternalDropdownItem` already supports not injecting `className` with the `customChild` prop. I think for non-abstract components like `NavItem` it makes more sense to have a `styleChildren?: boolean;` prop since you probably want the `onClick` and `aria-current` without having to change your JSX too much.

**Comment by christianvogt** [comment]
For `NavItem` in particular we don't know, without looking at source code, that props are injected. We got stung by this because we provided a `<React.Fragment` as a child.

Using `children?: React.ReactNode | (onClick, className, ...) => React.ReactNode` for components would allow the client to accept injection or manage it themselves. At the very least the documentation should describe which props are being injected.

**Comment by redallen** [comment]
Still need to add docs about injected props from `cloneElement`.

I'm not sure the best way to do this since some are nested in internal components and an API of `React.ReactNode | (prop1, prop2, prop3) => React.ReactNode` is difficult to support.
