### ISSUE TITLE
React-table: Table expandible header missing left padding with shrunk viewport width

### ISSUE THREAD

**Issue by leSamo** [patternfly/patternfly-react#4260]
Image taken from: [Patternfly documentation](https://www.patternfly.org/v4/documentation/react/components/table/collapsible)
![pf-table-2](https://user-images.githubusercontent.com/8426204/82196336-d8cfd800-98f9-11ea-86db-c7da8d84cd25.png)

**Describe the issue. What is the expected and unexpected behavior?**
Having expandible aligned to the first column and then shrinking the viewport width to toggle table item arrangement to on top of one another and then expanding expandible results in expandible header (identical to the column header it was aligned to) not having left padding.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. Use [example](https://www.patternfly.org/v4/documentation/react/components/table/collapsible) 
2. Shrink the viewport width to toggle item arrangement to on top of one another
3. Expand expandible on second row (the expandible there is aligned to first column)
4. Expandible header ("Header cell") is missing left padding

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Trivial bug.

**What is your product and what release version are you targeting?**
RH Insights, Vulnerability

Is there a way to remove the expandible header label and keep the alignment for full-width table, for the time being?

**Comment by mcoker** [comment]
@leSamo thanks for reporting this. Looks like this is a bug. The header text should never display inside of an expandable table row.

For the react dev that works on this, if you compare the [core table](https://www.patternfly.org/v4/documentation/core/components/table/expandable)  example to the [react table](https://www.patternfly.org/v4/documentation/react/components/table/collapsible), you'll see that in core, inside of any expandable table rows (`tr.pf-c-table__expandable-row`), the immediate children cells (`th` or `td`) do not have a `data-label` attribute, since the purpose of the cell is just to create a container for expandable content, and shouldn't be associated with the table column header text of any of the columns.
