### ISSUE TITLE
react-table cannot have column with name `id` / `ID`

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#4283]
Hello.

'@patternfly/react-table' cannot have column named with name: `id` / `ID`:

```
index.js:27 Warning: Encountered two children with the same key, `[object Object]-row`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in tbody (created by BodyWrapper)
    in BodyWrapper (created by BaseBody)
    in BaseBody (created by Context.Consumer)
    in Body (created by ContextBody)
    in ContextBody (created by Context.Consumer)
    in TableBody (created by SimpleTable)
    in table (created by Provider)
    in Provider (created by Table)
    in Table (created by Context.Consumer)
    in ComponentWithOuia (created by Context.Consumer)
    in Unknown (created by SimpleTable)
    in SimpleTable
```

It turned out that column cannot be named with `id`.

Reproducer: https://codesandbox.io/s/mystifying-diffie-e0b0t
That is a clone of the first official example: https://codesandbox.io/s/1h9p2 from : https://www.patternfly.org/v4/documentation/react/components/table

There is only 1 line change:

From:

```
        'Branches',
        { title: 'Pull requests' },
```

changed to:

```
        "Branches",
        { title: "Id" },
```

And in console (press F12) you will see messages: 

```
Encountered two children with the same key, `[object Object]-row`.
```

I spent 3 hours to understand the cause. Chance that a developer names column with name `id` / `ID` / `Id` is very high.

Version:  "@patternfly/react-table": "^2.28.47",

**Comment by karelhala** [comment]
@Andrei-Stepanov you can have columns with name ID, however you'll also have to pass `rowKey` to TableBody component. This is limitation of reacttabular component used to build the table itself. If you want to deep dive into how reactabular and setting `rowKey` works check out their documentation - https://reactabular.js.org/#/table/components
Since table is using reactabular you can write a lot of ehancer functions as well, I am wondering why there is no reference to the package in docs as that would prevent such questions in future @redallen .

**Comment by Andrei-Stepanov** [comment]
@karelhala thank you for the comment.
However: https://www.patternfly.org/v4/documentation/react/components/table   says:

rowKey | RowKeyType | No | 'id' | **This prop should not be set manually**

It would be good to have an example. Also, maybe updated the official doc? Thank you!

**Comment by karelhala** [comment]
@Andrei-Stepanov I wonder who put the `This prop should not be set manually` as it's not correct and should on other side describe the behavior, similiar to documentation on reactabular.

**Comment by redallen** [comment]
We probably depended on the behavior at some point and so that's why the `This prop should not be set manually` comment was left.

We should add an example for a column named "id" as that does seem like a rather common case.

**Comment by seanforyou23** [comment]
@karelhala is correct as far as I understand. I'm happy to add an example for this ([we've had it come up in the past](https://github.com/patternfly/patternfly-react/issues/3090)), but because it's an implementation type detail and wouldn't illustrate any specific behavioral interaction, the normal documentation example space maybe isn't a great place to house it.

I've been pushing for adding these types of examples to react-integration, although this project isn't published so users would currently have to run it in development mode to see. Any chance we could start publishing builds of react-integration so we can add examples of things like this without polluting the main doc example space?

@mcarrano @redallen this is what I was getting at in https://github.com/patternfly/patternfly-react/issues/3980 - just an idea! Let me know how I can help further.
