### ISSUE TITLE
Create demo to show use case of using page and skip to content outside of each other

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#4297]
**Describe the issue. What is the expected and unexpected behavior?**
This [PR](https://github.com/patternfly/patternfly-react/pull/2519) added the ability to send proper focus from the skip to content component to the main container of our page component. However, if the consumer doesn't pass an id in this context, it will not work as expected so it was requested to make the id required when a breaking change was available.

In the case that a user mixes and matches components (i.e. perhaps uses our page component but uses their own custom skip to content component), making the prop required could lead to a case where someone is having to set that value even though they aren't using it. 

There was discussion to keep it optional to allow for flexibility so if the prop isn't required, we should build a demo (perhaps in react-integration) to showcase the potential use case of someone using these components outside of each other.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

cc @seanforyou23

**Comment by seanforyou23** [comment]
`SkipToContent` uses a named anchor to point to the main container of the Page component via `mainContainerId`. This prop was initially added as [optional](https://github.com/patternfly/patternfly-react/pull/2519/files#diff-5e85f596cb829546545fff5ed5b1c364R28), then changed to [required](https://github.com/patternfly/patternfly-react/pull/3904/files#diff-72a98c6cde8b853417019d7a3d558a21R30), but somehow it's still [optional on master](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Page/Page.tsx#L30). I think optional is correct, @jessiehuff is that in line with what you're thinking? I'm not sure exactly what to test since SkipToContent and `<main>` element are both generated from Page. Happy to help with this, but just unsure I know exactly what to build and what aspect of user experience the test is supposed to verify.

I wonder whatever happened to commit #72a98? I think this commit being lost has something to do with the confusion.

**Comment by seanforyou23** [comment]
I think I maybe confused things in https://github.com/patternfly/patternfly-react/pull/2519 when I mentioned

> If users don't supply a mainContainerId then things will not work as expected.

Not quite that cut and dry. It's not that it won't work as expected, it just won't if the user also provided a SkipToContent and they are not also adding a DOM element with that ID inside the Page component somewhere. In any case, the [pagelayout](https://www.patternfly.org/v4/documentation/react/demos/pagelayout) demos correctly wire up the SkipToContent and mainContainerId and show it well by using a same variable as the value for each, so I think we're good? Can we just close this issue?

**Comment by jessiehuff** [comment]
So from my memory, there was discussion on making `mainContainerId` required [here](https://github.com/patternfly/patternfly-react/pull/2519) because of the concerns about certain scenarios where a user wouldn't provide a `mainContainerId` but were providing a SkipToContent and aren't also adding a DOM element with that ID inside the Page component somewhere. This was addressed during our breaking change release and when we were merging v4 into master, someone mentioned that they didn't think it made sense in case users weren't using these components and this id would just be extra (I assume in a case where they're not using our skip to content component, though ideally they'd be using their own since it's important for accessibility). This demo was the idea for compromise, but I think it's ok to close if there's not a super clear path forward on it.
