### ISSUE TITLE
Table: Rendering issues of virtualized table causing performance and display issues in OpenShift 

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4311]
**Describe the issue. What is the expected and unexpected behavior?**
Specifically, pf4 tables vs pf3 tables scrolling is noticeably degraded. The PF4 table scrolling is choppy and jumpy by comparison. 

This issue is reproducible with the Patternfly sample paes. The scrolling is re-rendering rows on every pixel movement. (See the screenshot attached) This re render did not occur on pf3 tables.

**Display of rerender of every row on scroll:**
![virtualscroller](https://user-images.githubusercontent.com/35978579/83284533-c6cc2000-a1aa-11ea-93dc-b003f643d6c4.gif)

**Display of render issue on filter**
![render-issue](https://user-images.githubusercontent.com/35978579/83285132-be281980-a1ab-11ea-8b3b-914eaa44b53f.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? 
Openshift Bugs related: https://issues.redhat.com/browse/CONSOLE-1532
https://bugzilla.redhat.com/show_bug.cgi?id=1819752
https://bugzilla.redhat.com/show_bug.cgi?id=1795305
https://bugzilla.redhat.com/show_bug.cgi?id=1805918
cc: @janwright73

**Comment by kmcfaul** [comment]
Re: the re-rendering, both pf3 and pf4 source their virtualized scrolling from the `react-virtualized` library with minor changes in pf4's [copy](https://github.com/patternfly/patternfly-react/pull/2011) that shouldn't impact performance. The examples in the docs have a small overscan index of 2 so that could be why they update more often. It is possible the difference lies in Table, so I am continuing to investigate.

Re: the filtering bug, I have not been able to reproduce this behavior so far after adding a filterable table demo to the virtualized docs (can be looked at in this [WIP PR](https://github.com/patternfly/patternfly-react/pull/4389) with [surge](https://patternfly-react-pr-4389.surge.sh/documentation/react/extensions/virtualizedtable#filterable)). Are you getting any console errors/warnings when the white space appears?

**Comment by jcaianirh** [comment]
@kmcfaul with the filtering issue: no console errors or warnings when this occurs. But one other clue, is that subsequent scrolling on the page rerenders the component correctly, and the blank space is removed.

**Comment by tlabaj** [comment]
closed by #4389
