### ISSUE TITLE
Table: Cannot assign to read only property 'isFirstVisible' of object '[object Object]'

### ISSUE THREAD

**Issue by rabajaj0509** [patternfly/patternfly-react#4313]
**Describe the issue. What is the expected and unexpected behavior?**
I think when we pass an array of objects as props it tries to mutate the array and throws an error: 
```
Uncaught TypeError: Cannot assign to read only property 'isFirstVisible' of object '[object Object]'
    at flagVisibility (Body.js:24)
    at ContextBody.render (Body.js:105)
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Yeah, there was a workaround, I used the `asMutable()` function to get over it but i doint think that is a good practise therefore I am looking forward to fixing this. 

Since I am a first time contributor, it might take me a little more time to fix it :)

**Comment by seanforyou23** [comment]
Discussed in PF slack and we found that the Table rows/column definition was fine, but it was being generated in part by a JSON.stringify() statement which wrapped the resulting array in quotes, which lead to the error mentioned in the issue. Just needed to rebuild the rows structure as an actual array instead of a stringified array and it works like a charm. I think we can safely close the issue, @rabajaj0509 feel free to reopen if we missed anything!
