### ISSUE TITLE
Tooltip: should use the `pf-c-tooltip__arrow` class for the tooltip arrow

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#4359]
When using the Tooltip from the React component the produced html is not the same as the html for the tooltip advertised in the documentation.

Specifically, the html code when the React component is used looks like this:

``` html
<div class="tippy-tooltip pf-tooltip-theme pf-c-tooltip" id="tippy-20" data-state="visible" tabindex="-1" data-arrow="" data-animation="fade" style="max-width: 18.75rem; top: -15px; left: 0px; transition-duration: 300ms;" role="tooltip" data-placement="top">
  <div class="tippy-arrow" style="left: 137px;"></div>
  <div class="tippy-content" data-state="visible" style="transition-duration: 300ms;"><div>
   <div class="" role="tooltip" id="">
     <div class="pf-c-tooltip__content">
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id feugiat augue, nec fringilla turpis.
        </div>
      </div>
    </div>
  </div>
</div>
</div>
```
Note that there is not `pf-c-tooltip__arrow` class used for the tooltip arrow as advertised in the [html documentation for the tooltip.](https://www.patternfly.org/v4/documentation/core/components/tooltip)

Also there are some extra div wrapper in the React component, and tippy-arrow, tippy-content classes are not documented.

**Comment by jschuler** [comment]
We use tippy.js to position the tooltip/popover/dropdown menu relative to the triggering element. It also lets as append the element to the document body so that it is not constrained by the element flow. 

The outer divs are produced by tippy, and so what was done here was to style tippy's arrow to match the pf-core arrow. I do agree that it would be great if the produced DOM matched the core DOM closer and that the arrow div had the `pf-c-tooltip__arrow` class applied, perhaps there is a way to change the output to achieve that (https://github.com/atomiks/tippyjs-react/issues/84#issuecomment-500675007).

**Comment by jschuler** [comment]
I'll explore if the produced DOM can be improved
