### ISSUE TITLE
Look into accessibility issues

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4365]

**Comment by seanforyou23** [comment]
What happens here? Seems more `accessibility` related and less `infrastructure`?

**Comment by evwilkin** [comment]
@redallen @jessiehuff we set this up based on outstanding accessibility issues, I believe as a placeholder for the follow-up issues needed related to the aXe upgrade throwing new errors. Are those being worked on elsewhere, or do those issues still need to be created?

**Comment by redallen** [comment]
Once we've stabilized the `patternfly-a11y` script in core and fixed all its errors we can upgrade React to also use the new version, which is what I believe this issue is about.

I have a few open PRs in core related to this:
- https://github.com/patternfly/patternfly/pull/3233 (has complications)
- https://github.com/patternfly/patternfly/pull/3236

**Comment by redallen** [comment]
Closed in #4879
