### ISSUE TITLE
NavExpandable should be a button and not a link

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#4377]
**Describe the issue. What is the expected and unexpected behavior?**
`NavExpandable` results in a link with `href="#"`.  Since this item is not linkable and will always have an `href` value `#`, it should not be a link.

Expected behavior to be similar to `ExpandableSection` which uses a `button`.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See example https://www.patternfly.org/v4/documentation/react/components/nav#expandable

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bugish?

**What is your product and what release version are you targeting?**
OpenShift Console 4.6

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
cc @jessiehuff do you have a recommendation?

**Comment by jessiehuff** [comment]
So I was looking into this, and it sounds like the original reasoning behind making it a link was to allow for quick access to the navigation for screen reader users by keeping those links together (aka accessing this collection of links through the link menu). However, there are other ways an SR user could navigate to it such as landmark or form controls so I think it would be good to change it to a button since `href="#"` isn't very useful or semantic. Here is an [example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-navigation.html) that supports using buttons. When talking to Jenn, she also brought up another option where an element expands a section: https://www.bbc.com/ which was something she considered at the time of implementation, but handling focus should be considered with this pattern. This pattern also isn't documented, and there isn't any documentation or research articles that we've found that suggest having a mix of buttons and links in the nav region would be problematic. So I think it sounds like the best solution might be to change it to a button as suggested.

**Comment by mcoker** [comment]
Opened a core issue to update our examples - https://github.com/patternfly/patternfly/issues/3212
