### ISSUE TITLE
Add Typescript defintions

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#44]
* add Typescript type definitions into the `patternfly-react` distributions (so that custom type definition is not needed in PF React Demo App)

**Comment by priley86** [comment]
I believe we voted against maintaining these definitions in PatternFly React b/c it would be too much of a burden at this point. Will leave this open for future though...

**Comment by ia3andy** [comment]
Hi @priley86,

Using patternfly-react and react with typescript without the definition makes it complicated to use. IMO, either the documentation should be really complete with details of the components and how to use them or have this definition to give auto-complete. 

For example, I always have to browser the source to find component props.

Using react with typescript is pretty common.

Maybe the problem is that the Storybook is not enough as a documentation to really have the component definition.

Cheers,
