### ISSUE TITLE
TextInput setting a default value for the type date is prohibited.

### ISSUE THREAD

**Issue by klu17** [patternfly/patternfly-react#4440]
**Describe the issue. What is the expected and unexpected behavior?**
 As a user, I want to set a value for the `value` prop for TextInput to a default value like '01/05/2020'.
However, when the `type` prop set to 'date', the `value` prop does not replace 'mm/dd/yyyy'. When the `type` prop is 'string',
the `value` is displayed but the features that I expect from the date type are not available.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/recursing-sutherland-fnlts?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug. It is blocking me.
**What is your product and what release version are you targeting?**
The next release. I am writing this as of 2020.07 release for PatternFly 3.

**Comment by redallen** [comment]
`<TextInput>` is really just an `<input>` under the hood. Your problem is a format of "mm/dd/yyyy" is not allowed [without additional configuration.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) You can try `value={"1000-01-05"}` instead ([codesandbox](https://codesandbox.io/s/sleepy-leftpad-bq03v?file=/index.js:693-703)).
