### ISSUE TITLE
Spike(virtualized table): Determine baseline performance expectations

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4453]
Related to #4322 

The ask for this issue is to explore similar solutions to the virtualized table extension and determine what baseline performance requirements the virtualized table should meet.  Ideally this would include something along the lines of "for a table with 1000 rows and 10 actions per row, the table is expected to render in _x_ seconds and have a response time to user interaction of _x_".

This can guide the efforts to improve performance and give a standard to maintain with this component.

**Comment by redallen** [comment]
## Intro
It's difficult to give such measurements since browsers and hardware vary greatly. During testing, my own browser extensions played a role in benchmarks. How rendering is measured can also vary (do we count the time it takes to load scripts? do we count the time it takes to transpile the example on the docs site when consumers likely won't do that? do we use a tool like react-dev-tools to estimate how long a component takes to render without accounting for real-world issues like scroll debouncing?).

## Testing
### Initial load
On my machine on a production docs build it takes 1.452s from page load until the table is fully rendered:
![image](https://user-images.githubusercontent.com/47335686/94461700-7a104a00-0188-11eb-9ebb-8fe922c0fbe3.png)

For comparison button takes 754ms:
![image](https://user-images.githubusercontent.com/47335686/94461781-97451880-0188-11eb-8eeb-503548668dfd.png)

These aren't fair product benchmarks since the docs site asynchronously loads these examples and then uses acorn to transpile it (so the _length_ of the example matters). It's a decent estimate, though.

I put together a more fair comparison by serving a simple webpack app. It takes 400ms until the table is fully rendered:
![image](https://user-images.githubusercontent.com/47335686/94463519-13d8f680-018b-11eb-8876-fe9601ff213d.png)

Going from 100 to 10,000 rows still takes 400ms:
![image](https://user-images.githubusercontent.com/47335686/94463729-66b2ae00-018b-11eb-95d5-7033a73805b7.png)

For comparison button takes 332ms:
![image](https://user-images.githubusercontent.com/47335686/94462998-4d5d3200-018a-11eb-95a1-a197ba84ee44.png)

### Scrolling
Another measure of performance are `onScroll` events which take 7.6ms each:
![image](https://user-images.githubusercontent.com/47335686/94464060-eb9dc780-018b-11eb-99ed-d2bbb1cd1e39.png)

## Conclusions
In simple cases our virtualized table takes 68ms longer to load than a button. In more complex layouts this difference can be up to 700ms longer. I think the current primary performance bottleneck is the forced layout reflows used to calculate cell width/height. These take ~9ms total in the simple webpack app, but ~273ms on our docs site. I think we could assume a fixed height and look to enhance [these lines](https://github.com/bvaughn/react-virtualized/blob/dc9e2dd4fb942f8d62cc790912096880b7ce0e2b/source/CellMeasurer/CellMeasurer.js#L86) upstream in react-virtualized.

Another thing that may help scrolling is batching removing/adding DOM nodes. Currently a lot of time is spent removing/adding individual nodes.

**Comment by tlabaj** [comment]
cc @dgutride
