### ISSUE TITLE
Select shows incorrect checked value

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4478]
The `SelectOptionObject` now displays the checked items in the toolbar, but shows the wrong total checked items. In the example below, only one item has been selected, but the `Select` component shows 9 as the total checked count.

See https://github.com/patternfly/patternfly-react/pull/4469

<img width="501" alt="Screen Shot 2020-07-06 at 1 52 53 PM" src="https://user-images.githubusercontent.com/17481322/86623777-2084ee80-bf90-11ea-97fb-8b7d9205c321.png">

cc @kmcfaul

**Comment by dlabrecq** [comment]
I suspect this is an issue with `compareTo` function?  We're localizing labels, so we must work from IDs.

<img width="599" alt="Screen Shot 2020-07-06 at 2 06 43 PM" src="https://user-images.githubusercontent.com/17481322/86624804-f59b9a00-bf91-11ea-9a4e-ba7e40182d02.png">

**Comment by dlabrecq** [comment]
Note that if I don't use the same `SelectOptionsObject` for the `selections` prop, I get the following error.

<img width="843" alt="Screen Shot 2020-07-06 at 2 19 26 PM" src="https://user-images.githubusercontent.com/17481322/86625896-e0276f80-bf93-11ea-9269-43e7fc80ec04.png">

**Comment by kmcfaul** [comment]
The code currently expects either strings or SelectOptionObjects, not a mixture of types. 

For the incorrect chip count, you are passing the entire options array to `selections`, which should consist only of the checked options. `compareTo` is used to compare options between `selections` and `children` to determine if they should be marked as selected/checked (if they do match and compareTo returns true). It informs how two SelectOptionObjects should be compared together, rather than as a way to mark options as checked.

**Comment by dlabrecq** [comment]
Yup, I understand the need to prune the list of selections. I didn't expect that the code needed to be the same type. Previous to this change, I was using different types.

**Comment by kmcfaul** [comment]
Before the selections prop only really supported strings (SelectOptionObjects weren't considered for comparison), so that makes sense.

**Comment by dlabrecq** [comment]
Yea, I just started using the `compareTo`. Thanks for clarifying how this works
