### ISSUE TITLE
Code snippet/editor proof of concept

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4514]
Want to create a POC demo of a code editor component that integrates the Monaco editor (https://microsoft.github.io/monaco-editor/). Preliminary designs can be found here: https://marvelapp.com/prototype/b284chd  Want to understand how close we can get to this design and if there are other constraints or risks involved with this approach. Please consult with @gdoyle on any design questions.

cc @tlabaj @evwilkin

**Comment by gdoyle1** [comment]
From a design perspective, our ideal `code snippet` option would be to go with Variation 1 (where the actions are above the editor)! We would still need the `inline` variation as well for code snippets that are inline with paragraph text. Will be available to further discuss when this issue is taken on!

**Comment by nicolethoen** [comment]
Demo lives at [http://nicolethoen.surge.sh](http://nicolethoen.surge.sh)

**Comment by nicolethoen** [comment]
Code for POC lives at https://github.com/nicolethoen/monaco-poc
