### ISSUE TITLE
FormGroup:  Clean up use of helper text

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4552]
**Describe the issue. What is the expected and unexpected behavior?**
There are multiple props for helper text and helper text icons. There is duplicate code based on these props where the only difference is the modifier applied. Let's clean this API up and and have one prop for `helperText` and one prop for `helpertTextIcon`. We can update the examples to illustrate how to switch between error, warning and success.

related core issue
https://github.com/patternfly/patternfly/issues/5156

**Comment by tlabaj** [comment]
May depend on core issue  [#5156](https://github.com/patternfly/patternfly/issues/5156)

**Comment by mcoker** [comment]
This can begin without the core work. The form helper text element is just a container for the `<HelperText>` component now, so we'll just remove any customization this takes to format the text and use `<HelperText>` in the container instead.

https://github.com/patternfly/patternfly-react/blob/v5/packages/react-core/src/components/Form/FormHelperText.tsx

* remove `isError`
* `isHidden` - what's this for?
* remove `icon`
* IMO we should remove `component` and use a `<div>` since it's just a container
