### ISSUE TITLE
Table Demo: Sticky Header Table demo returns a 404

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4605]
**Describe the issue. What is the expected and unexpected behavior?**
When navigating to the pf react table sticky header demo here:

https://patternfly-react.surge.sh/documentation/react/demos/stickyheadertable/untitled-example

I get a 404 error.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

see above link
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug
**What is your product and what release version are you targeting?**

**Comment by MariaAga** [comment]
When navigating from the side menu to the demo the link leads to https://patternfly-react.surge.sh/documentation/react/demos/stickyheadertable for me, and the link to the first example leads to https://patternfly-react.surge.sh/documentation/react/demos/stickyheadertable#untitled-example
and both work.
How did you receive the link in this issue?

**Comment by evwilkin** [comment]
@jcaianirh just FYI in the meantime the demo is located here: https://patternfly-react.surge.sh/documentation/react/demos/stickyheadertable/basic

It looks like the demo full page URL is pulling from "untitled example" rather than "Basic", which still needs to be resolved.  @MariaAga the link for this issue is when either clicking the table image or the "open in a new window" icon just below the image to view the full page demo.

**Comment by jcaianirh** [comment]
@MariaAga i just went to the pf-react github page and clicked surge link at the top of the page. (in the about section)
![Screen Shot 2020-07-23 at 11 23 26 AM](https://user-images.githubusercontent.com/35978579/88305378-6a334000-ccd7-11ea-90f7-4df816fa8c9b.png)
