### ISSUE TITLE
Clicking on Dropdown item closes Popover

### ISSUE THREAD

**Issue by rawagner** [patternfly/patternfly-react#4698]
**Describe the issue. What is the expected and unexpected behavior?**
Clicking on dropdown item in Popover causes Popover to close.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/romantic-chatterjee-ynhmp

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, blocking OpenShift 4.6 https://bugzilla.redhat.com/show_bug.cgi?id=1862885

**What is your product and what release version are you targeting?**
OpenShift 4.6

**Comment by DaoDaoNoCode** [comment]
@rawagner Hi, I check this problem. Could you please use `Select` component to replace the `Dropdown` component in OpenShift? Based on your description, I think it performs more like a `Select` menu. Actually when you use `Dropdown` it should close the Popover because the items in it is much more like link or action buttons, but not only change the status. So would you mind trying to use `Select` instead? Please let me know if there are any other questions!

**Comment by rawagner** [comment]
@DaoDaoNoCode I tried `Select` but it still closes the popover. Updated the CodeSandbox.
FIY Dropdown in Popover worked at some point but doesnt in recet PF versions

**Comment by DaoDaoNoCode** [comment]
@rawagner Could you directly pass the `Select` component into `footerContent` prop in `Popover` like the code here? https://codesandbox.io/s/dry-waterfall-uw25z?fontsize=14&hidenavigation=1&theme=dark
But do not create a component for `Select`, this is a way to fix it temporarily, I am doing more research to see if we can get rid of it in PatternFly.

**Comment by DaoDaoNoCode** [comment]
And thanks @jschuler . There are multiple ways to temporarily fix your problem without directly passing the `Select` component into `footerContent`.

1. https://codesandbox.io/s/async-moon-il7d3?fontsize=14&hidenavigation=1&theme=dark. It only adds a `setTimeout` function to `onSelect` function in the `SingleSelectInput` component. We guess it may because of the render order in React that causes this problem so a timeout is useful to solve this problem.
2. https://codesandbox.io/s/async-snow-bp3ih?fontsize=14&hidenavigation=1&theme=dark. Another way is to add `event.stopPropagation` and `event.nativeEvent.stopImmediatePropagation` to `onSelect` function, which will prevent the popover from calling the listener to check whether click outside it when we click on the dropdown menu items, thus it will not close the popover.

**Comment by rawagner** [comment]
@DaoDaoNoCode @jschuler  thanks, I've opted for option #2. Works fine!
