### ISSUE TITLE
Code editor component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4795]
Introduce the Code snippet component per https://github.com/patternfly/patternfly/issues/3419

Design: https://marvelapp.com/prototype/b284chd/screen/70964526

@jessiehuff to provide input keyboard interaction. Reference this OS issue for more background: https://issues.redhat.com/browse/PD-598

**Comment by jessiehuff** [comment]
It looks like there's currently a common practice among some code editors, Monaco included, that do something called "[Tab Trapping](https://github.com/microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide#tab-trapping)". As you're tabbing, you become trapped in the code editor, and while there is a way out, it's not easily discoverable. (You can toggle the trapping of Tab with Ctrl+M on Windows and Linux and with Ctrl+Shift+M on OSX, and subsequent Tab keys will move focus out of the editor.) 

Depending on what we're capable of doing here, I think we should either:
- Consider a new interaction pattern: an idea I think we could follow is that you would tab through the page, focus goes to the editor itself (as opposed to immediately entering the editor), and you would press enter to interact with it. Then, similar to other interaction patterns like a modal or dropdown, pressing Esc would exit the inside of the editor and put focus back on the entire editor/outer div. This appears to me to be a little more intuitive, but that's up to debate as most interactions can be. I couldn't easily find a standard for code editors specifically, but I will continue to research this.
- Make the instructions on how to leave the editor significantly clearer and nearly require products to provide this documentation to users. Otherwise, it would appear to completely violate WCAG 2.1.2 [No Keyboard Trap](https://www.w3.org/WAI/WCAG21/quickref/#no-keyboard-trap) which would likely negatively affect products if they ever go to create a VPAT.

**Comment by nicolethoen** [comment]
- forward ref to editor, maybe editordidmount function
- prop to hide language
- auto fill parent container
- configure style?
- toggle padding?
- does monaco need to know the language to read the file type? does the uploaded file need to be the right extension?
