### ISSUE TITLE
Tree view: add capability for an "expand/collapse all" toggle

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4797]
**Describe the issue. What is the expected and unexpected behavior?**

Currently, the expanded state of a subtree is handled internally in a `useState` hook in `TreeViewListItem.tsx`. We are trying to add a toggle button to expand/collapse everything in the tree, but we can't control that state from outside the component.

I propose a new prop `allExpanded` that is passed down the tree similarly to `defaultAllExpanded`, and if it is defined its value is used instead of the internal expanded state. a `null/undefined` value would allow the internal state to work, a `true` value would force the entire tree to expand, and a `false` value could force the entire tree to collapse. When the user clicks one of the toggles in the tree itself, it could be set to `null` again so that the internal state kicks back in.

Maybe instead of an external prop, that `allExpanded` behavior could be handled internally at the top level, and a button could be shown to the left of the search bar (or in place of it if search is disabled) if a `showExpandAll` boolean is passed. Maybe that would be better, to keep it consistent with the existing internal state.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Observable in the workspace examples.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement / nice to have.

**What is your product and what release version are you targeting?**

https://github.com/konveyor/virt-ui (Red Hat Migration Toolkit for Virtualization), no particular release target.

cc @kmcfaul

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@mturley I understand how this can be useful, but I'm not sure what makes the most sense for the placement of the expand/collapse all button. Seems like you are suggested that this be integrated with the component vs being something that lives outside and passes state via a prop? So lives in the same space as the search box? I guess it depends on the context, ie., whether there is a view with a toolbar, for example. @doruskova any thoughts?

**Comment by mturley** [comment]
I think I was imagining that either it's not part of the component and the search box is also not part of it / something handled externally, or both are handled by the component, so that the consumer has the option of putting things next to the search bar arbitrarily if needed. I think @vconzola had other things he wanted to be able to put there, like a refresh button, etc.

**Comment by doruskova** [comment]
@mcarrano Adding some mocks for it. https://marvelapp.com/prototype/8cdg211/screen/73007897
It's usually placed to the right top and I'd use text version when you have just one action, but if you want to put there refresh button, etc. then we need icons.

**Comment by mcarrano** [comment]
@mturley What you are saying makes sense. I just want to make sure we approach this in a way that provides a general purpose path for any type of menu. This does not seem like a unique problem for trees. We currently have an open PR to add actions into a Context Select menu via adding a footer for example. (https://github.com/patternfly/patternfly/pull/3494) It may be that we would enable any menu to have an optional header or footer like this. I don't know.

@mcoker would like to get your input here. What would be the best way to approach this so that we avoid continuing to do one-off solutions that are very localized to particular components?

**Comment by mturley** [comment]
Makes sense. The scope of this particular issue should probably be limited to the ability to pass that expanded/collapsed state in via props, since that would allow the consumer to add their own expand/collapse control anywhere they need to, including in whatever general purpose toolbar comes later.

**Comment by mturley** [comment]
@mcarrano @mcoker do you know if this has been addressed on the design/core side?

**Comment by mcarrano** [comment]
@mturley No nothing has happened with this since the earlier conversation. From a design standpoint, I think what @doruskova put together makes sense, but we have not done further work. As I re-read this, there seem to be two potential options: 

1) make the toolbar/header area flexible to pass in anything you want including a search input, actions, or anything that makes sense. @tlabaj this would be similar to how we are handling dual list selector and the new composable  menu component. Is that something we can add here?

2) We could just add the prop and let the action be controlled external to the component.

What fits better with your needs @mturley ?

**Comment by mturley** [comment]
I like the more flexible idea of just being able to put whatever you want in that header bar, especially since it'll be easier to implement. But it would be nice to also have a prop later on.

**Comment by mcarrano** [comment]
@tlabaj do you see any issues with this? If not, I will get this on our roadmap. Thanks.

**Comment by tlabaj** [comment]
I think even if we allow the flexibility of adding whatever in the header, we still need a prop for the expand/collapse all state so the consumer can control that via whatever the put in the header.
