### ISSUE TITLE
Adding content boxes [enhancement issue]

### ISSUE THREAD

**Issue by AdityaSharma911** [patternfly/patternfly-react#4924]
The main page of this website **looks empty** and has a sidebar for various options. 

![website now](https://user-images.githubusercontent.com/55270982/94839972-5f163200-0435-11eb-87e5-706f84320354.JPG)

This can be made **visually better and easily approachable by** **adding content boxes** as shown below:  

![qwiklabs](https://user-images.githubusercontent.com/55270982/94840164-a3093700-0435-11eb-9e4a-3d3e2c6655e4.JPG)

These content boxes can be anchored to the various items available in the sidebar. And as soon as the user clicks on a box let's say 'charts' then the collapsible sidebar just with the options related to  charts opens up and links to various other options such as   'Get Started', 'demos' etc. occur simultaneously.

**Comment by tlabaj** [comment]
cc @rachael-phillips @redallen @mcarrano

**Comment by AdityaSharma911** [comment]
Thanks mam, for referring my PR for review by other contributors : )

**Comment by redallen** [comment]
We expect most people to use https://www.patternfly.org. We've never had a design of the homepages for https://patternfly-react.surge.sh and https://pf4.patternfly.org because these sites are just for our developers who know their way around.

Our developers just need to know if they're in a PR (like https://patternfly-react-pr-5032.surge.sh/) or the master branch (https://patternfly-react.surge.sh/) based on the homepage and nav, and I think the current implementation does that well. I'm not sure about your context boxes design since I don't know where they would link to.

**Comment by AdityaSharma911** [comment]
Oh, alright that makes sense. Thank you for addressing this issue : )
