### ISSUE TITLE
Wizard: add prop for rendering with className="pf-c-page__main-wizard"

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4937]
Replacement for https://github.com/patternfly/patternfly/issues/3546, see more detail there.

We should add a boolean prop to `<Wizard>` to enable the `pf-c-page__main-wizard` CSS class, for wizards that are the main element on a page. Maybe `isPageMain` or something, although I'm not sure if there's a better name.

**Comment by mturley** [comment]
cc @mcoker

**Comment by DaoDaoNoCode** [comment]
@mcoker Could you take a look at this https://www.patternfly.org/v4/components/page/html#main-section-variations? I am still not sure whether we need `.pf-c-page__main-wizard` or not. If we want to make it consistent with tertiary navigation or breadcrumbs, the best way is to add a prop to `Page` named `wizard` like `tertiaryNav` and `breadcrumb` prop in `Page`, and we could apply `.pf-c-page__main-wizard` to the wizard component we passed in.

On the other hand, if we want to simply put a wizard in the main section, we could add a divider on top of it to make it looks the same as the in page wizard design. And to make it consistent, should we better remove the `.pf-c-page__main-wizard` in HTML/CSS side? For example, in this demo https://www.patternfly.org/v4/components/wizard/html-demos#in-page, we don't use `.pf-c-page__main-wizard` anymore if we want to remove `.pf-c-page__main-wizard`. Instead, we can simply use `.pf-c-page__main-section` and put a divider on top of it.

WDYT? It will influence the next step in both React repo and core repo like how to add in page demo #5372 .

**Comment by mcoker** [comment]
Hey @DaoDaoNoCode! We have another enhancement/fix needed for the wizard that may impact this work - https://github.com/patternfly/patternfly/issues/3255

I'd like to work on that issue for a little bit and see if we need a unique page section (`.pf-c-page__main-wizard`) to fix the problems in that issue, or if we're able to allow it to work using a regular page section. From there I think we can talk about how to include the wizard in a page - as a prop, `<PageSection type="wizard">`, or if we create a demo that uses a regular page section and a `<Divider>`.

I would be curious what others think about those approaches, too. I'm assuming a prop might be difficult to manage, since a user might want to position their wizard in the middle of other page sections, or use other props you can apply to page sections (`isWidthLimited`, `sticky`, etc), things like that.

We may also keep `<PageSection type="wizard">` for consistency, but allow the use of the wizard in a regular page section with a `<Divider>` component, too, assuming we can get the layout to work properly in a regular page section.

**Comment by mturley** [comment]
I think I like that last option best (support both), but if I had to choose I'd go for the more composable option (just use a regular `<PageSection>` with a `<Divider>`).

**Comment by DaoDaoNoCode** [comment]
It seems that @nicolethoen has completed this feature in #5325 . Maybe it's OK to close this issue?

**Comment by nicolethoen** [comment]
I'm going to close this issue. The [Page section demo for the Wizard component](https://www.patternfly.org/v4/components/wizard/react-demos#in-page) demonstrates this capability.
