### ISSUE TITLE
Create PWA demo (Progressive Web App) using lit-html

### ISSUE THREAD

**Issue by maria-le** [patternfly/patternfly-react#501]
Please create a demo starter enterprise app [based on the lit-html PWA Starter Kit.](https://github.com/Polymer/pwa-starter-kit)

https://github.com/Polymer/pwa-starter-kit

This will enhance the current demo app by making it responsive and work offline. As well as being available on the web and also tablet and mobile across all operating systems and browsers.

**Comment by priley86** [comment]
It seems like this issue might be sorely placed? Considering this is a PF React repository... 

I.m.h.o. introducing another rendering library such as lit-html/polymer would be "double dipping" in that department (since React is specifically for view rendering and very advanced in this department). I believe responsive/offline is dependent on implementation (i.e. you can find similar things in the [create-react-app](https://github.com/facebook/create-react-app) boilerplate). 

would you be ok with closing this issue @maria-le ? I believe these are just alternative routes which are not purposed in this repo. thanks for reaching out though!

**Comment by dgutride** [comment]
Moving to closed based on inactivity
