### ISSUE TITLE
Add multi-level drill down menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5024]
Introduce a multi-level drill down menu per these designs: https://marvelapp.com/prototype/66b0059/screen/72079939

Core issue: https://github.com/patternfly/patternfly/issues/2635

@jessiehuff Thoughts about keyboard interaction for this?

Requesting projects: Multiple (cloud platform, app services)
Date needed: March
Contacts:  @ajacobs21e @nlcwong @aprilma419

**Comment by jessiehuff** [comment]
The only keyboard accessibility concern I have with a multi level drill down menu is making sure that the submenus are not immediately opened when using the tab key to navigate through the menu. I would expect that the user would tab through menu options, select the option with the submenu with space or enter (using either the parent or the button as the toggle) and then be able to tab through those options. Otherwise if the user is trying to get to the menu option after one with a submenu, they could be forced to go through the entire submenu first. This [article](https://www.w3.org/WAI/tutorials/menus/flyout/) explains the accessibility functionality/options pretty well.
