### ISSUE TITLE
Recommend way to import react-icons is not working

### ISSUE THREAD

**Issue by gildub** [patternfly/patternfly-react#5028]
https://www.npmjs.com/package/@patternfly/react-icons#tree-shaking page recommends to import icons with following syntax:
`import TimesIcon from '@patternfly/react-icons/dist/js/icons/times-icon';`

Unfortunately that doesn't work for us.
I tried with @patternfly/react-icons versions 4.7.6 and latest 4.7.11.
And it gives following error:
`Cannot find module '@patternfly/react-icons/dist/js/icons/resources-full-icon;' or its corresponding type declarations.ts(2307)`

The alternative is to use the following, works meanwhile it's the optimal/recommended way:
`import { FilterIcon } from '@patternfly/react-icons';`

**Comment by redallen** [comment]
Hi @gildub ,

I'm unable to reproduce this error. I can [import and use the ResourcesFullIcon](https://codesandbox.io/s/quirky-waterfall-t3gs2?file=/src/index.js) just fine with the versions you specified. Do you mind creating or linking a project where this doesn't work? It might be due to your babel or webpack config.

Thanks!
- Zack

**Comment by gildub** [comment]
Sorry for late reply following up.

This is working as expected using latest (@patternfly/react-icons@4.26.4) and Webpack recommended setup. 

Thanks
