### ISSUE TITLE
TextArea isDisabled property is called readOnly?

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#5068]
**Describe the issue. What is the expected and unexpected behavior?**
It's more of a consistency issue really, all of the components that support being "disabled" have a property called `isDisabled` except TextArea where it's called `readOnly`. Wouldn't it be better to call it `isDisabled` there as well?

**Comment by tlabaj** [comment]
For this one I propose we add a `isReadOnly` prop similar to the TextInput component rather than `isDisabled`.  Right now to make the TextArea read only, you have to use the attribute for the native `<textarea>`.  Or, are you looking to apply `disabled` to the underlying `<textarea>`?  in that case, we should add `isDisabled`.
