### ISSUE TITLE
AlertGroup removes the state of my components

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#5084]
When I have a component, that has some state, it looses this state after an alert gets rendered.

Sandbox of the issue:
https://codesandbox.io/s/happy-cerf-96e52

1. The Test component is set with the state "hello" (after the button is pressed)
1. Then when the "Issue" button is pressed the state of the test component is reset back to "demo"

What I expect is that the state of the Test component not to be influenced by the alert.

**Comment by edewit** [comment]
This is not a patternfly issue it's how react works

**Comment by redallen** [comment]
The problem is with this line: `const [demo, isDemo] = React.useState("demo");`. `useState` binds to the outer `YourIssue` function rather than the `Test` function like you expect.

Working demo [here,](https://codesandbox.io/s/elastic-paper-6892i?file=/index.js:392-401) feel free to reopen if you are unable to use this solution.

**Comment by edewit** [comment]
@redallen right it was late looking long into this strange issue, wasn't thinking strait.
