### ISSUE TITLE
Move "Page" html demos into "Navigation" component

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#5106]
Change `id: Page` to `id: Navigation`.

Related https://github.com/patternfly/patternfly/issues/3447

**Comment by mmenestr** [comment]
From Matt:

We decided this is not so simple because all of the demos on this page do not reference navigation. So in that case, I's like to see up split this into two separate sets of demos.

**For Navigation, include:**
Default nav
Expandable nav
Horizontal nav
Tertiary nav
Grouped nav
Light themed sidebar and nav

**For Page include:**
Sticky tertiary nav
Sticky breadcrumb
Sticky section group
Sticky section bottom
Overflow scroll

**Comment by redallen** [comment]
@boaz0 Sorry that there are changing requirements on this. Can you update your PR?

**Comment by boaz0** [comment]
Sure!
