### ISSUE TITLE
PF4: Alert typings issue

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#513]
I'm using the pf4 alert with the Cost Management UI and encountered a couple issues.

1. A simple string does not compile with typescript:

```
<Alert variant="danger"...

   TS2326: Types of property 'variant' are incompatible.
   Type '"danger"' is not assignable to type '"Succes" | "Danger" | "Warning" | "Info"'.
```

2. Want to import AlertVariant, but it's not exported in react-core/dist/js/index. Had to create my own AlertVariant object with type any as a workaround:

```
const AlertVariant = {
      success: 'succes',
      danger: 'danger',
      warning: 'warning',
      info: 'info'
    } as any; <<<<

<Alert variant={AlertVariant.danger}...
```

**Comment by dlabrecq** [comment]
I still cannot import AlertVariant after installing @patternfly/react-core v1.7.0. Although, we can import Alert and ButtonVariant, like so:

```
import {
  Alert, <<<
  Bullseye,
  Button,
  ButtonType,
  ButtonVariant, <<<
  Card,
  CardBody,
  CardHeader,
  Title,
  TitleSize,
} from '@patternfly/react-core';
```

**Comment by dmiller9911** [comment]
@dlabrecq Sigh looks like I missed adding it to the index.d.ts under Alert. A work around is to use the string literal for now `<Alert variant="danger"` you will still get the same type safety since we are actually asserting on the string value not the use of the enum. New versions of TS should give the intellisense too.

**Comment by dlabrecq** [comment]
Appears to be resolved now.
