### ISSUE TITLE
Unable to use DatePicker

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#5156]
**Describe the issue. What is the expected and unexpected behavior?** DatePicker is not working for me. I'm trying to use it in the most basic fashion as captured in the documentation, like the below snippet for example. 

`<DatePicker minDate="04/09/1988" maxDate="11/18/2020" onChange={onChange} />`

If I use an early version of the package (`4.1.0`) the component does render as expected and the app styling is without issue, but there is no `onChange` method exposed.

<img width="500" alt="Screen Shot 2020-11-18 at 1 41 01 AM" src="https://user-images.githubusercontent.com/5942899/99497188-8ec8bd00-2943-11eb-8112-607b48322cc1.png">

I then tried to use it as a basic JavaScript component, thinking the type was just wrong, but selecting a date entry still does not fire any onChange event. Seems to be related to https://github.com/patternfly/patternfly-react/issues/5001. Strangely, pressing the space bar with focus in the input fires an event, but it's not usable from an experience standpoint, and the values don't match what the documentation says anyway.

<img width="412" alt="Screen Shot 2020-11-18 at 1 54 22 AM" src="https://user-images.githubusercontent.com/5942899/99497578-20d0c580-2944-11eb-8a53-f350cf4347f3.png">

I then came across https://github.com/patternfly/patternfly-react/pull/5011 which looked hopeful, so I re-tried the package at version `4.2.19`, which is actually what I tried initially, but it breaks the styling across the entire app. I thought I was just doing something wrong, but after quite a bit of back and fourth I finally had to come to a stopping point as I realized there is no test in the jest test suite that exercises `onChange` nor is there a demo of this in `react-integration`, so it seems like it might be more than just a small issue. Here below is an screenshot of how the app styling breaks completely when importing and using the newer version.

<img width="771" alt="Screen Shot 2020-11-18 at 2 36 59 AM" src="https://user-images.githubusercontent.com/5942899/99499568-1b28af00-2947-11eb-8775-66dc395d4de3.png">

Removing the `@patternfly/react-datetime` package makes the app styling go back to normal.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

- Install the DatePicker package
- Try to use it
- Notice the `onChange` does not work
- Notice styling issues that arise when using the latest version on npm (4.2.19 as of time of writing)

I put together an example that illustrates the problem using the patternfly-seed project

https://github.com/seanforyou23/patternfly-react-seed/tree/datepicker-issue-illustration

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a blocking bug, I have tried everything I can think of but there doesn't seem to be any work-around I can find.

**What is your product and what release version are you targeting?**
Personal projects and also can be seen in the [patternfly-seed](https://github.com/patternfly/patternfly-react-seed) project.

**Comment by marusak** [comment]
Can confirm the exact issue - `onChange` does not get triggered in version `4.1.0` and updating to version `4.2.50` breaks style for all other PF components.

**Comment by marusak** [comment]
Is this supposed to be fixed in `4.2.53` pre-release? Because the UI is still broken the same way with this package.

**Comment by redallen** [comment]
Currently `onChange` works as expected and I'm unable to reproduce this issue in the seed app.

However, I suggest waiting until next release (2 weeks from now) to use the DatePicker. While currently usable (and hence my closing the issue) the styles are off if you rely on imports from `@patternfly/react-styles` instead of importing from `@patternfly/patternfly` yourself.

The API is also being amended. For example, the `minDate` and `maxDate` props have been removed in favor of a `validators` interface. Since 3rd party dependencies like `flatpickr` and then `date-fns` have been removed DatePicker and CalendarMonth will likely move to `@patternfly/react-core` next release. 

If you still want to use this beta component in the next 2 weeks [patternfly.org](https://www.patternfly.org/v4/components/date-picker) and [codesandbox](https://codesandbox.io/s/inspiring-leaf-fvcxy?file=/index.js) shows example usage. Make sure with `@patternfly/react-datetime@4.2.53` you install a compatible version of `@patternfly/react-core` like `^4.79.4` and include a prop like `value="2020-03-05"` (null values will be supported next release). Alternatively you can use an older `flatpickr` version like `@patternfly/react-datetime@4.2.6` which supports `minDate` and `maxDate`.
