### ISSUE TITLE
Export an easily reusable TypeScript type for IconComponent

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5192]
If you're writing a component that can be used with different kinds of icons, it is useful to have a prop for passing in an icon component. Currently that prop needs to have the type `React.FunctionComponent<React.SVGProps<SVGSVGElement>>` which is not at all obvious. It would be nice to have a type exported from `@patternfly/react-icons` called something like `IconComponent` or `IconComponentType` with this value, and we should add that to the docs somewhere.

cc @redallen @guillaumevincent

**Comment by redallen** [comment]
While I suggested `React.FunctionComponent<React.SVGProps<SVGSVGElement>>` in Slack that's just what I personally would use as a strict function type. We don't use this type anywhere in PatternFly. In fact, there isn't a PatternFly-specific type for icons -- we usually just happily accept and pass around `React.ReactNode`s.

In 2 of 17 cases we use `React.ComponentType<any>` (Empty state) and `React.ReactElement` (Select). We should change these to `React.ReactNode` to be more consistent on our end.

For types, I'd suggest:
1. `React.ReactNode` to be the most flexible. Icons could be spans with a class, `<svg>`s rendered with React, or maybe even just text (like "X" for close).
2. `React.FunctionComponent<React.SVGProps<SVGSVGElement>>` to be more strict and only accept SVG-like elements that your component can then render (I believe this is what was requested in Slack).
3. `React.ReactElement` to be more strict and only accept custom React elements (no text).

If we ever find a use case for `React.FunctionComponent<React.SVGProps<SVGSVGElement>>` in PatternFly we'll be sure to export a convenience type since it is a lot to type.

**Comment by mturley** [comment]
Sounds good. I seem to remember a case where `React.ReactNode` wasn't good enough, but I can't remember why. I'll see if I can figure that out and I'll reopen this if I do.
