### ISSUE TITLE
Draggable DataList items are not placed in the new possition when mouse is used for moving

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5250]
When keyboard is used dragging works properly but with mouse I just can't move things around.

cc @kmcfaul

**Comment by tlabaj** [comment]
Hi @KKoukiou.  Can you please provide the steps to reproduce this, we were not able to reproduce this issue on our site.

**Comment by KKoukiou** [comment]
https://www.awesomescreenshot.com/video/2043393

**Comment by kmcfaul** [comment]
@KKoukiou I can't access the video, the site says it is an invalid share key.

**Comment by KKoukiou** [comment]
> @KKoukiou I can't access the video, the site says it is an invalid share key.

@kmcfaul sorry, I replaced the video link with a gif in the comment above.

**Comment by kmcfaul** [comment]
@KKoukiou Thanks for updating with the gif! 

After testing some more, I found that this is a Firefox specific bug. The `dragEnd` event is not being fired because the nodes are being moved/edited as the drag moves (for the placeholder row). [The MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/dragend_event) links a very old [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=460801) that hasn't been resolved. 

It might be possible to work around this by manually listening for the `mouseup` event and returning the new item order that way, since it appears everything is working except that last event call.

**Comment by KKoukiou** [comment]
Please double check that this is solved before closing this.

**Comment by KKoukiou** [comment]
Does not work for firefox still. I think we should update the docs to contains the WA. Firefox is a supported browser for all RH products and we should make sure this works somehow there as well.

**Comment by KKoukiou** [comment]
Ignore - I was testing with an older react version. This was fixed by:
https://github.com/patternfly/patternfly-react/pull/5505
