### ISSUE TITLE
ClipboardCopy displays multi-line text oddly in the summary section

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly-react#5324]
**Describe the issue. What is the expected and unexpected behavior?**

When passing text with newlines to ClipboardCopy, the summary section can render oddly, showing no whitespace between the lines. This screenshot shows the ClipboardCopy component above, along with the raw markdown source below.

<img width="236" alt="Screen Shot 2021-01-12 at 2 24 14 PM" src="https://user-images.githubusercontent.com/4741620/104363481-3c3ef380-54e3-11eb-9d7d-27dd95ca14fa.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/vigilant-morse-bm32m

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

I don't really see a workaround, since the `<input>` element is hidden under the component, so I can't do anything with css.

**What is your product and what release version are you targeting?**

RedHat Advanced Cluster Management
https://github.com/IBM/kui

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
@tlabaj I don't think this is a CSS issue. New lines aren't rendered as spaces in a text input like they are in other html elements - https://codepen.io/mcoker/pen/rNmvdOR

It looks like when text is passed directly to the component, the new lines are converted as expected, but when a var is passed, they aren't. Is there a way to format a var passed to convert any new lines to spaces?

Here's the example from the codesandbox recreated in our workspace since I couldn't figure out how to disable the auto-formatting in codesandbox.

<img width="575" alt="Screen Shot 2021-07-30 at 11 34 27 AM" src="https://user-images.githubusercontent.com/35148959/127684113-cf24bd12-0d0f-4870-9349-f820b14adbd2.png">

<img width="701" alt="Screen Shot 2021-07-30 at 11 40 25 AM" src="https://user-images.githubusercontent.com/35148959/127684849-cbc03476-91f2-4226-9f8d-85d6dde48dc3.png">

@starpit if you want to override the CSS, you can do something like this:

```
.pf-c-clipboard-copy__group .pf-c-form-control {
  // css goes here
}
```

**Comment by eliranmal** [comment]
i verified that the issue is not a styling issue (as stated in @mcoker's investigation above).

replacing any newlines in the passed string (e.g. `(children as string).replace(/\n/g, ' ')`) fixes the problem.
here's [a demo][1], showing the effect with and without the replacement.

i'm not sure if there are any hidden implications though, so i'd love some feedback on that.


[1]: https://codesandbox.io/s/festive-bouman-kie45

**Comment by eliranmal** [comment]
proposed change:

```diff
Index: packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx b/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
--- a/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx	(revision 1c02d77a07a642f8ef67eaf94ba3330fa8015a63)
+++ b/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx	(date 1644085199373)
@@ -233,7 +233,7 @@
                   <TextInput
                     isReadOnly={isReadOnly || this.state.expanded}
                     onChange={this.updateText}
-                    value={this.state.text as string | number}
+                    value={String(this.state.text as string | number).replace(/\n/g, ' ')}
                     id={`text-input-${id}`}
                     aria-label={textAriaLabel}
                   />

```

**Comment by mcoker** [comment]
@eliranmal sorry for the delay! From the CSS side, I'm not aware of a way to change the formatting of the text inside of a text input. One option could be to render the text in a `<div>` and use `contenteditable` to make it behave like an `<input type="text">` when it needs to, which gives us a lot more control over how the content is displayed - though that may be breaking.

**Comment by eliranmal** [comment]
@mcoker that's ok - i'm under no specific deadline :)

while the current fix seem to be non-breaking, i gather from your reply that we should favor rendering-oriented solutions over behavioral changes (?), so i'll give the `contenteditable` approach a go and see what i can come up with.  
if all h\*\*\* breaks loose, i'll retrace my steps, and see what breaks.

by the way - when running locally, how can i ensure i'm testing for the widest regression set possible? is running the entire test suite enough, or should i append some special flag?

**Comment by nicolethoen** [comment]
I think that we've wrestled with some quirks with using `contenteditable` and screen readers in the past. 
We'd want to test that it'd still work if that's the solution we wanted to try.

I don't _think_ that updating the parsing to use `.replace` constitutes a breaking change in the ways that we would normally avoid. But I would defer to @tlabaj for that.

**Comment by eliranmal** [comment]
hey,

i'm holding creating the `contenteditable` impl', until further comments on this issue arrive from core members (@tlabaj can you please share your input?)

if i don't hear anything for a few days, i'll go ahead and move the current solution's PR out of draft mode, so it's ready for review.

cheers :)
