### ISSUE TITLE
bug(Typeahead Select): the selection should be updated also when the user uses <Tab> to select it

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5364]
This could be just an issue of the example implementation, however it seems that there is not any obvious way how to propertly implement it.

Steps to reproduce:
* Use the https://www.patternfly.org/v4/components/select/#typeahead
* Focus on the input and write 'Alabama'
* when finished typing just press <Tab> instead of clicking on the selections from the list or pressing enter
* the selection state object should be updated but it's not

A workaround would be to update the selection also on the onToggle function, when the dropdown closes. But that would need access to the ref of the <input>.

**Comment by jessiehuff** [comment]
Hey @mcarrano! I'd love your opinion on the interaction expectation here. This issue sounds identical to [this previous issue](https://github.com/patternfly/patternfly-react/issues/5164), and both sound like an interaction/design question.

It sounds like it's a question of whether we'd expect a value to be saved/submitted when tabbing or clicking away. However, it brings to mind more questions like what if the entry isn't a valid value, is keeping that as the value always an option when tabbing or clicking away? What about when it's isCreatable? Do we know for sure they'd want to create that option? It might be good to think about all the possible scenarios and how the user would know their value is captured or not because I don't know if just typing in a value would be a valid way. Honestly, any accessibility perspective I could take would be the same questions I'd pose for the average user here which make me wonder what the interaction expectation would be for this situation. Is this what someone would expect? How do they know or decide that they want to submit a value?

**Comment by KKoukiou** [comment]
OH @jessiehuff I just realized there is the other issue you  mention above, feel free to close this, move the question/comment and we can continue the discussion in the other issue which is a bit more verbose as well.

**Comment by jessiehuff** [comment]
Ok, sounds great @KKoukiou! 🙂 Just moved my comment to that issue, and I'll close this one out.
