### ISSUE TITLE
Fix needed for 12-hour format in Time picker component

### ISSUE THREAD

**Issue by MariSvirik** [patternfly/patternfly-react#5401]
12-hour format of time picker is written incorrectly [here](https://www.patternfly.org/v4/components/time-picker) in an interactive dropdown.

Instead of '3:35am' it should be written '3:35 AM' - using a space after the numbers and the capital letters for AM and PM. 
This change has been consulted with Alana from the content team.

**Comment by redallen** [comment]
What do you think @mcarrano ?

@nicolethoen if we make this change should we still accept `defaultTime="3:35am"`?

**Comment by mcarrano** [comment]
Yes, I agree. This becomes more of a presentation thing. That said, if someone were to enter 3:35am" from the keyboard, I think we should accept it, but maybe upon processing the string we would update it to the preferred format? Thoughts @redallen @nicolethoen ?

**Comment by nicolethoen** [comment]
We used the lower case am/pm with no space because that's what the google calendar time picker uses. We can very easily change it. Technically inputting AM/PM with a space is valid the way the time picker is currently built so switching the default formatting should still also allow the older way as valid. The picker should parse it so it changes from am/pm to _AM/PM when validating.

**Comment by mcarrano** [comment]
Sounds good @nicolethoen . I will add this into the roadmap for the next sprint then.
