### ISSUE TITLE
Background image system 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#550]
Introduce background image system: https://pf-next.com/components/BackgroundImage/examples/

Note: There is some complexity involved here with how to consume this component because of the static assets and react’s usage of webpack

In addition to a React review, this issue should be reviewed by the core contributors of this demo:
CSS: @andybraren
Design: @mceledonia

**Comment by dlabrecq** [comment]
@LHinson I've created the background image component, but blocked by https://github.com/patternfly/patternfly-next/issues/752. I'm not able to load PF4 style images because they are built with absolute paths. If the images are built using relative paths, then webpack should be able to load them. Note webpack is able to load fonts because they're using relative paths

**Comment by dlabrecq** [comment]
I also found that react-docs needs the ability to display examples in a full page. Otherwise, the background is applied to the body of the page. I see that patternfly-next has custom code to display examples in a full page; however, the Gatsby app for react-docs does not have that functionality.

**Comment by dlabrecq** [comment]
Added functionality to Gatsby in order to show components in a full page, similar to patternfly-next.

See PR https://github.com/patternfly/patternfly-react/pull/658

**Comment by dlabrecq** [comment]
The PR below introduces pf-next variables to address the image path issue.
patternfly/patternfly-next#776
