### ISSUE TITLE
Drop down menus that have tooltips are not keyboard navigate-able

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#5547]
**Description**
Pass a set of items to a dropdown that have tooltips makes the dropdown items not navigate-able via the keyboard.

**Steps to reproduce**
Run `yarn start:demo-app`
Navigate to the `Application Launcher Demo`
Open the application launcher via the keyboard
notice you cannot navigate to the choices.

**Is this a bug or enhancement?**
Bug, no workaround

**Comment by jessiehuff** [comment]
Currently wrapping any dropdown related components will cause a keyboard issue due to the way we're handling index (issue on that [here](https://github.com/patternfly/patternfly-react/issues/5490)), this includes wrapping them in a tooltip component. To add a tooltip to a dropdown or app launcher item, it should be added as a prop like this: `tooltip={<div>Launch Application 4</div>}`. I [updated](https://github.com/patternfly/patternfly-react/pull/5550) the app launcher demo to include the right usage.
