### ISSUE TITLE
PF4: Missing TextArea Typing 

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#582]
Encountered type errors with the TextArea from @patternfly/react-core v1.8.1.

TS2305: Module '"/Users/dlabrecq/Work/hccm/repos/koku-ui/node_modules/@patternfly/react-core/dist/js/index"' has no exported member 'TextArea'.

**Comment by amarie401** [comment]
Previously there were no type definitions for Text Area and Text Input. That has been changed recently with the merge of this [PR](https://github.com/patternfly/patternfly-react/pull/626/files#diff-66de655e0428a98ee2734bead0d9c4dc). Please also see [here](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/index.d.ts) to view the updated `index.d.ts` file. Since the issue has been resolved, I will go ahead and close this issue.
