### ISSUE TITLE
PF4 Modal component is not draggable/movable

### ISSUE THREAD

**Issue by hstastna** [patternfly/patternfly-react#5883]
We are missing the draggable/movable ability regarding the PF4 React `Modal` component. This is more like a feature request. 

Sometimes it is very unpleasant not to see the important info under the dialog window. Having it draggable would solve such problems in any UI.

This could be relatively easily solved by using the PF3 component, but the effort is to go forward and to use only the PF4 components. Moving back and supporting PF3 is not a way to go, together with some other solutions we considered in my team.

This is blocking the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1744114

Thanks very much in advance for any info, comments, suggestions!

**Comment by mcarrano** [comment]
@tlabaj @nicolethoen After discussing this with @mcoker we decided to take a React-first approach, and therefore I am planning to queue this up for our next React feature sprint. My expectations for mouse interaction are as follows:

* When the user hovers over the header area, the cursor changes to the `move`cursor to give an affordance that the window is movable. 
* Clicking down and dragging on the header will update the position of the modal relative to the travel of the mouse coordinates.
* Releasing the mouse will leave the modal at it's new position.
* While moving, we should test against the boundaries of the viewport to ensure that the modal is not positioned outside of the browser window.

I was not sure how this should work for keyboard interaction. @jessiehuff can you give guidance?

Any other interactive elements in the header should take precedence for event propagation. 

Let me know if you see any problems with this approach. If core work if needed, we can open a new issue. But seemed like this can be handled directly in React unless we find that changes to the structure of the modal header are needed.

**Comment by jessiehuff** [comment]
I think the big question that I have for this is what is the usability issue that we're trying to solve for here and how are we solving it for all users? Do we have guidance on when to use a draggable/movable modal?

Typically when using a modal, the user doesn't have access to the content beneath the modal, and they are just able to interact with the modal itself. This, likewise, is the experience for screen reader users since this content is hidden from the user while interacting with the modal. If we make the content behind the modal now accessible to sighted users, we then need to make this content accessible to screen reader users. We also currently have the backdrop dimmed when using a modal. Moving the modal brings up the question of what should we do for low vision users? Would we remove the backdrop so that all users can still see the content? If there are important contents behind the backdrop, how is that information available to all users? If there are important contents behind the modal, I wonder if we should be using the modal at all in this case?

**Comment by redallen** [comment]
This is the use case the upstream bugzilla is about:
![migration](https://user-images.githubusercontent.com/47335686/124660256-f94b5080-de73-11eb-99c3-e1aa3aa0b729.png)
![movable](https://user-images.githubusercontent.com/47335686/124660258-f9e3e700-de73-11eb-912f-0ecc6c72a861.png)
![not_movable](https://user-images.githubusercontent.com/47335686/124660259-f9e3e700-de73-11eb-9bd2-9577cbd99a01.png)

**Comment by mcarrano** [comment]
@hstastna I wanted to probe the requirements for this a bit more. We could create a modal that is draggable as you are requesting, but I am concerned about the accessibility of this approach for the reasons that @jessiehuff outlines. Is there specific information that you feel like the user needs access to while they work within the dialog? Could that be presented another way or perhaps consider using a [Drawer](https://www.patternfly.org/v4/components/drawer) for edits so that information can exist side by side?

**Comment by sgratch** [comment]
@mcarrano @hstastna 
We are using FP4 React modals plugged into a GWT app for the RHV Admin portal UI. The main reason we need a draggable modal  is to be as much consistent as we can with other admin portal GWT dialogs and the admin portal UI design as a concept.

There is no plan to convert all GWT dialogs to React since it's too complicated so we need to support this combined UI. 
 In the past Admin Portal users asked for this draggable option for the GWT dialogs so it is supported for GWT dialogs but not supported for PF4 react ones. 

There is an important info within the content beneath the modal like the grids (vm list, hosts list etc) or the entity info and  the user needs access to this info while editing the modal. That's why we also canceled the defaulted backdrop dimmed when using a react modal within the Admin portal.

We won't change it to use a  Drawer since it's not consistent -  within the admin portal all edit dialogs are presented as modals and not as drawers.

**Comment by mcarrano** [comment]
@hstastna @sgratch After discussion with the team, we have decided that this is not something we want to support generally in PatternFly. It raises a11y concerns and feels very specific to your project. We have not had other requests for this. Therefore I am closing this out, but we could possibly advise you on creating a custom implementation that could be shared as a community extension if this is something you wanted to contribute back.
