### ISSUE TITLE
Aria-label not supported on specific div elements

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#5897]
**Describe the issue. What is the expected and unexpected behavior?**
An axe issue was discovered on OpenShift's Installation Wizard for the OCS operator which then made us realize that this exists on the pf wizard as well. In the wizard body there is an `aria-label` on the `<div>` that isn't being supported. We should investigate how to fix this. This is also an issue on the alert component (also found from OpenShift's Installation wizard) so I imagine that there might be other places that this issue exists as well.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Run axe against [this example for Wizard](https://www.patternfly.org/v4/components/wizard/react/basic/) and [this example for Alert](https://www.patternfly.org/v4/components/alert/react/types/).

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

**Comment by nicolethoen** [comment]
This will require us to refactor the Alert unit tests, since they query by the Alert's aria-label

**Comment by nicolethoen** [comment]
In this case, Alert's aria-label is defaulting to be the same as the Alert's title. So it's causing the screen reader to read the same information twice, which is unnecessary. I think we can remove the alert's aria-label.

In the case of the wizard, the aria-label applied to the WizardBody component's div element. our demos include defining a `mainAriaLabel` which is passed and sets the WizardBody's aria-label. It's worth discussion about what purpose this prop is intended to serve. If it is helpful to have an aria label on the WizardBody, then the body likely needs to be updated so that it's not on a div, or uses a more specialized role like 'region'

**Comment by thatblindgeye** [comment]
For alert, https://github.com/patternfly/patternfly-react/pull/7604/files may be relevant (it was later reverted as I believe it caused issues during testing for release candidates) (possibly look into a role to add to alerts?)

Could possibly involve similar functionality added to Accordion where roles/tabindex/etc are conditionally added when necessary (when a scrollbar gets rendered).
