### ISSUE TITLE
bug(DataList): the drag/move feature is not working at all on mobile on firefox

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5900]
**Describe the issue. What is the expected and unexpected behavior?**

The draggable data list does not seem work on mobile using Firefox. Tested on Firefox Nightly, Android 11.
On Chrome, if you touch and hold for a while, it works... but the dragged item is not shown (blank rectangle)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no workaround.

**What is your product and what release version are you targeting?**

Cockpit Virtual Machines plugin.
This is one of the two components that are still blocking us from completely dropping PF3 from our dependencies.

**Comment by KKoukiou** [comment]
@tlabaj Can someone look at this? This component is the last remaining in cockpit to port from PF3 to PF4 :) Plus it's a serious bug.

**Comment by tlabaj** [comment]
Hi @KKoukiou . There are a number of issues open with draggable feature.  We are looking at them and and investigating solutions.

**Comment by KKoukiou** [comment]
Friendly reminder :) Would be super nice to be able to drop this so that we can also drop completely PF3.

**Comment by redallen** [comment]
It's fixed with the new suggested `<Draggable>` implementation: http://patternfly-react.surge.sh/components/data-list#draggable

![dragdrop-firefox](https://user-images.githubusercontent.com/47335686/136436194-49848e99-aaea-4689-b41f-8d736c1094af.gif)

The deprecated HTML5-based API may still be broken, but that's why it's deprecated. Closing!
