### ISSUE TITLE
findDOMNode produces warnings in Strict Mode

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#6050]
When [Strict Mode](https://reactjs.org/docs/strict-mode.html) is enabled Patternfly creates deprecation warnings due to the usage of `findDOMNode`. 

This is deprecated functionality and the recommendations to handle this deprecation as stated in the [React documentation](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) should be followed.

## Actual behavior

Patternfly creates the following exception:

![An example of the exception produced](https://user-images.githubusercontent.com/695720/126146265-f3aab875-8327-4fd9-a61c-4957514ac5de.png)

## Expected behavior

Patternfly does not produce any exceptions.

## Steps to reproduce
Enable [Strict Mode](https://reactjs.org/docs/strict-mode.html) in an application running Patternfly.

**Comment by jonkoops** [comment]
@redallen Perhaps this might help: https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by jonkoops** [comment]
Note that this behavior could be enforced using an ESLint [rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md).

**Comment by redallen** [comment]
Again, if there's a way to remove `findDOMNode` without breaking breaking existing components I'm all for it, but it's not as simple as "just use refs" or "stop using // eslint-disable-next-line react/no-find-dom-node."

These are the places we currently use `findDOMNode`:
```
packages/react-core/src/components/Dropdown/DropdownMenu.tsx:133:59:        this.refsCollection[index][innerIndex] = ReactDOM.findDOMNode(node) as HTMLElement;
packages/react-core/src/helpers/util.ts:182:30:    const element = ReactDOM.findDOMNode(refsCollection[nextIndex]) as HTMLElement;
packages/react-core/src/helpers/Popper/FindRefWrapper.tsx:11:29: * It has to be a class for findDOMNode to work
packages/react-core/src/helpers/Popper/FindRefWrapper.tsx:21:27:    const root = ReactDOM.findDOMNode(this);
```

Keeping `findDOMNode` as a last resort in DropdownMenu.tsx and util.tsx is fine. You should see warnings if we can't grab your refs normally. However it's more difficult for places we use `FindRefWrapper` like Popper because it allows passing _any_ trigger and _any_ menu which [it then has to grab refs from.](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/helpers/Popper/Popper.tsx#L308)

Is there a reason the Popper's trigger and menu can't be wrapped with divs that have normal refs @jschuler ? I might be able to try it out this afternoon.

**Comment by jonkoops** [comment]
> Again, if there's a way to remove `findDOMNode` without breaking breaking existing components I'm all for it, but it's not as simple as "just use refs" or "stop using // eslint-disable-next-line react/no-find-dom-node."

I was operating under the assumption that this rule had been disabled for the entire repo, my bad. I'd love to spend some time helping out to fix these issues, but unfortunately my work on Keycloak is keeping me busy,

**Comment by jonkoops** [comment]
Not stale.

**Comment by nicolethoen** [comment]
@mcarrano could you assign this to a milestone?

**Comment by AlexisLessard** [comment]
For your information, we noticed this issue as well. We've just activated strict mode, and the issue appears in local development., because we're using PageHeaderToolsItems and Tooltips in our main page. Waiting for a fix.

Versions:
```
 "@patternfly/patternfly": "^4.159.1",
 "@patternfly/react-charts": "^6.28.4",
 "@patternfly/react-core": "^4.202.29",
 "@patternfly/react-icons": "^4.26.4",
 "@patternfly/react-styles": "^4.25.4",
 "@patternfly/react-table": "^4.44.4",
```

**Comment by andrewballantyne** [comment]
Curious, why can't we (the App) just use a ref manually on the item we want Popper to use and just pass that into Popover and you thread it down to where you need to find the node. It won't be breaking, it will be additive. 

```
const Test = () => {
  const ref = React.useRef();
  return (
    <Popover itemRef={ref} ...>
      <OutlinedQuestionCircleIcon ref={ref} />
    </Popover>
};
```

I really would like to stop seeing this in my application. This issue is over a year old. If we don't want to make a breaking change, just make it additive and it's no longer breaking.

Obv the right solution is to stop using it, but I would not like to see another year pass without this fix as there is concerns about a breaking/major shift in versions.
