### ISSUE TITLE
Example for composable table actions returns undefined

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#6230]
There's an issue with the composable action table example where if you click on an item in the drop down it will console log undefined.

https://www.patternfly.org/v4/components/table#composable-actions

<img width="2130" alt="Screen Shot 2021-08-11 at 9 54 55 AM" src="https://user-images.githubusercontent.com/6126356/129041948-f8bb6be5-4929-4077-9631-459190c70c60.png">

**Comment by mturley** [comment]
@jschuler do you think that `ActionsColumn` workaround in the examples is sufficient, or do we need to change something in the table components to fix this as well?

**Comment by tlabaj** [comment]
@mturley are you adding this to your PR?  Can I assign this to you?

**Comment by mturley** [comment]
I was going to take a look at it when I finished converting everything else, but I think it makes sense to fix it as part of that PR. Self-assigning.

**Comment by mturley** [comment]
@tlabaj @dlabaj @jschuler @nicolethoen I'm revisiting this now as part of wrapping up #6168, and I'm not sure exactly which direction to go here. Some observations:
* I think it may make sense to use the `ActionsColumn` workaround @jschuler describes above to fix the example, since that looks cleaner and more composable.
* The existing `actions` prop could be made to work without using that undefined `rowIndex` param, because when rendering a Td we have the underlying data object for that row in scope, so it could be passed into a function to generate the actions objects. This doesn't feel ideal to me, I'd prefer the ActionsColumn workaround.
* Regardless of how we fix the example though, ideally either that `actions` prop should work (and have a defined rowIndex) or we should deprecate it, right?

To that last point, I'm not sure how we'd get that to work without adding a `rowIndex` prop on the Td. Looking at where the actions prop is used: https://github.com/patternfly/patternfly-react/blob/main/packages/react-table/src/components/TableComposable/Td.tsx#L110-L122 that `actionParamsFunc` would need a rowIndex passed into it, and I don't see a way to get that index from that point in the code.

I think maybe the way forward is to (a) change the examples to use ActionsColumn as suggested above and (b) deprecate/remove the `actions` prop on the `Td` component entirely. Thoughts?

**Comment by jschuler** [comment]
I like the ActionsColumn approach, it's more composable that way too, which is in the spirit of this table :)

**Comment by mturley** [comment]
Sounds good to me. I'll close this issue as part of my PR then, and open a followup issue to consider deprecating that `actions` prop.
