### ISSUE TITLE
TreeView: `allExpanded` prop doesn't apply recursively, doesn't take effect if `true` on first mount. `defaultAllExpanded` affects more than initial state.

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#6314]
**Describe the issue. What is the expected and unexpected behavior?**

The new `allExpanded` prop introduced in https://github.com/patternfly/patternfly-react/pull/5503 and the existing `defaultAllExpanded` prop seem to behave differently than I would expect.

* If `defaultAllExpanded` is not passed, changing `allExpanded` to true only expands the immediate children of the root node(s). It does not behave the same way as `defaultAllExpanded`, which expands the tree fully (all descendants down to the leaves). However, if `defaultAllExpanded` is passed, changing `allExpanded` to true DOES fully expand the tree correctly regardless of current state when it changes.
* If I set `allExpanded` to `true` when the component first mounts, it does not start with the tree expanded. Using state to flip it to false and back to true does expand the tree. It appears I need to also set `defaultAllExpanded` if I want this behavior, but that feels weird to me, maybe we should deprecate the `defaultAllExpanded` prop if we can get the initial value of `allExpanded` to apply this way?
* Worth noting, when `defaultAllExpanded` is true, expanding any node in the tree fully expands all its descendants. I would expect it to only affect the initial state (toggling an individual node should only ever affect that node's level in the tree).

The behavior I'm looking for is: the tree starts fully recursively expanded, there is an expand/collapse all control that will fully expand the tree, but expanding individual nodes does not expand their descendants. I can't see a way to do that with the props as they behave now.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

You can see this behavior by changing these two props on the [default TreeView example](https://github.com/patternfly/patternfly-react/pull/5503) in the docs.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, I think? Unless I'm misunderstanding the intent of these props.

**What is your product and what release version are you targeting?**

Migration Toolkit for Virtualization, no particular target release.

cc @kmcfaul

**Comment by kmcfaul** [comment]
In the linked PR's surge, I don't see this behavior. The default example does not pass `defaultAllExpanded` and modifying the `allExpanded` property's starting state to `true` does recursively expand the full tree for me. However, I am seeing this behavior on our live docs site. 

Tracing through the changes to `TreeView` it looks like there was an update to have `TreeViewListItem` react to changes in `defaultExpanded`, and since `defaultAllExpanded` has a starting value of `false` and the `useEffect` is second in order, it is overriding changes set by `isExpanded` (item-level) and `allExpanded` (tree-level) is my guess. I'll test switching up the order and open a PR if it works.

**Comment by mturley** [comment]
Thanks @kmcfaul ! I should have checked the PR's surge link, good thinking.
