### ISSUE TITLE
TypeAhead Select shows autocomplete popup in Chrome

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#6625]
**Describe the issue. What is the expected and unexpected behavior?**
In a TypeAhead Select component, typing in the field brings up the autocomplete box in Chrome. This covers the filtered selections and one cannot chose from them.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Run the PF components in Chrome.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by garrett** [comment]
This bug actually now appears _after_ the PR that addresses the issue was merged. In other words, the "fix" causes the issue.

See: https://github.com/patternfly/patternfly-react/pull/6623#issuecomment-1005586144

Before this bug was introduced, there is one case where it might happen: when a typeahead is used for a user list. But now this bug shows up for every case, as "never" is not a standard string to pass to autocomplete. The correct value is "off", as it was before — or, in some rare cases, "new-password", to prevent a password manager autocomplete (even built-in browser ones) from showing up.

(We're seeing the issue in Cockpit after upgrading PatternFly now, since "off" is no longer being used.)
