### ISSUE TITLE
Draggable row table of  PatternFly 4 threw an error when I drag table row in horizon direction then move in vertical direction

### ISSUE THREAD

**Issue by judy20191103** [patternfly/patternfly-react#6723]
I have a question about Draggable row table of  PatternFly 4.
when I dragged one table row in horizontal direction out of the table, and it still in origin place . Then I dragged the table row in vertical direction, the page was crashed and threw an error:
"TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'." 
I found that thrown from the move function of the demo code.
This issue can repeat stably.
can you have a try and fix this issue?

**Comment by wushiying** [comment]
I think I have found the reason of this issue:
we shuold initialize tempItemOrder's value is the same as itemOrder, like below:
useEffect(() => {
    setItemOrder(props.rows.map((r) => r.id.toString()));
    setTempItemOrder(props.rows.map((r) => r.id.toString()))
  }, [props.rows]);
otherwise, when we trigger onDragOver event in 'if' condition(drag table row in horizontal direction), the tempItemOrder value is [], then we drag the table tow in vertical direction, triggering the onDragOver event 'else' condition, but the tempItemOrder is [], so
the move function threw an error for its empty array without attribute id.

**Comment by wushiying** [comment]
This issue is fixed

**Comment by nicolethoen** [comment]
This will likely be addressed when we tackle this issue: https://github.com/patternfly/patternfly-react/issues/6531

**Comment by nicolethoen** [comment]
Still plan to address this when we tackle this issue: https://github.com/patternfly/patternfly-react/issues/6531
