### ISSUE TITLE
Attribute-value filtering enhancement to support comma-separated approach for multiple values in 1 key

### ISSUE THREAD

**Issue by imjoyjean** [patternfly/patternfly-react#6795]
## Requesting new features, enhancements, or design changes to PatternFly 
- For the attribute-value filtering demo, currently each entry of a key-value pair turns into one chip, regardless of whether or not the pair has the same key as the others. 
- In ACM/ACS, the pattern that existed groups the values with the same keys in one chip. E.g., [cluster: name1, name2] instead of [cluster: name1] [cluster: name2]. It saves space and also is easier to locate and see the relationship when looking at the filters that one has applied

Current: 
![image](https://user-images.githubusercontent.com/57908474/145474610-ee44397f-49af-4423-9f8f-6683472ceb4a.png)

- This is an enhancement on this demo: https://www.patternfly.org/v4/components/text-input-group/react-demos/

**Comment by mcarrano** [comment]
Per discussion we can update the React demo to work this way. Will get this on our feature roadmap. Currently scheduling into Q2.

**Comment by mcarrano** [comment]
@mmenestr is this something we should also be adding to our filter guidance?

**Comment by nicolethoen** [comment]
This should be relatively simple to implement if we do the following:

- dont change the way the input expects the user to identify the attribute key first, then the value and uses a 'space' as a delimiter to trigger parsing the pair into a chip.
- once the user types a 'space' and the attribute-value pair is parsed into a chip, check to see if a chip already exists for that attribute key. If it does, update the preexisting chip to include an additional value as indicated in the design above. 

I don't think we need to update the parsing of inputs to watch for commas.

**Comment by mmenestr** [comment]
Here is my recommendation based on the feedback gathered by Joy and Andy Burka:
- Refrain from implementing the proposed way of displaying chips inside of a toggle outlined in this issue
- Instead, have two text-input options available
- - Option 1: Chips inside the text input - what we have today in our demos
- - Option 2: Chips outside of the text input - maintaining the same chip pattern we use in all our other filters today

 **Reasoning:** 
-  Want to try to use the existing patterns we already have - this would maintain consistency with other filter experiences where chips are surfaced at the bottom of the toolbar.
- PatternFly supports the ability to show multiple values selected within the same attribute via their chip groups. However, chip groups are too tall to be added to a text input field. But they work great under the toolbar (like we have today).
- From a usability stand point, it would arguably be confusing to type and select and attribute value pair, only for it to be populated somewhere other than right before your cursor. (Though it's true that it's easier to scan after the fact)

To supplement the increase in options around how to display chips in this type of filter, we can add guidance in the design guidelines around when to use chips inside the input vs outside of the input:
- Use inside when the text input takes up most of the toolbar and we expect the user to have a simple search
- Use outside when the user is expected to have a more complex/lengthy search and we want to be able to clearly display all their search queries. Also use when you have other filter types in your toolbar so that all the chips can be shown together.

let me know your thoughts! cc: @mcarrano @imjoyjean @arburka (related to issue #1143)

**Comment by mcarrano** [comment]
I think this totally makes sense @mmenestr .

**Comment by mcarrano** [comment]
In this case, I am going to close this issue. We can reopen/revisit in the future if necessary.
