### ISSUE TITLE
Checkbox invalid validation marker is not working

### ISSUE THREAD

**Issue by mazenkhalil** [patternfly/patternfly-react#6802]
**Describe the issue. What is the expected and unexpected behavior?**

Checkbox component doesn't show validation marker.

Checkbox required  id="consent" name="consent" label="I agree to the Privacy Policy." isValid={false} 

![image](https://user-images.githubusercontent.com/21160900/149765763-09e360d5-bb38-466c-b7fa-bae181f23f91.png)

**What is your product and what release version are you targeting?**
"react": "17.0.2"
"@patternfly/react-core": "4.181.1"

**Comment by DaoDaoNoCode** [comment]
@mazenkhalil Are you actually looking for another prop here? As far as I can tell, `isValid` prop is not used to change the [`aria-invalid`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid) label of the checkbox, it will not do any style change on it.

**Comment by mazenkhalil** [comment]
@DaoDaoNoCode What I am looking for is a way to apply invalid style to the checkbox as other components in the library.
e.g. adding `aria-invalid="true"` to the TextInput changes the style of the component. In case for Checkbox, setting `isValid` property sets aria-invalid to true but has no effect to the style.

**Comment by DaoDaoNoCode** [comment]
@mazenkhalil Could you let me know what kind of style you are looking for for the invalid type of checkbox? We have `disabled` but I am not sure what is `inValid` checkbox should look like.

**Comment by mazenkhalil** [comment]
I would suggest to change border color to red similar to 'invalid' style on the Text component.

**Comment by mmenestr** [comment]
Our recommendation would be to add a [static helper text](https://www.patternfly.org/v4/components/helper-text#static-with-default-icons) underneath the checkbox, like this, rather than changing the styling of the box. This would be more in line with our other patterns, and could already be implemented with what PF offers!

<img width="297" alt="image" src="https://user-images.githubusercontent.com/51165119/155607020-b0cabb16-2029-4674-a1bd-be8ed19dac0f.png">
