### ISSUE TITLE
Update bar-chart example to show tooltips with data labels

### ISSUE THREAD

**Issue by Fewwy** [patternfly/patternfly-react#6816]
**Describe the issue. What is the expected and unexpected behavior?**
The first and the second example(https://www.patternfly.org/v4/charts/bar-chart) shows a horizontal bar-chart but when the user mouse over any ChartBar column other than the middle one the tooltip does not appear. It is appearing on the vertical movement over the middle ChartBar column.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

The problem is in the documentation it could be found there https://www.patternfly.org/v4/charts/bar-chart

It could be solved by removing 
the `containerComponent={<ChartVoronoiContainer labels={({ datum }) => ${datum.name}: ${datum.y}} constrainToVisibleArea />}`

and adding 
`labelComponent={<ChartTooltip/>}` to the ChartBar as well as passing label value to the 
chartBar data object
This is the example:
```
<ChartBar 
data={ name: name, x: year, y: value, label:value }
labelComponent={<ChartTooltip/>} 
/>
```
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
Docs

**Comment by tlabaj** [comment]
cc @dlabrecq

**Comment by dlabrecq** [comment]
This is not a bug, but an approach for adding tooltips to a group of chart items. The examples at the top of each page are intentionally simplified.

Note that we have a "Data label" example (below) to demonstrate an alternate way of applying tooltips using data labels.
https://www.patternfly.org/v4/charts/tooltip-chart#data-label

The "Data label" example is a bit more complex, because it requires more code -- devs must add labels to each and every data object. Therefore, it was a better candidate for the tooltip examples. The "data label" approach applies to all chart types.

That said, if we choose to show the "Data label" approach here, I suggest that we add it to the second example only and leave the first example as is. Devs can choose whether they want to group tooltips or add "data labels" to each `data` object.

**Comment by Fewwy** [comment]
@dlabrecq It's good to have both examples because I honestly thought that it was an error. I just found it strange that the user doesn't see a tooltip when he's hovering over three bars out of four.

**Comment by dlabrecq** [comment]
Updated the bar chart example via https://github.com/patternfly/patternfly-react/pull/6883
