### ISSUE TITLE
Edit expandable data list example to remove the primary button

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#6933]
This demo uses a primary blue button to allow users to interact with the expand all/collapse feature: https://www.patternfly.org/v4/components/data-list#expandable

Having that functionality in the demo is great, the only issue is that people are considering the use of a primary button in this context a design suggestion. **This is not what we want to convey, so we should update that primary button to something else.**

Perhaps just a blue link button? but @mcarrano @mceledonia do you have any other ideas?

**Comment by mcoker** [comment]
@mmenestr @mcarrano looking at the [design guidelines for expandable data list](https://www.patternfly.org/v4/components/data-list/design-guidelines#expandable-data-list), we're using an expand all button in the toolbar. I know we moved the expand all button for expandable tables out of the toolbar and into the table header, but since the data list doesn't have a header, is the toolbar still where we want to put that? Assuming so, maybe we could just remove the expand all functionality from this example, and add an expand all demo if we think it's useful to show a way users can wire this functionality up themselves?

Side note - the [expandable table design guidelines](https://www.patternfly.org/v4/components/table/design-guidelines#expandable-table) still show the expand all button in the toolbar. Should we update that?

**Comment by mmenestr** [comment]
Hi, yeah that sounds like a good idea to me @mcoker ! And yes, we'd probably keep the expand all in the toolbar for data lists.
Also yes we definitely do want to update that, and I have [this issue](https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2693) open to address it, just haven't had a chance to do it yet, but I may just do that right now haha

**Comment by nicolethoen** [comment]
The consensus is that we will remove the expand/collapse all button from the expandable data list example. We will address demonstrating this feature in data list demos in other issues.
