### ISSUE TITLE
[Pagination] - update the items per page toggle so text is clickable

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7123]
Want to allow the text as well as the down caret to reveal the items per page options. Core PR: https://github.com/patternfly/patternfly/pull/4723

@mcoker anything to add?

**Comment by mcoker** [comment]
In core, the entire default plain/text options menu toggle is clickable. The pagination component was unique where we made the outer toggle a `<div>`, and only had a `<button>` for the toggle icon so that the text in the toggle wasn't clickable. The core PR just uses the default plain/text variant.

In react, I noticed that the default plain/text outer toggle is a `<div>`. It seems like the change here would just be to update that so that the other toggle is a `<button>` to match core. We discussed this and I can't remember if we decided that changing the element is breaking. There should be no change in classes, layout/spacing, etc. The only problem I could see is if there are user modifications to the toggle that might conflict - as in they may have nested another `<button>` in the toggle (if that's even possible?), styled the toggle by targeting the selector `div.pf-c-options-menu__toggle`, or something like that. I might position this as a bug/a11y fix, but if we wanted to be safe, this could be an opt-in until we have a breaking change and can update the default behavior.

**Comment by thatblindgeye** [comment]
@mcoker I know last you mentioned that you weren't sure whether changing the element for this issue would be a breaking change. Would you or @mcarrano happen to know if there was any update on that and whether we should move forward with making this opt-in for now or just changing that outer `<div>` to a `<button>`?

**Comment by mcarrano** [comment]
I would be OK with just treating this like a bug fix. @mcoker @nicolethoen @tlabaj do you feel comfortable with that? I feel like this is how it should have worked from the onset.
