### ISSUE TITLE
Table demos - improve table data and interactions

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#7384]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Table

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
some of that table demos have pagination components that do not match the data in the table (e.g. pagination says there are 4 pages of data and there are only 5 rows of data in the table.  Let's create some data to be used in all our table examples that would allow us to wire up the pagination to work as expected.  All demos should use the composable table.

This task should be completed as part of this epic:
- [x] #7795
- [x] #7685
- [x] #7855
- [x] #7991
- [x] #7882
- [x] Table: Update sticky header demo data
- [ ] Table: Update compound expansion demo data
- [x] #8066
- [x] #8065
- [x] #8079

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly-design/issues/1157 to create the sample data set to feed these examples.

**Comment by mcarrano** [comment]
Here is some data that can be used based on the design issue above: https://docs.google.com/spreadsheets/d/1-sqIbCpmFfmID0fByWZSOBpn99ocGyT2KoUZ5B_s3zo/edit?usp=sharing  and mockups: https://marvelapp.com/prototype/2ff7ahj6

**Comment by jenny-s51** [comment]
@tlabaj , @mcarrano and I met as a group this afternoon to agree on a plan for the remaining work in this epic!

- **Compound expansion**: remove the toolbar since the toolbar actions are not used, and rename some of the columns to match the new data a bit more closely. Otherwise can leave the general structure of the data/expandable sections as-is.
- **Automatic pagination**: Automatic pagination should be used when the user's data is hardcoded. We need to find a way to highlight this in the docs or potentially rename Automatic pagination to something that conveys it should be used with hardcoded data sets. 
- **Pagination**: Rename Bulk Select to "Pagination with Bulk Select" and add a description underneath that explains that (default) Pagination is used with an external API. If the consumer is working with an external API, default Pagination will programmatically fetch data based on the page and perPage parameters in the URL. 
- **Column Management (draggable)**: Since the Drag and Drop refactor is blocking any work on this demo, #8079 will exist as a standalone issue until the Drag and Drop refactor is complete for the purpose of closing this epic.
