### ISSUE TITLE
Bug - OverflowMenu- Always placed on right

### ISSUE THREAD

**Issue by abhinandan13jan** [patternfly/patternfly-react#7398]
**Describe the problem**
OverflowMenu cannot be placed to left.(like tooltip) It opens always as "placed to the right" which makes it unusable on the righthand side of the screen

**How do you reproduce the problem?**
Place overflowMenu dropdown on right hand side of screen

**Expected behavior**
some property to open it as left placed(like tooltip)

**Screenshots**
<img width="489" alt="Screenshot 2022-05-06 at 4 58 43 PM" src="https://user-images.githubusercontent.com/24852534/167678388-7d674483-5920-485f-8c86-0c736edd380e.png">

<img width="434" alt="Screenshot 2022-05-05 at 7 05 04 PM" src="https://user-images.githubusercontent.com/24852534/167678411-d819b96b-2eb2-4e38-be47-c86949bffaac.png">

**What is your environment?**
Chrome on MacOS

**What is your product and what release date are you targeting?**
Openshift 4.11

**Any other information?**

**Comment by nicolethoen** [comment]
This will likely be addressed when we address: https://github.com/patternfly/patternfly-react/issues/7286

**Comment by nicolethoen** [comment]
@abhinandan13jan Thank you for reporting this issue.
I took a look at it and opened a PR to make a couple tweaks to our docs for clarity.

Since the OverflowMenu component expects the user to pass it a Dropdown for viewing whenever the OverflowControls need to collapse down, you could pass the `position={DropdownPosition.right}` to make the Dropdown menu in your screenshot appear correctly right aligned. Hopefully that helps! Let me know if you have more questions!

**Comment by tlabaj** [comment]
closed by #7545
