### ISSUE TITLE
Tabs - add horizontal tab overflow

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#7479]
Placeholder for core issue https://github.com/patternfly/patternfly/pull/4876

**Comment by wise-king-sullyman** [comment]
@mcarrano @mmenestr would you all expect the overflow tab title to change back to "More" if the user selects another (non-overflowing) tab? Or for it to keep the title of the tab it was previously being used to show?

I've currently got it doing the latter, but I feel like it might be a bit unintuitive since clicking the overflow tab opens the overflow menu again rather than switching back to the tab that it was previously used to select.

What the interaction looks like at the moment:
![horizontal-tab-overflow-demo-1](https://user-images.githubusercontent.com/7115053/180080927-f978945d-b15f-417b-9d97-bc9a50fd6fb4.gif)

Marvel link for easy reference: https://marvelapp.com/prototype/hi2b48a/screen/85423094

**Comment by mcarrano** [comment]
@wise-king-sullyman if the overflow tab looses state as you point out, then yes, I would expect the tab label to revert to "More". @mmenestr do you agree?

**Comment by mmenestr** [comment]
I agree, I think it should revert back to more @mcarrano @wise-king-sullyman
