### ISSUE TITLE
ChartLegendTooltip - allow configurable font size

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly-react#7633]
**Is this a new component or an extension of an existing one?**
ChartLegendTooltip

**Describe the feature**
As far as I can tell, there is no easy way to adjust the font size used by ChartLegendTooltip. The only way I have figured out is to have a complex layering of custom components. The `style` attribute of `ChartLegendTooltip` does not pass through fontSize, fill, or fontFamily to the labels!! This is different from the behavior of the stock ChartTooltip component.

Because of this, I need to have:

- `ChartLegendTooltip` uses custom labelComponent `MyTooltipContent`
- `MyTooltipContent` uses custom labelComponent and titleComponent `MyTooltipLegendLabel`
- `MyTooltipLegendLabel` uses custom legendLabelComponent `MyTooltipLabel`

then, MyTooltipLegendLabel sets a custom `style`, as does MyTooltipLabel, that uses the desired custom font size, font family, fill color, etc.

On top of that, in order to make the legend values appear in the viewport, MyTooltipLegendLabel needs to override `dx` to scale according to the variance from your assumed and fixed 14px font sizing..

After all of that is done, the tooltip still looks awkward, because I still haven't adjusted all of the `x` and `y` values for the individual component. And even if I did that... the overall dimensions of the flyout would need to be managed...

Anyway, all of this because ChartLegendTooltip doesn't pass through the fontSize (and other) attributes...

I must be missing something...

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

https://codesandbox.io/s/epic-gates-m0n2sv

Here is a screenshot showing how the default 14px font size is not well suited to our use case.
<img width="211" alt="Screen Shot 2022-06-29 at 1 43 37 PM" src="https://user-images.githubusercontent.com/4741620/176501741-c30404e4-6b9c-4d48-8da9-dbbd2663c999.png">

And this is what it looks like after all of the hacks... Better, but still the inter-element spacing and the overall size of the tooltip does not yet reflect the smaller font size.

<img width="213" alt="Screen Shot 2022-06-29 at 1 45 00 PM" src="https://user-images.githubusercontent.com/4741620/176502047-d40aa31d-fe2a-44d1-9a26-08f94528eaa8.png">

Again, none of this is a problem with the stock victory chart tooltip component... It works just fine with custom font sizes.

**Any other information?**

**Comment by nicolethoen** [comment]
@dlabrecq do you know if this is possible for the charts' legends already?

**Comment by dlabrecq** [comment]
Spent some time on this and want to share my notes. Overriding `labelComponent` is still the best approach, but I also implemented a fix (https://github.com/patternfly/patternfly-react/pull/7666) to ensure `style` properties are applied properly.

`ChartLegendTooltip` is a complex component that ultimately wraps `ChartTooltip`. However, it also uses custom sub-components to support the legend and title within the tooltip's body. As noted above, the `style` prop is not applied (intentionally) to all sub-components, only `ChartTooltip`.

There are a couple reasons for this.

1. The same `style` props do not always apply to all components; tooltip, legend, and title
2. There may be cases where only one component (e.g., the title) should be styled differently
3. Some Victory based components use different syntax for `style` props

Regarding #3 above, legend styles are defined like this:

`style={{ labels: { fill: "tomato", fontSize: 40 }, title: { fontSize: 20 } }}`

While tooltip styles look more like:

`style={{ fontSize: 20, fill: "tomato" }}`

Therefore, in order to set font size for the title and legend, you need to override the legend and title components to provide unique styles there. The default prop hierarchy for `ChartLegendTooltip` looks like this.

```
ChartLegendTooltip
  labelComponent = ChartLegendTooltipContent

ChartLegendTooltipContent
    labelComponent = ChartLegendTooltipLabel
    legendComponent = ChartLegend
```

The code would look similar to this example:

![Screen Shot 2022-07-06 at 6 09 27 PM](https://user-images.githubusercontent.com/17481322/177653571-7aa671be-e642-4812-928b-492c43d147a0.png)

**Comment by starpit** [comment]
thanks! yes, this is more or less what we had to do. we also had to adjust the `x` and `dx` attributes, to avoid excessive horizontal spacing (we are using a smaller font size)

**Comment by dlabrecq** [comment]
You shouldn't need to adjust the `x` and `dx` props, after my fix. Although, this is exactly how the props are intended to be used. For known font families, Victory does a good job at sizing text, but some adjustments may be necessary.
