### ISSUE TITLE
Styling issue with PF4-React components 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#766]
Investigate why PF4-React components are showing up un-styled in some workspaces configs. The Insights workspace is one example.

This might include building insights frontend to test:

- https://github.com/RedHatInsights/insights-frontend-starter-app
- https://github.com/RedHatInsights/insights-frontend-storybook/blob/master/src/docs/welcome/quickStart/DOC.md

**Comment by dlabaj** [comment]
Fixed in https://github.com/RedHatInsights/insights-frontend-components/pull/112/files. 

The issue was that the project was importing styles and reseting styles. The way the styles would get load it would end up removing and reapplying the styles.  When 1.12 was released we where no longer styling components as was expected on the project, so when the project tried reapplying them it no longer able to do that.  They updated to change the way it was being imported and where able to get the PF4 styles.
