### ISSUE TITLE
Bug - Alert - timeout is not per Alert but cumulative

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#8064]
**Describe the problem**
When we add a couple of Alerts to a AlertGroup and use timeout the alerts don't get triggered to leave after 8 seconds

**How do you reproduce the problem?**
Add 3 alerts to a in a Alert Group within a second and see that only the first one gets hidden after 8 seconds and the the second after 16 seconds and so on.

go to this sandbox: https://codesandbox.io/s/optimistic-gianmarco-w7i186
and click the button 3 times within a second and observe they go away 3 seconds apart from each other.

**Expected behavior**
Expected is that the 8 second timeout is per Alert and not cumulative.

**Is this issue blocking you?**
No, it's just that in our tests we need to explicitly click the alerts away

**Comment by jenny-s51** [comment]
Hi @edewit , thank you for your issue, I have been investigating this behavior. In your codesandbox, it looks like the `onTimeout` function is called to remove the alert from the DOM? If you already pass in the `timeout` prop to dismiss an alert, it looks like you don't need to also pass an `onTimeout` function, since the `timeout` prop has logic to remove the alert.

Here is a sandbox without the `onTimeout`: https://codesandbox.io/s/serene-sanne-liieep?file=/index.js

It looks like the alerts dismiss as expected now - does this resolve your issue @edewit ?

**Comment by edewit** [comment]
That can't be the way to solve it though, so re-opening this. If I don't add the `onTimeout` property the list with alerts will keep growing, thus introducing a memory leak

**Comment by jenny-s51** [comment]
Hi @edewit I discussed this issue with one of our PF experts @jeff-phillips-18 .

There isn't anything we can do on the PF side to fix this, since we are not managing/storing/deleting your alert data from the Keycloak API. Your issue was originally being caused due to the way you were implementing `onTimeout` with the `timeout` prop, but it seems it has since been resolved in Keycloak. 

On the PF side, there cannot be a memory leak, as the alerts always get removed from the DOM. Is it okay if we close this issue since it has been resolved on your end?
