### ISSUE TITLE
File upload multiple - allow custom message text for uploaded files

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#8238]
Want to allow for customizing message text associated with uploaded files.

Original request: https://github.com/patternfly/patternfly/issues/4915

Core PR: https://github.com/patternfly/patternfly/pull/5161

**Comment by wise-king-sullyman** [comment]
@mcarrano the requested custom message is being enabled through the Progress component which File Upload Multiple uses internally, so changes will be needed in Progress as well as File Upload Multiple to enable the requested behavior.

I feel like it would make sense to have separate issues for implementing the text on the Progress component and updating File Upload Multiple to take advantage of the updated Progress API.

I don't think it would be unreasonable to have both issues in the 2022.15 milestone and I would be willing to take them both on since I'm already very familiar with the File Upload Multiple component and the core change linked here. Plus I may be able to get started on them before we formally kick the next sprint off.

Thoughts?

**Comment by mcarrano** [comment]
Sure. I will open an additional issue and link it here.

**Comment by wise-king-sullyman** [comment]
@mcarrano did you have anything in mind for what (if any) demo/example would be added as part of this feature add?

**Comment by mcarrano** [comment]
That's a good question @wise-king-sullyman . The original ask was for something like what is shown below:

![image](https://user-images.githubusercontent.com/6619860/200630674-a9e1887d-e78f-4288-bb83-348cc2992495.png)

Basically it's the ability to display an error if one of the uploads fails. Any way to just use the Basic example but just force an error so someone can see how that's displayed using Helper text?

**Comment by wise-king-sullyman** [comment]
@mcarrano I believe I could do something like that, maybe not forcing a real error but at least making it appear like an error has occurred. Would you just want another checkbox added that causes files uploaded to show as though they've failed?
