### ISSUE TITLE
Input group - updates to support more flexible children

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8264]
Placeholder for core work in https://github.com/patternfly/patternfly/issues/4003

**Comment by srambach** [comment]
In Core PR #5382, a wrapper around input group items was added, so that the wrapper could be used for sizing and spacing rather than selecting and styling individual components. For this issue, add `.pf-c-input-group__item` as a required element around children of `pf-c-input-group`.

https://github.com/patternfly/patternfly/issues/5437 will add documentation of this to core.

**Comment by MariaAga** [comment]
@srambach  Adding the wrapper means users will have to specify `isBox` `isFill` for input groups that worked without them, wont that make the move to v5 very difficult?

**Comment by MariaAga** [comment]
@srambach?
