### ISSUE TITLE
Bug - Popper - `removeFindDomNode` props could cause layout issues

### ISSUE THREAD

**Issue by DaoDaoNoCode** [patternfly/patternfly-react#8277]
**Describe the problem**
Take Tooltip as an example, I have the following use of a tooltip.
```
<span className="odh-card__title-supported">
  {odhApp.spec.displayName}
  <Tooltip content={`${ODH_PRODUCT_NAME} certified and supported`}>
    <img
      className={supportedImageClasses}
      src="../images/CheckStar.svg"
      alt={`${ODH_PRODUCT_NAME} certified and supported`}
    />
  </Tooltip>
</span>
```
`odh-card__title-supported` has the following CSS style:
```
display: flex;
align-items: center;
```

which results in the following:
<img width="100" alt="Screen Shot 2022-10-21 at 12 08 53 PM" src="https://user-images.githubusercontent.com/37624318/197248827-f035204e-5df9-414a-99e3-c10fa21994be.png">

However, if I add `removeFindDomNode` to `Tooltip`, I will get the following:
<img width="100" alt="Screen Shot 2022-10-21 at 12 08 19 PM" src="https://user-images.githubusercontent.com/37624318/197249011-773ac323-0437-446f-a205-b4886a2cd0f4.png">

I checked the HTML and found a div was added which caused the layout issue, the old layout:
<img width="288" alt="Screen Shot 2022-10-21 at 12 10 24 PM" src="https://user-images.githubusercontent.com/37624318/197249129-8400fd30-5326-4cbe-940a-09e500e87ae4.png">

The new layout:
<img width="292" alt="Screen Shot 2022-10-21 at 12 11 05 PM" src="https://user-images.githubusercontent.com/37624318/197249159-b60f0f4e-c02a-4b9b-a745-534010b8418a.png">

**How do you reproduce the problem?**
See the description.

**Expected behavior**
The style should keep the same before and after I apply `removeFindDomNode` to `Tooltip`.

**Is this issue blocking you?**
I can add <Bullseye> to the `children` of `Tooltip` to make it work.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**
Open Data Hub

**Any other information?**

**Comment by kmcfaul** [comment]
`removeFindDomNode` is an opt-in prop for a breaking change (as it adds the extra div to allow the popper to keep track of its own references) so may require additional updates.

Instead of using this prop, you can pass the `reference`, `popperRef`, and `popper` props together (effectively passing the relevant refs for use in the popper) to resolve the strict mode warning without adding the extra `div`.

**Comment by kmcfaul** [comment]
@mcoker @mattnolting Any thoughts about how the extra div may cause issues and what steps we can take to resolve it?

**Comment by mcoker** [comment]
@kmcfaul as we discussed in sprint planning, looks like a perfect use case for `display: contents;` on the extra `<div>` you don't want to impact the existing layout.

**Comment by andrewballantyne** [comment]
I had not heard of `display: contents` before -- so I did a quick google. It seems it's not supported in Safari and has some controversial usage for the CSS community. https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_contents

Did you guys test a `span` instead of a `div`? Did it not have the desired impact? I naively assume this is because of a block element being brought into this? You're just looking for a DOM element to attach a reference to, no?

**Comment by mcoker** [comment]
@andrewballantyne it's generally suitable for use with generic/non-semantic elements, like `<div>` and `<span>`. There are issues with replaced/browser generated elements, and accessibility implications with semantic elements, but in this case I think it would be fine. PatternFly uses it in a handful of components - tree view, progress stepper, and dual list selector.
