### ISSUE TITLE
Composable tree table support

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#8285]
**Is this a new component or an extension of an existing one?**
Existing composable tree table

TODO (more descriptions below):

- [x] Either enable the use of `treeRow` in a `Th` which already uses `isStickyColumn`, or enable `Td` to support `isStickyColumn` (since it already supports `treeRow`)
- [x] Allow for dynamically rendered children as is done in TreeView
- [x] #8603
- [ ] #8604

**Describe the feature**
1. For the HCS UI, we need the first column of the tree table to be sticky -- see mock 1 below.

The sticky column examples use a `Th` (to add `isStickyColumn`) instead of `Td` for the first column.
However, we cannot do that because `treeRow` is required for the first column -- `Td` doesn't support `isStickyColumn`.

2. The tree table requires ALL children to be provided upfront. We need the option to fetch children when a toggle is clicked, but there are no toggles without children. Ideally, there would be a flag to make toggles visible. That way, we could choose to fetch data dynamically when clicked.

In our scenario, the table rows must be created dynamically. We don't know how many children we have until data is fetched for individual rows, while some nodes may not have children at all. The table is also paginated, so children may only be available on another page. Or, a mix of both. Regardless, the columns and rows should still align properly -- see HCS UI screenshot below.

3. When children are omitted, the column formatting is way off. The column heading appears to be left justified, while row cells are right justified.

4. The first column is always indented, regardless if children are provided. Ideally, the first column would not be indented when there are no toggles present -- see mock 2 below. The `level` and `posinset` props don't seem to have any effect.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**HCS UI**
![Screen Shot 2022-10-25 at 10 14 02 AM](https://user-images.githubusercontent.com/17481322/197800742-5ff286bd-59b9-45cc-b138-0d8455084336.png)

**Mock 1**
<img width="1273" alt="Screen Shot 2022-10-25 at 10 27 20 AM" src="https://user-images.githubusercontent.com/17481322/197801238-d156d63d-c84e-4903-901a-6e6b81a28610.png">

**Mock 2**
<img width="1299" alt="Screen Shot 2022-10-25 at 10 27 32 AM" src="https://user-images.githubusercontent.com/17481322/197801196-a1b75eac-544f-4f53-9d41-e1e5e587385c.png">

**Any other information?**

**Comment by dlabrecq** [comment]
@mattnolting @nlcwong

**Comment by dlabrecq** [comment]
In some cases, using `isStickyColumn` for column headings also interferes with the dropdown

**HCS UI**
![Screen Shot 2022-10-25 at 11 42 26 AM](https://user-images.githubusercontent.com/17481322/197821180-f20f075e-b1dd-45d4-ad14-76209ccd8f2a.png)

**Tree table**
![Screen Shot 2022-10-25 at 11 50 18 AM](https://user-images.githubusercontent.com/17481322/197821637-32cd19da-89cb-40bb-8c9d-125595b622aa.png)

**Comment by mcarrano** [comment]
We are assessing for scope and feasibility in the context of https://github.com/patternfly/patternfly-design/issues/1207

**Comment by mcarrano** [comment]
To add more clarification of the requirements, here is a copy of a Slack thread between @mcarrano @dlabrecq @nicolethoen and @patternfly/patternfly-accessibility 

Dan Labrecque
:redhat:  [10:00 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671116440536219)
The tree table has a lot of issues, but the main thing that blocked me was the fact that the entire tree structure must be laid out first.
I need to fetch data as the user expands each node of the tree.
The next major issue was that I couldn't use a sticky column with the tree table (i.e., to make columns horizontally scrollable).
I'm currently using the composable, expandable table. Our data is only one level deep, so it kind of looks like a tree table.
The composable table allows me to use a sticky column, which makes columns horizontally scrollable. (edited) 


Nicole
  [10:01 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671116473862899)
are these new limitations when switching to the composable tree table that were not issues for the legacy table?


Dan Labrecque
:redhat:  [10:02 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671116549178469)
I'm not using a legacy table with the HCS UI (edited) 


Nicole
  [10:02 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671116571866899)
ah okay - that’s good to know
[10:03](https://rhux.slack.com/archives/C04FDLCT490/p1671116609785449)
You may be one of the first consumers really pushing the capabilities of the tree table, so it’s good feedback


Dan Labrecque
:redhat:  [10:04 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671116678055509)
For Cost Management, I was using my own sticky column styles with the legacy table. Now I'm using the composable version.
The HCS UI is my first use of the tree table (edited) 


Natalie
  [10:15 AM](https://rhux.slack.com/archives/C04FDLCT490/p1671117331151869)
FYI, HCS stands for Hybrid Committed Spend. The timeline of the need was supposed to be by the end of the year.


mcarrano
  [12:11 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671124298605989)
So sounds like we have a work around for now, but it would be good to revisit requirements and implementation of the Tree Table, is that a good summary? It might be difficult to address these issues for January, but perhaps we can address this in PatternFly 5. Will that work?


Natalie
  [12:51 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671126679532259)
sure


mcarrano
  [1:48 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671130127486079)
I do have one question, however. 
[@Natalie](https://rhux.slack.com/team/U6VGTPG2V)
 in your issue, you stated the need for sorting. How do you expect that to work. We intentionally did not add sorting to the tree table because sorting items in a tree potentially breaks parent-child relationships. Were you assuming the sort would only apply to the top level nodes?


Dan Labrecque
:redhat:  [1:54 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671130451818269)
For HCS, the root nodes would be the primary sort. A secondary sort could be applied to the child nodes, once expanded.
We just need the table sort controls, the actual sorting would be applied by the APIs (edited) 


mcarrano
  [1:57 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671130663648819)
So the problem I see with this from a design standpoint is that the sort controls live on the column headers, but the child rows do not have separate headers. So if the user clicks sort, would you then apply that to the primary rows and then secondary rows of all expanded nodes?


Dan Labrecque
:redhat:  [2:01 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671130875875469)
It would be applied to all. So an ascending sort by "cost" might look like
$100
$10
$20
$70
$200
$20
$30
$150
(edited)

Dan Labrecque
:redhat:  [2:02 PM](https://rhux.slack.com/archives/C04FDLCT490/p1671130978088409)
The child nodes are expected to add up to the total cost shown by the root (parent) node (edited)

Will pull this into a PatternFly 5 milestone for further work.

**Comment by nicolethoen** [comment]
@dlabrecq couple quick questions.
for your use case, I'm imagining that you are ending up in a state where there are no children - only top level nodes - in your tree table because it's paginated and/or filtered right?

In that case - as you've proposed for the updated design, it'd mean that as filters are applied or removed or as pages are paginated through, the first column would jump around depending on whether or not there are visible expandable rows. Is that ideal? I'm tempted to push back against point 4. If the table is a tree table, even if you've filtered out all expandable rows, I think it still makes sense to leave the space for the expand/collapse arrow. WDYT?

Also, I've built [this code sandbox](https://codesandbox.io/s/determined-waterfall-6e9q6f?file=/index.tsx) which contains a very skeletal recreation of you HCS UI (when you view the resulting webpage in a new window). I _think_ it indicates that the formatting of the table headers might be an implementation issue? I think it should work out of the box?

@mattnolting FYI

**Comment by dlabrecq** [comment]
For our use case, the top level nodes are based on a "primary group by" selection. The child nodes are based on a "secondary group by" selection. I actually make separate API requests based on these two selections, so I never have all the nodes upfront.

In the screenshot below, I'm using an expandable table, which sort of works when there is only one level of children. You can see the top nodes are populated first. Then, the user makes another selection for the child nodes. However, I only make the API request when the user expands a given row.

![chrome-capture-2023-1-9](https://user-images.githubusercontent.com/17481322/217896035-b045cac0-3ee2-4b92-89bc-a9596bd561a2.gif)

Note that the only the top nodes are currently paginated. We would likely use an inner table to paginate child nodes separately.

**Comment by nicolethoen** [comment]
@dlabrecq 
I spent some time trying to build out a demo of a tree table which meets these design specs and I think I was successful. 
https://codesandbox.io/s/sticky-tree-table-65v1fb?file=/index.tsx
It won't take care of the fact that there will be space for an expand toggle even if there are no rows with children to expand. But outside of that it may meet all your requestsS? Could you let me know if this will unblock you or if there is still a feature missing or that I am misunderstanding?

**Comment by dlabrecq** [comment]
I see that the `Td` and `Th` both support `isStickyColumn` now. This helps with some of the layout issues. Still would like to fix the indentation for when there are no children.

That said, the tree table still isn't dynamic. In the example, you know all the child nodes upfront. I'm trying to see if there is a way to create `childRows` dynamically via `onToggleRowDetails`, for example. 

For the HCS UI, we call a function with a known ID when each row is expanded. Is there a way to retrieve the selected row index via `onToggleRowDetails`?

**Comment by nicolethoen** [comment]
@dlabrecq , i've updated [the codesandbox](https://codesandbox.io/s/sticky-tree-table-65v1fb?file=/index.tsx)
some portions of the code to call out:

- i'm imagining that the `function getChildrenRowsByRowId(id: string)` on line 32 is a stand in for the API call.
- I can't think of a way to get around the need for knowing each node's child count upfront. I'm not sure if that information is available via your API. but it's needed because of the `"aria-setsize": node.childCount,` on line 282.
- on line 326, you can see that now i'm only calling renderRows if the parent row is expanded, and one of the params of renderRows in that snippet is calling the `getChildrenRowsByRowId` API call stand in function.
- In case you want to explore using the `onCollapse` callback function for fetching children, I did also add a console statement on line 244 which will show you all the information you have access to when the user expands the row. (I realized that the `onToggleRowDetails` callback is actually only called to toggle the row details hidden by default when in the narrow/responsive view of the default tree table layout)

I've opened [a core issue](https://github.com/patternfly/patternfly/issues/5390) which will need to be addressed first in order to fix the issue with the indentation.

**Comment by dlabrecq** [comment]
Thanks for the updated codesandbox.

API requests are asynchronous, so `getChildrenRowsByRowId` (on line 326) probably wouldn't work because we don't have data available immediately. 

The `onCollapse` function looks promising. It seems to be called whenever a row is expanded, but not certain it's intended to work that way?

Unfortunately, the child node count will never be known upfront. We're lazily making requests, so won't know the total node count until a row is expanded. It looks like -1 can be used if the set size is unknown?

**Comment by nicolethoen** [comment]
@dlabrecq  
I think the child count is not necessary - it only adds more information by setting the `aria-setsize` attribute in the example. That can be left off but does leave some contextual information for users about how many total items are in the data set when they are not all visible on the DOM.

I think I am feeling increasingly confident that, with a little experimenting with your actually API calls, you will be able to manipulate the code sandbox i've provided to dynamically load children rows. 

So outside of the pending work to fix the indentation of rows when there are no children (which is already in PR on the core side) I think the rest of this issue has been addressed?

**Comment by nicolethoen** [comment]
Can be reopened if more needs addressing, but i believe this has been addressed, and a follow up issue has been opened to address the allowing for rows to not be indented if there are no children
