### ISSUE TITLE
TextList - TextList missing plain variant

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#8434]
**Is this a new component or an extension of an existing one?**
extension of TextList

**Describe the feature**
TextList does not include a plain variant (no bullets, no left margin or padding).

If you put a `<List isPlain>` inside a `<TextContent>`, the `isPlain` styling is overridden by the `<TextContent>` styling (margin-left and padding-left).

<img width="1194" alt="Screenshot 2022-12-08 at 10 55 02 AM" src="https://user-images.githubusercontent.com/895728/206497136-edc6c162-a437-443e-b98c-db48dc588271.png">

If you put a `<SimpleList>` inside a `<TextContent>`, the styling is overridden.

<img width="989" alt="Screenshot 2022-12-08 at 10 55 56 AM" src="https://user-images.githubusercontent.com/895728/206497460-2ab0ad3f-944a-4aa8-b1e6-cbc526775801.png">

**Any other information?**

Related issue: https://github.com/patternfly/patternfly-react/issues/8413

**Comment by mcoker** [comment]
Hey @rhamilto, ideally I think you could just use a `<List>` (or any component) there. I'm wondering if we can improve this in a way that's more usable with our upcoming major release. Currently what the text/content component mostly does is:

* Styles simple HTML elements/tags with defaults, so you can just write a block of content without having to specify classnames. Mostly that's for folks writing HTML, not using the react sub components for text/textlist/etc.
* Provides reasonable spacing/layout between those elements when they're used together to format a block of content.

I'm curious what you use the text component for (what it provides you that you get value from), and if you have an idea of how it might work better? I have some ideas, but I'd like to get your perspective first from y'alls use cases.

**Comment by rhamilto** [comment]
> Hey @rhamilto, ideally I think you could just use a `<List>` (or any component) there. I'm wondering if we can improve this in a way that's more usable with our upcoming major release. Currently what the text/content component mostly does is:

I think you missed the point about `<List isPlain>` styling being overridden by `<TextContent>` styling?

> * Styles simple HTML elements/tags with defaults, so you can just write a block of content without having to specify classnames. Mostly that's for folks writing HTML, not using the react sub components for text/textlist/etc.

Ok.  Per the PatternFly documentation, "Text components such as Text, TextList, TextListItem need to be placed within a TextContent".

> * Provides reasonable spacing/layout between those elements when they're used together to format a block of content.

Which I'm assuming is why the docs state the above.  A `<TextList>` without a `<TextContent>` does not render correctly.

<img width="911" alt="Screenshot 2022-12-13 at 4 57 20 PM" src="https://user-images.githubusercontent.com/895728/207452855-765a2dcc-13b2-4e67-ad91-68a18d8d52f8.png">

> I'm curious what you use the text component for (what it provides you that you get value from), and if you have an idea of how it might work better? I have some ideas, but I'd like to get your perspective first from y'alls use cases.

My assumption is adding a plain variant to `<TextList>` is the most backwards-compatible approach since it introduces something new rather than fixing something existing.  But I'm not beholden to this approach.  Whatever the community to decides is best to fix the styling issues with `<List isPlain>` and `<SimpleList>` inside `<TextContent>`.

**Comment by mcoker** [comment]
> ideally I think you could just use a <List> (or any component) there

Sorry about that, I could have worded that better - what I mean is that I'd like to see is you be able to the `<List>` and any of its variations, along with any other component (like `<SimpleList>`), in the `<TextContent>` component and it not introduce style conflicts and it behave as you'd expect it to. Users have reported this issue with other components/variations, like alerts and data-lists:
* <img width="1353" alt="Screenshot 2022-12-13 at 5 55 07 PM" src="https://user-images.githubusercontent.com/35148959/207470884-8aab5cae-e263-43b4-9e4b-4843572fe523.png">
* <img width="1312" alt="Screenshot 2022-12-13 at 5 57 33 PM" src="https://user-images.githubusercontent.com/35148959/207471053-5ca16cbb-9c51-480c-b07a-05ba7dbac5c5.png">

While adding a plain list variation could solve this specific issue, it would be great not to duplicate features we already have, and we will likely continue to have the same issue with other components/variations. So I'm wondering if this is something we can address in v5. First though, I'd love to better understand how folks are using the `<TextContent>` component currently - what it provides, what issues they've had, and any sorts of suggestions based on their usage. I imagine your team has some great use cases and feedback that could help us make this component better.

Some ideas I have:

* Scope the `<TextContent>` styling to classes of that component, instead of styling generic tags/elements. So we'll style `.pf-c-content--paragraph` instead of `<p>` and `.pf-c-content--list` instead of `<ul>/<ol>`.
  * This will get rid of most/all of the style conflicts that will overlap from combining styles like `.pf-c-content ul` and `.pf-c-data-list` (since a data list is a `<ul>`)
* Consider not doubling up on styles for components we already have/support. Eg, `<List>` and `<TextList>` - consider dropping `<TextList>`.
* Separate or expand the block spacing/formatting/layout that the `<TextContent>` component provides to create space between paragraphs, lists, headings, etc, so that component classes can be applied to containers to create that block level spacing, and anything can be put in them. Eg, `.pf-c-content--list-block` creates an element that only provides block level spacing for lists, spacing it appropriately from other stuff around it, and anything can go inside of it. That way you could put a `<List>` in there with no style conflicts between `<List>` and `<TextList>`, but get the `<TextContent>`'s spacing it currently provides for lists.

Allowing for something like:

```
div.pf-c-content
  div.pf-c-content--heading-1-block // creates a container that provides `<h1>` block spacing
    h1.pf-c-title // anything can go here, and it gets `<h1>` block spacing from the parent
  p.pf-c-content--paragraph // the equivalent of `<Text component={TextVariants.p}>` currently, but styles are scoped to `.pf-c-content--paragraph` instead of `.pf-c-content p`
  div.pf-c-content--paragraph-block // creates a container that provides `<p>` block spacing
    <Alert /> // anything can go here, and it gets `<p>` block spacing from the parent
  div.pf-c-content--list-block // creates a container that provides `<ul/ol/dl>` block spacing
    <List isPlain /> // anything can go here, and it gets `<ul/ol/dl>` block spacing from the parent
```

**Comment by rhamilto** [comment]
> While adding a plain list variation could solve this specific issue, it would be great not to duplicate features we already have, and we will likely continue to have the same issue with other components/variations. So I'm wondering if this is something we can address in v5. First though, I'd love to better understand how folks are using the `<TextContent>` component currently - what it provides, what issues they've had, and any sorts of suggestions based on their usage. I imagine your team has some great use cases and feedback that could help us make this component better.

My intention in filing this bug is so that we'd have a backwards-compatible fix in *v4*.  I had to [add a class to OpenShift](https://github.com/openshift/console/pull/12355/files#diff-1fb6fa91d8ff94369eb889cdf8b6e6c0ba62c88a88dbdb444da6a57f88f75a50R342-R349) in order to hack around the issue, something we are trying hard to get out of the business of doing.

> Some ideas I have:
> 
> * Scope the `<TextContent>` styling to classes of that component, instead of styling generic tags/elements. So we'll style `.pf-c-content--paragraph` instead of `<p>` and `.pf-c-content--list` instead of `<ul>/<ol>`.

I personally find `<Text>`, `<TextContent>`, etc. confusing since they duplicate other components that do the same thing (e.g., `<List>`, `<SimpleList>`, `<Title>`).  If `<Text>` is "A text component can wrap any static HTML content you want to place on your page to provide correct formatting when using standard HTML tags.", why does it include a `component` prop and `<TextContent>`, `<TextList>`, etc.?  It seems the initial purpose of the `<Text>` component is lost.  This is probably the root of the confusion surrounding `<Text>`.  The purpose of `<Text>` is muddy.

I think it's entirely appropriate to deprecate and remove conflicting components in the next major release, but would love to see known issues fixed in the current version.  Migrating to a new major version is not a quick and easy change given the vast scope of the OpenShift console.
