### ISSUE TITLE
List-Group a11y/storybook review

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#85]
This issue is just to ensure we are not missing anything w/ the List Group [PR](https://github.com/patternfly/patternfly-react/pull/74) recently merged.

**Comment by jgiardino** [comment]
@priley86 The list group component looks great! There are just a couple of things I noticed:

- In the Linked Items storybook example, a ListGroupItem should have either onClick or href, but not both. 
- In the Custom Content storybook example, you should be able to use the header prop to define the headers.

**Comment by priley86** [comment]
OK! Thanks @jgiardino - I will make the update there...

**Comment by priley86** [comment]
@jgiardino originally I had implemented the `onClick` as to prevent the Storybook page from changing when clicking the linked item, but I agree that it would be better to showcase the linked item as it would be used in the application.

re: the custom content header... this works, but I noted that if you specify an `onClick` instead of an `href`, it will render the header inside of a button. This button also changed the design and adds border radius (not like the others). I think downstream one would still have to render the header separately to maintain the current design. Thoughts?

**Comment by jgiardino** [comment]
Regarding the `href` vs `onClick`, what I meant is that on the [react-bootstrap](https://react-bootstrap.github.io/components.html#listgroup) site, it looks like they expect one of these to be defined, not both. In your storybook example when you include both, it's rendered as a link (versus a button). I'm curious if the `onClick` would still work in that case or if including both would somehow ignore the `onClick` in this component? Is that something that can be tested and verified using storybook (can the action logger show when actions are clicked)? 

And you're right that there is a rounded border in the case where the `onClick` renders a `<button>` instead of `<a>`. Do you anticipate cases where `onClick`/`<button>` would be needed instead of `href`/`<a>`? If so, then that's potentially a bug for patternfly css.

**Comment by priley86** [comment]
Re: `href` vs `onClick` in Linked example. That is how it was added previously to prevent the page change from happening (as to prevent default action), and it seemed to work. But to your point - if it's truly a link, just an `href` for the Linked example is fine with me (even if the page change occurs and we would rather demonstrate that usage)...

Re: `onClick` in Custom Content example. Yes, I think `onClick` is a common behavior for the ListGroupItem. To workaround this, I am guessing we can either:

A. Leave it as it was before the PR - and just provide the example with the heading in the child content
B. Update it as it is in this PR - and file a CSS issue in PF Core to accept buttons / or style it differently (and just noting the style differences after). I can push the Storybook with that there if you'd like...

It's a minor implementation detail that's not really a huge blocker anymore but would be nice to address i.m.o...
