### ISSUE TITLE
React Code Editor - Replace `react-monaco-editor` with `@monaco-editor/react`

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#8578]
The [`react-monaco-editor`](https://github.com/react-monaco-editor/react-monaco-editor) package should be replaced with [`@monaco-editor/react`](https://github.com/suren-atoyan/monaco-react). The latter is much more mature and receives more frequent updates, specifically:

- It has much better documentation
- Doesn't need a WebPack plugin
- Has a stable version

I think this would be a good candidate for the next major version of PatternFly React.

**Comment by jonkoops** [comment]
Alternatively a new package could be created and published under a new major of `@patternfly/react-code-editor`. The 'legacy' version could then be published under a new `@patternfly/react-code-editor-legacy` package to provide a migration path.

**Comment by mcarrano** [comment]
Consider for post v5 as an Editor-Next component.

**Comment by jonkoops** [comment]
Bumping this for stale-ness

**Comment by Chip-L** [comment]
I like the idea behind this. We are using Vite for our product, which doesn't use Webpack. Making Patternfly independent of frameworks should be a requirement.

**Comment by Chip-L** [comment]
So having explored `@monaco-editor/react` further, this uses a CDN to get the monaco editor. This may or may not be a problem for others. However, it is really easy to bypass because you can globally configure the loader so that it will work with whichever framework you need to include.

**Comment by KKoukiou** [comment]
hi, In cockpit we are implementing a new plugin for FS browsing. https://github.com/KKoukiou/cockpit-navigator

We tried using this editor - but it's partially broken due to CSP. Nothing unexpected since the used module has the same CSP issues. https://github.com/microsoft/monaco-editor/issues/271

Did you try the suggested alternative module, but it looks like the CSP issues are fixed. https://github.com/suren-atoyan/monaco-react/issues/83

Thanks for prioritizing this.
