### ISSUE TITLE
Chore: Test react 18

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8699]
This issue is to track work needed to test React 18 in product

**Comment by KKoukiou** [comment]
Can you ellaborste what this issue is about?
react is a peerDependency so it's up to the consumers to install it. You already allow react 18, in:

packages/react-core/package.json:    "react": "^16.8 || ^17 || ^18",

In cockpit we already use react 18 for you interest, so you have a thumbs up from cockpit for react 18 usage with patternfly.

**Comment by tlabaj** [comment]
@KKoukiou that is great!  We had product report the could not upgrade due to some of our outdated dependencies in PF.  Those dependencies have been upgraded now.  This was a placeholder to verify hat we no longer have any blockers in our codebase.  The consumer has since been able to upgrade so we can close this issue.
FYI we just removed support for react 16.
