### ISSUE TITLE
Bug - v5 alpha testing - Popover enableFlip

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9237]
While testing the Cost management UI, we noticed the Popover's `enableFlip` is not working as expected.

**Before**
![Screenshot 2023-06-02 at 8 46 09 PM](https://github.com/patternfly/patternfly-react/assets/17481322/cfa0b46a-4a5e-42ba-b495-c42220bd1067)

**After**
![Screenshot 2023-06-02 at 8 46 18 PM](https://github.com/patternfly/patternfly-react/assets/17481322/1ae5f6a7-0b7c-44f2-86bd-4aa23802945c)

**Code**
![Screenshot 2023-06-02 at 8 51 43 PM](https://github.com/patternfly/patternfly-react/assets/17481322/699f919e-36b0-4a21-97e9-5d441138a6f8)

**HTML**
![Screenshot 2023-06-02 at 8 54 41 PM](https://github.com/patternfly/patternfly-react/assets/17481322/a5e77e47-aee6-4a37-a833-78e737200125)

**Comment by kmcfaul** [comment]
This looks like it could be a z-index issue rather than a flipping issue as the position is the same between screenshots. @mcoker Would there possibly be a conflict between the z-index of the v5 popover and the v4 masthead? I can't remember if we updated that.

Otherwise adding the zIndex prop to popover may resolve the issue. The other possible thing to try is to pass the `triggerRef` (with the reference of the button) in to the popover, to remove the wrapping divs, but I'm not sure that would be causing this specific issue.

**Comment by thatblindgeye** [comment]
Noticing somewhat similar behavior on our v5 surge site for React, where the Popover is rendered beneath the masthead. Continuing to scroll does get the Popover to flip (even without the `enableFlip` prop passed in). 

Seems like it might be an issue we saw recently regarding a Popper-y component being appended inline by default not rendering "above" other areas of the page like the sidebar or masthead (https://github.com/patternfly/patternfly-react/pull/8802). The zIndex prop on Popover may not resolve it since the masthead stacking context is higher than the main page area's (at least based on our v5 surge, but I imagine it's the same for Cost).

**Comment by mcarrano** [comment]
Should we consider reverting this to prior v4 behavior for now?
