### ISSUE TITLE
Remove Stylesheet.create from BackgroundImage & LoginPageHeader

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#939]
BackgroundImage & LoginPageHeader need to be updated to not use Stylesheet.create and to take their styles directly from core (pf-next).

**Comment by dmiller9911** [comment]
This is required for the environment. Images move in each environment. In the case of gatsby node_modules/* is not available. So it is not possible to use those are the path for the background image. They need to be overwritten in 90% of environments for React. Having these driven by props instead of CSS will give the consumer more control over where the images are hosted. You can view more of the reasoning here: https://github.com/patternfly/patternfly-react/pull/710#discussion_r222834182 it speaks to why we chose to implement this in the lib itself instead of pushing it to consumers.

If the implementation needs changed all react projects implementing these components will need to be updated. Also, if we decide to take values directly from pf-next they will not just work for webpack projects. An example of properly overriding this will need to be made available.

**Comment by rachael-phillips** [comment]
Spoke with @dlabaj and we'll close this.
