### ISSUE TITLE
Bug - [TextInput] - ["type=number" still allows entering normal text in the input field on firefox]

### ISSUE THREAD

**Issue by subhoghoshX** [patternfly/patternfly-react#9391]
**Describe the problem**
Even after passing the prop `type="number"`, `TextInput` component still allows entering normal text.

**How do you reproduce the problem?**
[On firefox] It can be reproduced in the docs (https://staging.patternfly.org/components/forms/text-input#basic). Toggle code editor and change the value of type prop from "text" to "number"

**Is this issue blocking you?**
kind of :)

**Screenshots**
On firefox:
![image](https://github.com/patternfly/patternfly-react/assets/108616679/ac0e9194-5213-4e7c-a72f-9126ac749d61)

**What is your environment?**
 - OS: fedora-38
 - Browser: firefox

**Comment by kmcfaul** [comment]
There is an open issue on Mozilla discussing this issue [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528). In short, this seems like inconsistent browser behaviors instead of being a bug within our component. Chrome and IE attempt to sanitize input on entry (but doesn't catch all invalid entries like combining scientific notation `e` with punctuation in an invalid way) while Safari and Firefox allow any entry, and assume validation will happen after on a form submit if the input has `required`. 

We could attempt to add validation to the TextInput component ourselves on the keyDown event, or include a [polyfill of some kind](https://github.com/jonstipe/number-polyfill), but what do others on the team think? @nicolethoen @wise-king-sullyman @thatblindgeye @tlabaj

**Comment by thatblindgeye** [comment]
Agreed with leaving it as-is and having it be something that would be on consumers to implement.

**Comment by kmcfaul** [comment]
Closing for now as its a browser issue, and adding internal validation would vary based on user specification (allowing/disallowing scientific notation, etc) and language (. vs , for delimiting, etc).
