### ISSUE TITLE
Spike: Implement/enable RTL in charts

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#9431]
Victory charts has an 'orientation' feature which _should_(?) allow for RTL language support. 
https://github.com/FormidableLabs/victory/issues/739

we should investigate whether we can enable RTL language support based on the presence of RTL language in the `<html lang='x'>` tag or `<html dir='RTL'>`

Spike should produce a POC/recommendation

**Comment by kmcfaul** [comment]
To enable RTL in charts, the `ChartAxis` component has the `invertAxis` property, which will reverse the data direction (both labels and chart data) on that axis. The `orientation` property on `ChartAxis` will control the labels' overall position on the chart, but not the data direction.

As for automated detection of RTL, it depends on how the RTL is specified. Internally we could attempt to set a default on the `invertAxis` property by looking at the document element's `lang` property, or a specific element's `dir` property (because it appears `dir` can be set on anything). But we'd have to decide on which approach, and additionally on an app-level, there should be a control for selecting a language that could be used to conditionally pass the `invertAxis` property instead.

The only things we may want to look into further for RTL support of charts is the legend rendering + position. Right now it does not have full support of `left` position orientation (the current accepted values are "bottom", "bottom-left", and "right". You can pass "left" and it works except for vertical alignment). Also, the data color blocks on the legend are left-aligned with no option to be right aligned, which I think we may need or want for RTL.

**Comment by kmcfaul** [comment]
Opened #9541 to follow up on legends and closing this issue.
