### ISSUE TITLE
Bug - ChartDonutUtilization - Performance issue on safari

### ISSUE THREAD

**Issue by metalice** [patternfly/patternfly-react#9498]
**Describe the problem**
On safari browser component ChartDonutUtilization causes the page to be laggy and lack performance. 

**How do you reproduce the problem?**
Just use ChartDonutUtilization without any data (no props at all) to check the difference between chrome and safari while navigating between pages.

**Expected behavior**
Smooth as chrome

**Is this issue blocking you?**
Yes

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/14824964/ac7ed947-9878-4425-99ca-eedf3bed32e1)

ChartDonutUtilization component is mounted:
![pattern-fly](https://github.com/patternfly/patternfly-react/assets/14824964/a73d5045-984c-4353-88c3-c442a5f4f187)

ChartDonutUtilization component is unmounted:
![pattern-fly-unmounted](https://github.com/patternfly/patternfly-react/assets/14824964/e7f23554-43e9-4fbd-a91e-98912cadf374)

**What is your environment?**
 - OS: macos 13.5
 - Browser safari, chrome
 - Version @patternfly/react-charts: ^6.84.8

**What is your product and what release date are you targeting?**
kubevirt-plugin

**Any other information?**

**Comment by wise-king-sullyman** [comment]
CC @dlabrecq

**Comment by dlabrecq** [comment]
Logged into OpenShift and the app definitely seems less performant on Safari than with Chrome.
However, I can see fetching in the network tab while the chart is not visible.
The chart seems to appear immediately after the fetch, but the fetch is noticeably longer with Safari.

Looking at some of the code, I can see `ChartDonutUtilization` isn't rendered unless data is available. There is a `ComponentReady` component that shows a spinner, instead of the chart, while data is not available.

For example:
https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx#L55

That said, it appears that the fetch may be the performance bottleneck on Safari. This is a case where a code sandbox example would help to isolate components from the network traffic.

**Comment by metalice** [comment]
I can try to disable the fetching and give some hard-coded data - let's see if it will work. Why it's only on Safari?
