### ISSUE TITLE
Bug - Page - PageSection noPadding seems to have no effect?

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly-react#9548]
**Describe the problem**
A PageSection with `padding={{default: 'noPadding'}}` still has padding.

**How do you reproduce the problem?**
https://codesandbox.io/s/quirky-jang-wkj3xc

**Expected behavior**
PageSections with noPadding should have no padding?

**Is this issue blocking you?**
Using `type=subnav` rather than `type=nav` on the PageSection seems to work around this. It is unclear whether this is a bug or expected behavior, as the docs do not specify that noPadding does not apply to `nav`.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - OS: mac
 - Browser chrome
 - Version patternfly 5

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by mcoker** [comment]
@starpit you're correct, the docs are not clear. Currently we only allow modifying padding via the `padding` prop on `.pf-[v]-page__main-section` (`<PageSection />` either with no `type`, or with `type="default"`). `type="subnav"` doesn't have padding to begin with, so that's why it seems to work. Though we may end up adding padding for subnav sections at some point, so that may not be the best option.

If you're able to just use `<PageSection />` without a `type`, that should work predictably. I would also be in favor of adding support for the `padding` prop on other variants variants via the `type` prop, so that you could use `padding` and `type="nav"` together. WDYT @tlabaj @andrew-ronaldson?

**Comment by starpit** [comment]
re: no type, we want a footer in our page. without type, the last section floats, even if the prior section has `isFilled` (which also seems odd). you can experiment with this in the codesandbox i linked in the issue.

**Comment by mcoker** [comment]
@starpit ah gotcha! The last section is `isFilled` by default, and multiple sections can be set to `isFilled`. If you only want the section before the footer to fill, you'll need to set `isFilled={false}` on the footer - https://codesandbox.io/s/sad-bartik-fc8wm2
