### ISSUE TITLE
(Login Page): Add Penta tokens

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9845]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6026

**Comment by kmcfaul** [comment]
Doesn't look like LoginPage currently needs any react update to reflect the new penta design.

https://github.com/patternfly/patternfly/issues/6098 is open to fix the footer font color (shouldn't need a react update but TBD). 

The slight variation in icon size is due to outdated tokens in react (the same token is used but boils down to 16px in core and 22px in react right now) and should be fixed with a core update.

The difference in form spacing will be resolved with form penta updates.
