### ISSUE TITLE
Bug - Docs - Card docs mentions isSelectableRaised is preferred

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#9872]
Docs mention that `isSelectableRaised` is preferred over `isSelectable`, but in reality `isSelectableRaised` is deprecated?

https://www.patternfly.org/components/card#selectable-cards-deprecated

**Comment by jschuler** [comment]
oh , may be a grammatical misunderstanding (comma)
`This example uses the isSelectable property instead of isSelectableRaised, which is the current recommendation for implementation. `

**Comment by tlabaj** [comment]
@edonehoo What do you think about the wording her and the confusion it may cause.  DO you think it should be updated?

**Comment by edonehoo** [comment]
@tlabaj I'm actually also confused reading it, even though I wrote it hah. It looks like this content was written for PF 4, where the "current" selectable example used isSelectableRaised - [https://v4-archive.patternfly.org/v4/components/card#selectable-cards](https://v4-archive.patternfly.org/v4/components/card#selectable-cards). Is the PF 5 "deprecated" example incorrect since it doesn't match the PF 4 implementation? [https://www.patternfly.org/components/card#selectable-cards-deprecated](https://www.patternfly.org/components/card#selectable-cards-deprecated )

I may be wrong here

**Comment by edonehoo** [comment]
If I am wrong, though, it seems like there's no use of isSelectableRaised in the examples on the PF 5 site -- so I do think the description needs to be updated for clarity, which I can do

**Comment by edonehoo** [comment]
It looks like these docs are currently fine. Either this was addressed by https://github.com/patternfly/patternfly-react/pull/10056 or https://github.com/patternfly/patternfly-react/pull/10168, or there was just an initial misunderstanding (due to that comma). Regardless, no further changes are needed here from what I can tell!
