### ISSUE TITLE
Consume core Penta updates: Spinner

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9915]
Follow up to core PR https://github.com/patternfly/patternfly/pull/6154

**Comment by thatblindgeye** [comment]
Shouldn't need any updates in React. React is using the diameter CSS var which remains intact in Core, otherwise the React examples match Core examples in terms of visuals and markup. Since the examples show animation it may be easier to show a side by side of alpha 51 locally vs the Core v6 staging.

**Comment by thatblindgeye** [comment]
Closing per comments above + agreement from @andrew-ronaldson
