### ISSUE TITLE
Consume core updates: Calendar month and Date picker ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9998]
Follow up to issue core  https://github.com/patternfly/patternfly/issues/5734

Updated in PR #10081 to fix build
- `CalendarMonth` `prevMonth` and `nextMonth` modifiers removed, using a string now.

**Comment by thatblindgeye** [comment]
Doesn't seem like either CalendarMonth or DatePicker need React updates.

- [React v6 Calendar Month](https://patternfly-react-v6.surge.sh/components/date-and-time/calendar-month) vs [Core v6 Calendar Month
](https://pf6.patternfly.org/components/date-and-time/calendar-month)- [React v6 Date Picker](https://patternfly-react-v6.surge.sh/components/date-and-time/date-picker) vs [Core v6 Date Picker
](https://pf6.patternfly.org/components/date-and-time/date-picker)

The MenuToggle in React v6 is a little off compared to Core (more noticeable when you select "October" in the React example) due to a width being set on the toggle within the React code and the MenuToggle having `justify-content: center`. The inline width is so the toggle width won't change with each month selection. We may want to apply the full width modifier to MenuToggle, but that requires an update in Core as the styling is also off for a [full width menu toggle](https://patternfly-react-v6.surge.sh/components/menus/menu-toggle/#full-width-toggle). Depending on the update made in Core, we could move the inline width styling in React from the MenuToggle to the div calMonth header wrapper.

**Comment by thatblindgeye** [comment]
cc @andrew-ronaldson @mcoker for above comment to confirm whether additional updates are needed in React

**Comment by mcoker** [comment]
@thatblindgeye lgtm, looking at the core PRs, doesn't look like there were any updates other than adding an icon to the error helper text for one of the datepicker examples https://pf6.patternfly.org/components/date-and-time/date-picker/#invalid

**Comment by andrew-ronaldson** [comment]
lgtm!

**Comment by thatblindgeye** [comment]
Closing per agreements above
